from importlib import import_module


type_module_name_map = {
	'Byte': 'nifgen.formats.base.basic',
	'Ubyte': 'nifgen.formats.base.basic',
	'Uint64': 'nifgen.formats.base.basic',
	'Int64': 'nifgen.formats.base.basic',
	'Uint': 'nifgen.formats.base.basic',
	'Ushort': 'nifgen.formats.base.basic',
	'Int': 'nifgen.formats.base.basic',
	'Short': 'nifgen.formats.base.basic',
	'Char': 'nifgen.formats.base.basic',
	'Normshort': 'nifgen.formats.base.basic',
	'Rangeshort': 'nifgen.formats.base.basic',
	'Float': 'nifgen.formats.base.basic',
	'Double': 'nifgen.formats.base.basic',
	'Hfloat': 'nifgen.formats.base.basic',
	'ZString': 'nifgen.formats.base.basic',
	'ZStringBuffer': 'nifgen.formats.base.compounds.ZStringBuffer',
	'PadAlign': 'nifgen.formats.base.compounds.PadAlign',
	'FixedString': 'nifgen.formats.base.compounds.FixedString',
	'Vector2': 'nifgen.formats.base.compounds.Vector2',
	'Vector3': 'nifgen.formats.base.compounds.Vector3',
	'Vector4': 'nifgen.formats.ms2.compounds.Vector4',
	'Bool': 'nifgen.formats.ovl_base.basic',
	'OffsetString': 'nifgen.formats.ovl_base.basic',
	'Compression': 'nifgen.formats.ovl_base.enums.Compression',
	'VersionInfo': 'nifgen.formats.ovl_base.bitfields.VersionInfo',
	'Pointer': 'nifgen.formats.ovl_base.compounds.Pointer',
	'Reference': 'nifgen.formats.ovl_base.compounds.Reference',
	'LookupPointer': 'nifgen.formats.ovl_base.compounds.LookupPointer',
	'ArrayPointer': 'nifgen.formats.ovl_base.compounds.ArrayPointer',
	'CondPointer': 'nifgen.formats.ovl_base.compounds.CondPointer',
	'ForEachPointer': 'nifgen.formats.ovl_base.compounds.ForEachPointer',
	'MemStruct': 'nifgen.formats.ovl_base.compounds.MemStruct',
	'SmartPadding': 'nifgen.formats.ovl_base.compounds.SmartPadding',
	'ZStringObfuscated': 'nifgen.formats.ovl_base.basic',
	'GenericHeader': 'nifgen.formats.ovl_base.compounds.GenericHeader',
	'Empty': 'nifgen.formats.ovl_base.compounds.Empty',
	'ZStringList': 'nifgen.formats.ovl_base.compounds.ZStringList',
	'BiosynVersion': 'nifgen.formats.ms2.basic',
	'MainVersion': 'nifgen.formats.ms2.basic',
	'BonePointerIndex': 'nifgen.formats.ms2.basic',
	'MeshFormat': 'nifgen.formats.ms2.enums.MeshFormat',
	'WeightsFlag': 'nifgen.formats.ms2.bitfields.WeightsFlag',
	'WeightsFlagMalta': 'nifgen.formats.ms2.bitfields.WeightsFlagMalta',
	'ModelFlag': 'nifgen.formats.ms2.bitfields.ModelFlag',
	'ChunkedModelFlag': 'nifgen.formats.ms2.bitfields.ChunkedModelFlag',
	'ModelFlagZT': 'nifgen.formats.ms2.bitfields.ModelFlagZT',
	'ModelFlagDLA': 'nifgen.formats.ms2.bitfields.ModelFlagDLA',
	'RenderFlag': 'nifgen.formats.ms2.bitfields.RenderFlag',
	'CollisionType': 'nifgen.formats.ms2.enums.CollisionType',
	'AfterJointsPadding': 'nifgen.formats.ms2.compounds.AfterJointsPadding',
	'Matrix44': 'nifgen.formats.ms2.compounds.Matrix44',
	'Matrix33': 'nifgen.formats.ms2.compounds.Matrix33',
	'AxisAngle': 'nifgen.formats.ms2.compounds.AxisAngle',
	'StreamDebugger': 'nifgen.formats.ms2.compounds.StreamDebugger',
	'Bone': 'nifgen.formats.ms2.compounds.Bone',
	'Ms2Root': 'nifgen.formats.ms2.compounds.Ms2Root',
	'BufferPresence': 'nifgen.formats.ms2.compounds.BufferPresence',
	'MaterialName': 'nifgen.formats.ms2.compounds.MaterialName',
	'LodInfo': 'nifgen.formats.ms2.compounds.LodInfo',
	'Object': 'nifgen.formats.ms2.compounds.Object',
	'MeshData': 'nifgen.formats.ms2.compounds.MeshData',
	'ChunkedMesh': 'nifgen.formats.ms2.compounds.ChunkedMesh',
	'NewMeshData': 'nifgen.formats.ms2.compounds.NewMeshData',
	'PcMeshData': 'nifgen.formats.ms2.compounds.PcMeshData',
	'ZtMeshData': 'nifgen.formats.ms2.compounds.ZtMeshData',
	'MeshDataWrap': 'nifgen.formats.ms2.compounds.MeshDataWrap',
	'ZTPreBones': 'nifgen.formats.ms2.compounds.ZTPreBones',
	'DLAPreBones': 'nifgen.formats.ms2.compounds.DLAPreBones',
	'FloatsY': 'nifgen.formats.ms2.compounds.FloatsY',
	'Model': 'nifgen.formats.ms2.compounds.Model',
	'ZtTriBlockInfo': 'nifgen.formats.ms2.compounds.ZtTriBlockInfo',
	'ZtVertBlockInfo': 'nifgen.formats.ms2.compounds.ZtVertBlockInfo',
	'InfoZTMemPool': 'nifgen.formats.ms2.compounds.InfoZTMemPool',
	'StreamsZTHeader': 'nifgen.formats.ms2.compounds.StreamsZTHeader',
	'Buffer0': 'nifgen.formats.ms2.compounds.Buffer0',
	'BufferInfo': 'nifgen.formats.ms2.compounds.BufferInfo',
	'ModelInfo': 'nifgen.formats.ms2.compounds.ModelInfo',
	'ModelReader': 'nifgen.formats.ms2.compounds.ModelReader',
	'Ms2InfoHeader': 'nifgen.formats.ms2.compounds.Ms2InfoHeader',
	'TriChunk': 'nifgen.formats.ms2.compounds.TriChunk',
	'VertChunk': 'nifgen.formats.ms2.compounds.VertChunk',
	'MinusPadding': 'nifgen.formats.ms2.compounds.MinusPadding',
	'ZerosPadding': 'nifgen.formats.ms2.compounds.ZerosPadding',
	'UACJoint': 'nifgen.formats.ms2.compounds.UACJoint',
	'AbstractPointer': 'nifgen.formats.ms2.compounds.AbstractPointer',
	'BonePointer': 'nifgen.formats.ms2.compounds.BonePointer',
	'RotationRange': 'nifgen.formats.ms2.compounds.RotationRange',
	'IKEntry': 'nifgen.formats.ms2.compounds.IKEntry',
	'IKTarget': 'nifgen.formats.ms2.compounds.IKTarget',
	'IKInfo': 'nifgen.formats.ms2.compounds.IKInfo',
	'JointTransform': 'nifgen.formats.ms2.compounds.JointTransform',
	'RigidBody': 'nifgen.formats.ms2.compounds.RigidBody',
	'JointPointer': 'nifgen.formats.ms2.compounds.JointPointer',
	'Constraint': 'nifgen.formats.ms2.compounds.Constraint',
	'PushConstraint': 'nifgen.formats.ms2.compounds.PushConstraint',
	'StretchConstraint': 'nifgen.formats.ms2.compounds.StretchConstraint',
	'RagdollConstraint': 'nifgen.formats.ms2.compounds.RagdollConstraint',
	'UACJointFF': 'nifgen.formats.ms2.compounds.UACJointFF',
	'Sphere': 'nifgen.formats.ms2.compounds.Sphere',
	'BoundingBox': 'nifgen.formats.ms2.compounds.BoundingBox',
	'Capsule': 'nifgen.formats.ms2.compounds.Capsule',
	'Cylinder': 'nifgen.formats.ms2.compounds.Cylinder',
	'ConvexHull': 'nifgen.formats.ms2.compounds.ConvexHull',
	'SubA': 'nifgen.formats.ms2.compounds.SubA',
	'MeshCollisionBit': 'nifgen.formats.ms2.compounds.MeshCollisionBit',
	'SubCollChunk': 'nifgen.formats.ms2.compounds.SubCollChunk',
	'MeshCollision': 'nifgen.formats.ms2.compounds.MeshCollision',
	'HitCheck': 'nifgen.formats.ms2.compounds.HitCheck',
	'JointInfo': 'nifgen.formats.ms2.compounds.JointInfo',
	'HitcheckReader': 'nifgen.formats.ms2.compounds.HitcheckReader',
	'JointData': 'nifgen.formats.ms2.compounds.JointData',
	'BoneInfo': 'nifgen.formats.ms2.compounds.BoneInfo',
	'MeshCollisionData': 'nifgen.formats.ms2.compounds.MeshCollisionData',
}

name_type_map = {}
for type_name, module in type_module_name_map.items():
	name_type_map[type_name] = getattr(import_module(module), type_name)
for class_object in name_type_map.values():
	if callable(getattr(class_object, 'init_attributes', None)):
		class_object.init_attributes()
