#!/bin/sh
/mnt/compendium/DevLab/dexvert/build/build --silent programs formats
DENO_DIR=/mnt/compendium/.deno deno run --unstable --import-map /mnt/compendium/DevLab/deno/importMap.json --allow-read --allow-run --allow-write --allow-env testid.js "$@"
