#!/bin/sh
/mnt/compendium/DevLab/dexvert/build/build --silent programs formats
DENO_DIR=/mnt/compendium/.deno deno run --v8-flags=--max-old-space-size=32768 --no-check --unstable --import-map /mnt/compendium/DevLab/deno/importMap.json --allow-env --allow-read --allow-write --allow-run testdexvert.js "$@"
