
// DO NOT EDIT MANUALLY
// AUTO GENERATED BY build/buildFormats.js
// DO NOT EDIT MANUALLY
import {families} from "../family/families.js";
import unsupported from "./unsupported.js";
import {Format} from "../Format.js";
const formats = {};
import {revisableFormText} from "./document/revisableFormText.js";
formats.revisableFormText = revisableFormText.create(families.document);
import {macBinary} from "./archive/macBinary.js";
formats.macBinary = macBinary.create(families.archive);
import {cdi} from "./archive/cdi.js";
formats.cdi = cdi.create(families.archive);
import {windowsThumbDB} from "./archive/windowsThumbDB.js";
formats.windowsThumbDB = windowsThumbDB.create(families.archive);
import {stDiskImage} from "./archive/stDiskImage.js";
formats.stDiskImage = stDiskImage.create(families.archive);
import {msCompound} from "./archive/msCompound.js";
formats.msCompound = msCompound.create(families.archive);
import {windowsSCR} from "./executable/windowsSCR.js";
formats.windowsSCR = windowsSCR.create(families.executable);
import {txtByFilename} from "./text/txtByFilename.js";
formats.txtByFilename = txtByFilename.create(families.text);
import {tga} from "./image/tga.js";
formats.tga = tga.create(families.image);
import {xwd} from "./image/xwd.js";
formats.xwd = xwd.create(families.image);
import {pgm} from "./image/pgm.js";
formats.pgm = pgm.create(families.image);
import {advancedArtStudio} from "./image/advancedArtStudio.js";
formats.advancedArtStudio = advancedArtStudio.create(families.image);
import {artworx} from "./image/artworx.js";
formats.artworx = artworx.create(families.image);
import {fractalImageFormat} from "./image/fractalImageFormat.js";
formats.fractalImageFormat = fractalImageFormat.create(families.image);
import {eps} from "./image/eps.js";
formats.eps = eps.create(families.image);
import {apStar} from "./image/apStar.js";
formats.apStar = apStar.create(families.image);
import {a2gsSHStar} from "./image/a2gsSHStar.js";
formats.a2gsSHStar = a2gsSHStar.create(families.image);
import {gif} from "./image/gif.js";
formats.gif = gif.create(families.image);
import {ami} from "./image/ami.js";
formats.ami = ami.create(families.image);
import {imageSystem} from "./image/imageSystem.js";
formats.imageSystem = imageSystem.create(families.image);
import {aai} from "./image/aai.js";
formats.aai = aai.create(families.image);
import {a2eDoubleHighRes} from "./image/a2eDoubleHighRes.js";
formats.a2eDoubleHighRes = a2eDoubleHighRes.create(families.image);
import {macPaint} from "./image/macPaint.js";
formats.macPaint = macPaint.create(families.image);
import {degasHiPI} from "./image/degasHiPI.js";
formats.degasHiPI = degasHiPI.create(families.image);
import {threeDCK} from "./image/threeDCK.js";
formats.threeDCK = threeDCK.create(families.image);
import {all} from "./image/all.js";
formats.all = all.create(families.image);
import {ans} from "./image/ans.js";
formats.ans = ans.create(families.image);
import {png} from "./image/png.js";
formats.png = png.create(families.image);
import {ppm} from "./image/ppm.js";
formats.ppm = ppm.create(families.image);
import {pcx} from "./image/pcx.js";
formats.pcx = pcx.create(families.image);
import {cdr} from "./image/cdr.js";
formats.cdr = cdr.create(families.image);
import {artDirector} from "./image/artDirector.js";
formats.artDirector = artDirector.create(families.image);
import {bmp} from "./image/bmp.js";
formats.bmp = bmp.create(families.image);
import {dr2d} from "./image/dr2d.js";
formats.dr2d = dr2d.create(families.image);
import {a4r} from "./image/a4r.js";
formats.a4r = a4r.create(families.image);
import {mrw} from "./image/mrw.js";
formats.mrw = mrw.create(families.image);
import {drHalo} from "./image/drHalo.js";
formats.drHalo = drHalo.create(families.image);
import {ags} from "./image/ags.js";
formats.ags = ags.create(families.image);
import {aniST} from "./image/aniST.js";
formats.aniST = aniST.create(families.image);
import {aliasPIX} from "./image/aliasPIX.js";
formats.aliasPIX = aliasPIX.create(families.image);
import {pbm} from "./image/pbm.js";
formats.pbm = pbm.create(families.image);
import {autoSketchDrawing} from "./image/autoSketchDrawing.js";
formats.autoSketchDrawing = autoSketchDrawing.create(families.image);
import {afl} from "./image/afl.js";
formats.afl = afl.create(families.image);
import {draw256} from "./image/draw256.js";
formats.draw256 = draw256.create(families.image);
import {jpg} from "./image/jpg.js";
formats.jpg = jpg.create(families.image);
import {sunRaster} from "./image/sunRaster.js";
formats.sunRaster = sunRaster.create(families.image);
import {qrt} from "./image/qrt.js";
formats.qrt = qrt.create(families.image);
import {hiPic} from "./image/hiPic.js";
formats.hiPic = hiPic.create(families.image);
import {mur} from "./image/mur.js";
formats.mur = mur.create(families.image);
import {amf} from "./image/amf.js";
formats.amf = amf.create(families.image);
import {svg} from "./image/svg.js";
formats.svg = svg.create(families.image);
import {bld} from "./image/bld.js";
formats.bld = bld.create(families.image);
import {acornDraw} from "./image/acornDraw.js";
formats.acornDraw = acornDraw.create(families.image);
import {webp} from "./image/webp.js";
formats.webp = webp.create(families.image);
import {amosIcons} from "./image/amosIcons.js";
formats.amosIcons = amosIcons.create(families.image);
import {a2HighRes} from "./image/a2HighRes.js";
formats.a2HighRes = a2HighRes.create(families.image);
import {a2gsPreferred} from "./image/a2gsPreferred.js";
formats.a2gsPreferred = a2gsPreferred.create(families.image);
import {acornSprite} from "./image/acornSprite.js";
formats.acornSprite = acornSprite.create(families.image);
import {telepaint} from "./image/telepaint.js";
formats.telepaint = telepaint.create(families.image);
import {a2Sprites} from "./image/a2Sprites.js";
formats.a2Sprites = a2Sprites.create(families.image);
import {pcd} from "./image/pcd.js";
formats.pcd = pcd.create(families.image);
import {hsiRaw} from "./image/hsiRaw.js";
formats.hsiRaw = hsiRaw.create(families.image);
import {artistByEaton} from "./image/artistByEaton.js";
formats.artistByEaton = artistByEaton.create(families.image);

// process our 'unsupported.js' formats
for(const [familyid, unsupportedFormats] of Object.entries(unsupported))
{
	for(const [formatid, o] of Object.entries(unsupportedFormats))
	{
		const supportedKeys = ["name", "ext", "magic", "weakMagic", "filename", "notes"];
		const extraKeys = Object.keys(o).subtractAll(supportedKeys);
		if(extraKeys.length>0)
			throw new Error(`unsupported format ${familyid}/${formatid} has extra keys that are not currently copied over to the Unknown class, add them: ${extraKeys}`);
		
		class Unsupported extends Format
		{
			unsupported = true;
		}

		formats[formatid] = Unsupported.create(families[familyid], format =>	// eslint-disable-line sembiance/shorter-arrow-funs
		{
			for(const supportedKey of supportedKeys)
			{
				if(Object.hasOwn(o, supportedKey))
					format[supportedKey] = o[supportedKey];
			}
		});
	}
}
export {formats};
