import {TEXT_MAGIC} from "../Detection.js";

// All of the formats in this file are 'simple' files that should just be handled with the 'strings' program and are not worthy of having their own file
// Because 'strings' will take any file, ONLY include items here that have 'strong' magic (or mark the magic as weak when paired with an ext)
// Each entry also has the following properties added:
//	forbidExtMatch : true			(Only if ext is set)
//	converters     : ["strings"]
export default
{
	document :
	{
		acrossCrosswordPuzzle    : {name : "Across Crossword Puzzle", ext : [".puz"], magic : ["PUZ crossword puzzle", "Across crossword puzzle"]},
		actWordProcessorDocument : {name : "ACT! Word Processor Document", ext : [".wpa", ".tpl", ".rep", ".wpd"], magic : ["ACT! word processor document"], weakMagic : true},
		adorageScript			 : {name : "Adorage Script", ext : [".scp"], magic : ["Adorage Script"]},
		amigaProWrite 			 : {name : "Amiga ProWrite Document", magic : ["Amiga ProWrite document", "IFF data, ProWrite document"]},
		appleWorksDocument       : {name : "AppleWorks Document", magic : ["AppleWorks Word Processor"], forbiddenMagic : TEXT_MAGIC},
		askSamDatabase           : {name : "askSam Database", ext : [".ask"], magic : ["askSam database", "askSam Windows database"]},
		atariWorks               : {name : "Atari Works Document", ext : [".stw"], magic : ["Atari Works Wordprocessor document"]},
		atariWorksDatabase       : {name : "Atari Works Database", ext : [".std"], magic : ["Atari Works Database"]},
		atariWorksSpreadsheet    : {name : "Atari Works Spreadsheet", ext : [".sts"], magic : ["Atari Works Spreadsheet"]},
		bankBookForWindows       : {name : "Bank Book for Windows Account Data", ext : [".dat"], magic : ["Bank Book for Windows account Data"]},
		borlandTurboVisionHelp   : {name : "Borland Turbo Vision Help", ext : [".hlp"], magic : ["Borland Turbo Vision Help"]},
		cambridgeZ88Basic        : {name : "Cambridge Z88 Basic", ext : [".bas"], magic : ["Cambridge Z88 BASIC tokenized source"], weakMagic : true},
		catalogTranslation       : {name : "Amiga Catalog Translation file", ext : [".ct"], magic : ["catalog translation"]},
		centralPointHelp         : {name : "Central Point Help", ext : [".hlp"], magic : ["Central Point Software Help data"]},
		clarionHelp              : {name : "Clarion Help", ext : [".hlp"], magic : ["Clarion for DOS Help", "Clarion Developer (v2 and above) help data"], trustMagic : true},
		clarionMemo              : {name : "Clarion Memo", ext : [".mem"], magic : ["Clarion Developer (v2 and above) memo data"]},
		codeViewHelp             : {name : "Codeview Help", ext : [".hlp"], magic : ["Codeview Help"]},
		corelPresentations       : {name : "Corel/WordPerfect Presentations", ext : [".shw", ".mst", ".prt"], magic : ["WordPerfect Presentations", "WordPerfect/Corel Presentations"]},
		czHelp                   : {name : "CZ Help", ext : ["hlp"], magic : ["CZ Help"]},
		dageshDocument           : {name : "Dagesh Document", ext : [".dgs"], magic : ["Dagesh document"]},
		dataBaseProfessional     : {name : "DataBase Professional Database", ext : [".db"], magic : ["DataBase Professional database"]},
		dBASEMultipleIndex       : {name : "dBASE Multiple Index", ext : [".mdx"], magic : ["dBASE IV Multiple index", "FoxBase MDX"]},
		decisionPadWorksheet     : {name : "Decision Pad Worksheet", ext : [".dpw"], magic : ["Decision Pad Worksheet"]},
		demoManiacScript         : {name : "DemoManiac SCript", ext : [".script"], magic : ["DemoManiac Script"], weakMagic : true},
		deScribe                 : {name : "DeScribe Document", ext : [".doc", ".des"], magic : ["DeScribe document"]},
		deskMate                 : {name : "DeskMate Document", ext : [".doc"], magic : ["DeskMate document"]},
		easyCalc                 : {name : "EasyCalc Spreadsheet file", ext : [".calc"], magic : ["EasyCalc spreadsheet"]},
		enableDocument           : {name : "Enable Document", ext : [".wpf"], magic : ["Enable document"], weakMagic : true},
		epicITS                  : {name : "Epic ITS", ext : [".int"], magic : ["Epic ITS format"]},
		epocDatabase             : {name : "EPOC Database", magic : ["Psion Series 5 database Data file", "EPOC Data database"]},
		expressPublisher		 : {name : "Express Publisher Document", ext : [".epd"], magic : ["Express Publisher document"]},
		fileMakerPro             : {name : "FileMaker Pro Database", ext : [".fp3"], magic : ["FileMaker Pro 3 database", "Filemaker Pro (generic)", "FileMaker Pro database", /^x-fmt\/318( |$)/], website : "http://fileformats.archiveteam.org/wiki/FileMaker_Pro"},
		firstChoiceDatabase      : {name : "First Choice Database", ext : [".fol", ".pfs"], magic : ["First Choice database", /^fmt\/1284( |$)/], weakMagic : true},
		formMasterForm           : {name : "Form Master Form", ext : [".frm"], magic : ["Form Master Form"]},
		frameMakerBook           : {name : "FrameMaker Book", ext : [".book"], magic : ["FrameMaker book"]},
		frameworkDocument        : {name : "FrameworkDocument", ext : [".fw2", ".fw3"], magic : [/^Framework.* document/]},
		gnuInfo                  : {name : "GNU Info File", ext : [".info-1", ".info-2", ".info-3", ".info-4", ".info-5", ".info-6", ".info-7", ".info-8", ".info-9"], magic : [/^GNU Info$/]},	// We do NOT include Trid's "GNU Info document" because it's too loose
		goldDiskSpreadsheet      : {name : "Gold Disk Spreadsheet", ext : [".adv", ".pcf"], magic : ["Gold Disk Office Calc/Graph spreadsheet"]},
		helmMultimediaBook       : {name : "Helm Multimedia Book", magic : ["Helm multimedia book"]},
		helpLibrarian            : {name : "Help Librarian Help File", ext : [".hlp"], magic : ["C-Worthy Help Librarian Data"], website : "http://fileformats.archiveteam.org/wiki/Help_Librarian"},
		homeAccounts             : {name : "Home Accounts", ext : [".ha", ".ha2"], magic : ["Home Accounts account"]},
		hotHelpCatalog           : {name : "HotHelp Catalog", ext : [".cat"], magic : ["HotHelp Catalog"]},
		hyperBook                : {name : "HyperBook", magic : ["HyberBook document"]},
		hyperTextVSUM            : {name : "HyperText VSUM", ext : [".xdb"], magic : ["HyperText VSUM"]},
		ibmStoryboardStory       : {name : "IBM Storyboard Story", ext : [".sh", ".sh~"], magic : ["IBM Storyboard Story", "IBM PC Storyboard Story"]},
		ibmWorksForOS2           : {name : "IBM Works for OS/2", ext : [".lwp", ".lpw"], magic : ["IBM Works for OS/2 word processor document"]},
		iffDOCDesktopPublishing  : {name : "IFF DOC Desktop Publishing", magic : ["IFF data, DOC desktop publishing document"]},
		interPress               : {name : "Xerox InterPress Document", ext : [".ip", ".ip2"], magic : ["Xerox InterPress data", "Interpress format"]},
		itsInternational         : {name : "ITS International Module", ext : [".int"], magic : ["ITS international module"]},
		kamasOutline             : {name : "KAMAS Outline", ext : [".kam"], magic : ["KAMAS Outline"]},
		locomotiveBASIC          : {name : "Locomotive BASIC", ext : [".bas"], magic : ["Amstrad CPC Locomotive BASIC tokenized source"]},
		lotusManuscript          : {name : "Lotus Manuscript Document", ext : [".doc"], magic : ["Lotus Manuscript Document"]},
		lotusNotes               : {name : "Lotus Notes Database", ext : [".nsf"], magic : ["Lotus Notes database"]},
		lotusScreenCamScript     : {name : "Lotus ScreenCam Caption Script", ext : [".scs"], magic : ["Lotus ScreenCam Caption Script"]},
		magneticPages            : {name : "Magnetic Pages Article", magic : ["Magnetic Pages article"]},
		messageLibrarian         : {name : "Novell/C-Worthy Message Librarian", ext : [".msg", ".dat"], magic : [/^Novell [Mm]essage [Ll]ibrarian [Dd]ata/, "C-Worthy Message Librarian Data"]},
		microHelp                : {name : "MicroHelp", ext : [".slb"], magic : ["MicroHelp Library"]},
		microsoftLesson          : {name : "Microsoft Lesson", ext : [".les", ".lsn"], magic : ["Microsoft Lesson/tutorial"]},
		newAgeHelp               : {name : "NewAge Help", ext : [".hlp"], magic : ["NewAge Help"]},
		novellDOSClientMessage   : {name : "Novell DOS Client Message", ext : [".msg"], magic : ["Novell DOS client message"]},
		novellHelpLibrarian      : {name : "Novell Help Librarian", ext : [".hlp"], magic : ["Novell Help Librarian Data"]},
		oberonDocument           : {name : "Oberon Document", ext : [".odc"], magic : ["Oberon/F Document"]},
		oberonText               : {name : "Oberon Text", ext : [".mod"], magic : ["Oberon V4 text format"]},
		orgPlus                  : {name : "OrgPlus", ext : [".opx", ".ops"], magic : ["OrgPlus Organization Chart", /^fmt\/1457( |$)/]},
		os2Message               : {name : "OS/2 Message File", ext : [".msg"], magic : [/^OS\/2 help [Mm]essage/], website : "http://fileformats.archiveteam.org/wiki/MSG_(OS/2)"},
		ovationPro               : {name : "Ovation Pro Document", ext : [".dpd"], magic : ["Ovation Pro"]},
		pageSetter               : {name : "PageSetter Document", ext : [".ps"], magic : [/^PageSetter I{0,3} ?document/]},
		palmTealMeal             : {name : "Palm TealMeal Document", ext : [".pdb"], magic : ["Palm TealMeal"]},
		palmThoughtManager       : {name : "Palm ThoughtManager", ext : [".pdb"], magic : ["Palm ThoughtManager"]},
		papyrus                  : {name : "Papyrus", ext : [".pap"], magic : ["Papyrus document"]},
		pcpHelpText              : {name : "PCP Help Text", ext : [".pag"], magic : ["PCP Help Text"]},
		pcTypeDocument           : {name : "PC-Type Document", ext : [".pct"], magic : ["PC-Type document"]},
		peterNortonHelp          : {name : "Peter Norton Computing Help", ext : [".hlp"], magic : ["Peter Norton Computing Help"]},
		professionalPage         : {name : "Professional Page Document", magic : ["Professional Page document"]},
		proText                  : {name : "ProText Document", magic : ["Protext document"]},
		psion3Word               : {name : "Psion Series 3 Word Document", ext : [".wrd"], magic : ["Psion serie 3 word document"], website : "http://fileformats.archiveteam.org/wiki/Psion_Series_3_Word"},
		psionAgenda              : {name : "Psion Agenda", ext : [".agn"], magic : ["Psion S3a/3c/Siena Agenda"]},
		psionDatabase            : {name : "Psion Database", ext : [".dbf", ".odb"], magic : ["Psion serie 3 Database"]},
		psionSpreadsheet         : {name : "Psion Spreadsheet", ext : [".spr"], magic : ["Psion SH3 Spreadsheet"]},
		qAndADocument            : {name : "Q&A Document", ext : [".doc"], magic : ["Q and A Document", /^fmt\/1045( |$)/]},
		quill                    : {name : "Quill Document", ext : [".doc"], magic : ["Quill Document"], website : "http://www.rwapadventures.com/ql_wiki/index.php?title=Quill"},
		riscOSBBCBasic           : {name : "RISC OS BBC BASIC V Source", magic : ["RISC OS BBC BASIC V source"]},
		samnaWordDocument        : {name : "Samna Word Document", ext : [".sm"], magic : ["Samna Word Document"]},
		smartSoftwareDocument    : {name : "Smart Software Document", ext : [".doc"], magic : ["Smart Software Document"]},
		sprint                   : {name : "Sprint Document", ext : [".spr"], magic : ["Sprint document"], weakMagic : true},
		stFaxScript              : {name : "STFax Script", ext : [".script"], magic : ["STFax Script"]},
		stWriter                 : {name : "ST Writer Document", magic : ["ST Writer document"]},
		sundialClearlook         : {name : "Sundial Clearlook", ext : [".ctx"], magic : ["Sundial Clearlook document"]},
		superCalc                : {name : "SuperCalc Worksheet", ext : [".cal"], magic : ["SuperCalc worksheet", "SuperCalc 2/3 spreadsheet", /^fmt\/403( |$)/]},
		symantecQADatabase       : {name : "Symantec Q&A Database File", ext : [".dtf"], magic : ["Symantec QandA Database File"]},
		tempusWord               : {name : "Tempus Word Document", ext : [".twd"], magic : ["Tempus Word Document"]},
		textEngine               : {name : "Text Engine Document", ext : [".std"], magic : ["TextEngine document (generic)", "TextEngine document (v4.0)", "TextEngine document (v5.2)"], weakMagic : ["TextEngine document (generic)"]},
		textMakerDocument        : {name : "TextMaker Document", ext : [".tmd"], magic : ["TextMaker document"]},
		textPlus                 : {name : "Text Plus Document", ext : [".txp"], magic : ["Text Plus document"]},
		theWorksSpreadsheet      : {name : "The Works! Spreadsheet", ext : [".sht"], magic : ["The Works! Spreadsheet"]},
		twistDB                  : {name : "Twist Database file", ext : [".db"], magic : ["Twist DataBase"]},
		usefulNotesNote          : {name : "Useful Notes Note", ext : [".uno"], magic : ["Useful Notes Note"], weakMagic : true},
		vendInfoDataRecord       : {name : "VENDINFO Data Record", magic : ["VENDINFO data record"]},
		vgaPaint386Help          : {name : "VGAPaint 386 Help", ext : [".hlp"], magic : ["VGAPaint 386 Help"]},
		vipPhonebook             : {name : "V.I.P. Phonebook", ext : [".dat"], magic : ["V.I.P. phonebook data"]},
		visualXBaseForm          : {name : "Visual XBase Form", ext : [".ww"], magic : ["Visual XBase form/screen"], weakMagic : true},
		vxRexxInfo               : {name : "VX-REXX Windows/Object Info", ext : [".vry", ".vrw"], magic : ["VX-REXX windows/object info"]},
		winAsksQuestionaire      : {name : "WinAsks Questionnaire", ext : [".wap", ".wa"], magic : ["WinAsks Editor Questionnaire"]},
		windows31Registry        : {name : "Windows 3.1 Registry", magic : ["MS Windows 3.1 registry file"]},
		wingzHelp                : {name : "Wingz Help", magic : [/^Wingz [Hh]elp/]},
		wingzSpreadsheet         : {name : "Wingz Spreadsheet", ext : [".wkz"], magic : ["Wingz spreadsheet"]},
		winWorks                 : {name : "WinWorks Document", ext : [".wpd"], magic : ["WinWorks text Document"]},
		zincData                 : {name : "Zinc Data", ext : [".dat", ".znc", ".z_t"], magic : ["Zinc Data"], website : "https://en.wikipedia.org/wiki/Zinc_Application_Framework"},
		zxSpectrumDOSBASICSource : {name : "ZX Spectrum DOS BASIC Source Code", ext : [".bas"], magic : ["ZX spectrum +3 DOS BASIC source"]}
	},
	
	other :
	{
		agSIHelpFile                    : {name : "agSI Help File", ext : [".hlp"], magic : ["agSI Help File"]},
		amiDockConfig                   : {name : "AmiDock Configuration", ext : [".config"], magic : ["AmiDock Configuration"], weakMagic : true},
		amigaGuideIndex                 : {name : "Amigaguide Index", ext : [".index"], magic : ["Amigaguide Index"]},
		amosMenuBank                    : {name : "AMOS Menu Bank", ext : [".abk"], magic : ["AMOS Menu Bank"]},
		atariSTGuideHypertext           : {name : "Atari ST Guide Hypertext", ext : [".hyp"], magic : ["Atari ST Guide Hypertext document", "Atari ST Guide Hypertext"]},
		atariSTGuideREF                 : {name : "Atari ST Guide REF Links", ext : [".ref"], magic : ["Atari ST Guide ref links"]},
		bbxFile                         : {name : "bbX File", magic : ["BBx "]},
		borlandCProject                 : {name : "Borland C/C++ Project", ext : [".prj"], magic : ["Borland Turbo C Project", "Borland C++"]},
		borlandReflexDatabase           : {name : "Borland Reflex Database", ext : [".rxd"], magic : ["Borland Reflex Database", /^fmt\/393( |$)/]},
		borlandTurboVisionResource      : {name : "Borland Turbo Vision Resource", ext : [".res", ".tvr"], magic : ["Borland Turbo Vision Resource"]},
		briefCompiledMacro              : {name : "Brief Compiled Macro", ext : [".cm"], magic : ["Brief Compiled Macro"]},
		calendarCreatorPlus             : {name : "Calendar Creator Plus Project", ext : [".cce", ".bin"], magic : ["Calendar Creator Plus", /^x-fmt\/141( |$)/]},
		canDoVariables                  : {name : "CanDo Variables/Data", ext : [".var", ".data"], magic : ["CanDo Variables/data container"]},
		clarionTopspeed                 : {name : "Clarion Topspeed Data File", ext : [".tps"], magic : ["Clarion Topspeed Data file"]},
		compuserveInformationManagerDB  : {name : "Compuserve Information Manager DB", magic : ["CompuServe Information Manager DB"]},
		corelPlanPerfect                : {name : "Corel Plan Perfect", ext : [".pln"], magic : ["Corel Plan Perfect"]},
		cubicPlayerModuleInfoDB         : {name : "Cubic Player Module Information Database", ext : [".dat"], magic : ["Cubic Player module information data base"]},
		cWorthyErrorLibrarian           : {name : "C-Worthy Error Librarian Data", ext : [".dat"], magic : ["C-Worthy Error Librarian Data"]},
		cWorthyForm                     : {name : "C-Worthy Form", ext : [".cwa"], magic : ["C-Worthy Form"]},
		cWorthyOverlay                  : {name : "C-Worthy Machine Overlay", ext : [".ovl"], magic : ["C-Worthy Machine Dependant Overlay"]},
		dartDesktop                     : {name : "Dart Desktop", ext : [".dsk"], magic : ["Dart Desktop"]},
		databenchData                   : {name : "Databench Data", magic : ["Databench data"]},
		db2Bind                         : {name : "DB2 Bind", ext : [".bnd"], magic : ["DB2 Bind"]},
		dBaseLabelDesign                : {name : "dBase Label Design", ext : [".lbl"], magic : ["dBASE IV Label design"]},
		deluxePrint                     : {name : "Deluxe Print Document/Project", ext : [".bnr2", ".lbl2", ".lhd2", ".sgn2", ".bnnr", ".labl", ".lthd", ".sign"], magic : ["Deluxe Print"]},
		developerStudioProject          : {name : "Microsoft Developer Studio Project", ext : [".mdp"], magic : ["Microsoft Developer Studio Project"]},
		directorSTXT                    : {name : "Director STXT", ext : [".stxt"], magic : ["Director STXT"], weakMagic : true},
		epocInstallationPackage         : {name : "EPOC Installation Package", ext : [".sis"], magic : ["EPOC Installation package", "Symbian installation file"]},
		frontRunnerBinaryModule         : {name : "FrontRunner Binary Module", ext : [".frb"], magic : ["FrontRunner Binary module"]},
		geosConvert                     : {name : "GEOS ConVerT", ext : [".cvt"], magic : ["GEOS ConVerT container format"], website : "http://unusedino.de/ec64/technical/formats/cvt.html"},
		gfaBASICAmiga                   : {name : "GFA-BASIC Amiga", ext : [".gfa", ".bas"], magic : ["GFA-BASIC Amiga"]},
		gfaBASICMSDOS                   : {name : "GFA-BASIC MS-DOS", ext : [".gfa", ".bas"], magic : ["GFA-BASIC MS-DOS"]},
		gfaBasicWindows                 : {name : "GFA-BASIC Windows", ext : [".gfw"], magic : ["GFA-BASIC Windows v3 tokenized source"]},
		harvardTotalProject             : {name : "Harvard Total Project Manager Project", ext : [".prj"], magic : ["Harvard Total Project Manager Project"]},
		ibmPCOverlay                    : {name : "IBM PC Overlay", ext : [".ovl"], magic : ["IBM PC Overlay"]},
		iBrowseCookies                  : {name : "iBrowse Cookies", filename : ["Cookies"], magic : ["IBrowse Cookies"]},
		iffCTLG                         : {name : "Amiga IFF Catalog", ext : [".catalog"], magic : ["IFF data, CTLG message catalog", "Amiga Catalog translation format"], website : "http://fileformats.archiveteam.org/wiki/IFF"},
		innoSetupLog                    : {name : "Inno Setup Log", ext : [".dat"], magic : ["Inno Setup Uninstall Log", "InnoSetup Log"]},
		installShieldPackage            : {name : "InstallShield Package", ext : [".pkg"], magic : ["InstallShield compiled setup Package"]},
		installShieldScript             : {name : "InstallShield Script", ext : [".ins"], magic : ["InstallShield Script"]},
		jamMessageAreaHeaderFile        : {name : "JAM Message Area Header File", ext : [".jhr"], magic : ["JAM message area header file"], weakMagic : true},
		javelinCaseStudy                : {name : "Javelin Case Study", ext : [".cas"], magic : ["Javelin Case study"]},
		maxonMultimediaScript           : {name : "Maxon Multimedia Script", magic : ["MaxonMULTIMEDIA script"]},
		metaEditMethodDefinition        : {name : "MetaEdit Method Definition", ext : [".mof"], magic : ["MetaEdit Method definition"]},
		microsoftVisualCBinaryResource  : {name : "Microsoft Visual C Binary Resource", ext : [".aps"], magic : ["Microsoft Visual C .APS file", "Visual C++ binary resource"]},
		microStationResource            : {name : "MicroStation Resource Data", ext : [".dat", ".ma"], magic : ["MicroStation Resource data"]},
		midiInstrumentDefinitionFile    : {name : "MIDI Instrument Definition File", ext : [".idf"], magic : ["MIDI Instrument Definition File"]},
		moneyMatters                    : {name : "Money Matters Data", ext : [".mm"], magic : ["Money Matters"]},
		msvcPCH                         : {name : "Microsoft Visual C PCH file", magic : ["Microsoft Visual C .pch"]},
		msVisualFoxProApp               : {name : "MS Visual FoxPro App", ext : [".app", ".fxp"], magic : ["Generated application MS Visual FoxPro 7"]},
		msWinCEInstallHeader            : {name : "Microsoft WinCE Install Header", ext : [".000"], magic : ["Microsoft WinCE install header"]},
		noteWorthyComposure             : {name : "NoteWorthy Composure", ext : [".nw"], magic : ["NoteWorthy song"]},
		novellErrorLibrarian            : {name : "Novell Error Librarian", ext : [".dat", ".idx"], magic : ["Novell Error Librarian Data"]},
		nsFileWrapperSerializedData     : {name : "NSFileWrapper Serialized Data", magic : ["NSFileWrapper serialized data"]},
		omnisStudioDatabase             : {name : "Omnis Studio Database", ext : [".df1", ".lbr"], magic : ["Omnis Studio Database"]},
		objectVisionDatafile            : {name : "ObjectVision Datafile", ext : [".ovd"], magic : ["ObjectVision Datafile"]},
		powerWindowsProject             : {name : "PowerWindows Project", ext : [".pw"], magic : ["PowerWindows Project"]},
		qseqProject                     : {name : "QSEQ Project", ext : [".qsq"], magic : ["QSEQ project"]},
		quickBasicTokenizedSource       : {name : "QuickBASIC Tokenized Source", ext : [".bas"], magic : [/^Microsoft QuickBASIC \d\.\d tokenized source$/, /^QuickBASIC Extended .*Source$/]},
		quickPascalUnit                 : {name : "Microsoft QuickPascal Unit", ext : [".qpu"], magic : ["Microsoft QuickPascal Unit"]},
		reSourceControlLanguage         : {name : "ReSource Control Language", ext : [".rcl"], magic : ["ReSource Control Language"], weakMagic : true},
		rmQuestModule                   : {name : "RM/Quest Module", ext : [".qrm"], magic : ["RM/Quest module"]},
		sixtyFourNetContainer           : {name : "64Net Container", ext : [".n64"], magic : ["64NET container"], weakMagic : true},
		sybaseIAnywhereIndex            : {name : "Sybase iAnywhere Index", ext : [".cdx"], magic : ["Sybase iAnywhere index files", "xBase compound index"], weakMagic : ["xBase compound index"]},
		telemateCompiledScript          : {name : "Telemate Compiled Script", ext : [".tms"], magic : ["Telemate compiled script"]},
		telixPhonebook                  : {name : "Telix Phonebook", ext : [".fbk"], magic : ["Telix Phonebook"]},
		turboBASICChainModule           : {name : "Turbo Basic Chain module", ext : [".tbc"], magic : ["Turbo Basic compiled Chain module"]},
		turboCConfiguration             : {name : "Turbo C Configuration", ext : [".tc"], magic : ["Turbo C Configuration"]},
		turboCContextFile               : {name : "Turbo C Context File", ext : [".dsk"], magic : ["Turbo C Context"]},
		turboDebuggerConfig             : {name : "Turbo Debugger Configuration", ext : [".td", ".td2"], magic : ["Turbo Debugger configuration"]},
		turboPascalChainModule          : {name : "Turbo Pascal Chain module", ext : [".chn"], magic : [/^Turbo Pascal [23].0 Chain module$/]},
		turboPascalConfiguration        : {name : "Turbo Pascal Configuration File", ext : [".tp"], magic : ["Turbo Pascal configuration"]},
		turboPascalCompiledCPMCOM	    : {name : "Turbo Pascal Compiled 8bit CP/M-80 COM", ext : [".com"], magic : ["8bit CP/M-80 COM Turbo Pascal compiled"]},
		turboPascalDesktopFile          : {name : "Turbo Pascal Desktop File", ext : [".dsk"], magic : ["Turbo Pascal Desktop"]},
		turboPascalOverlay              : {name : "Turbo Pascal Overlay", ext : [".ovr"], magic : ["Turbo Pascal Overlay"]},
		typedStreamData                 : {name : "NeXT TypedStream Data", magic : ["NeXT typedstream serialized data", "NeXT/Apple typedstream data"]},
		venturaPublisherStyleSheet      : {name : "Ventur Publisher Style Sheet", ext : [".sty"], magic : ["Ventura Publisher Style sheet"]},
		verityCollectionIndexDescriptor : {name : "Verity Collection Index Descriptor", ext : [".wld", ".ddd", ".did", ".pdd", ".rsd"], magic : ["Verity Collection Index Descriptor", /^fmt\/461( |$)/], weakMagic : true},
		vimSwap                         : {name : "Vim Swap", ext : [".swp"], magic : ["Vim swap"]},
		visualBasicForm                 : {name : "Visual Basic Form", ext : [".frm"], magic : ["Visual Basic Form", /^fmt\/(1541|1542)( |$)/], website : "http://fileformats.archiveteam.org/wiki/VisualBasic_form"},
		visualBasicProject              : {name : "Visual Basic Project", ext : [".mak"], magic : ["Visual Basic project"], website : "http://fileformats.archiveteam.org/wiki/Visual_Basic_project_file"},
		windowsHelpFileContent          : {name : "Microsoft Windows Help File Content", ext : [".cnt"], magic : ["Help File Contents", "MS Windows help file Content"]},
		windowsProgramGroup             : {name : "Windows Program Group", ext : [".grp"], magic : ["Windows Program Manager Group", "Windows 3.x .GRP file"]},
		wingzScript                     : {name : "Wingz Script", ext : [".scz"], magic : ["Wingz script", "Wingz compiled script"]},
		wordSearchManiaPuzzle           : {name : "Wordsearch Mania! Puzzle", ext : [".wsp"], magic : ["Wordsearch Mania! Puzzle"]},
		wordStarMacro                   : {name : "WordStar Macro", ext : [".wsm"], magic : ["WordStar Macro"]},
		zingDirectoryInfo               : {name : "Zing! Directory Info", ext : [".zing"], magic : ["Zing! directory info"]}
	}
};
