import {TEXT_MAGIC} from "../Detection.js";

// All of the formats in this file are 'simple' files that should just be handled with the 'strings' program and are not worthy of having their own file
// Because 'strings' will take any file, ONLY include items here that have 'strong' magic (or mark the magic as weak when paired with an ext)
// Each entry also has the following properties added:
//	forbidExtMatch : true			(Only if ext is set)
//	converters     : ["strings"]
export default
{
	document :
	{
		acrossCrosswordPuzzle    : {name : "Across Crossword Puzzle", ext : [".puz"], magic : ["PUZ crossword puzzle", "Across crossword puzzle"], website : "http://fileformats.archiveteam.org/wiki/PUZ_(crossword_puzzles)"},
		actWordProcessorDocument : {name : "ACT! Word Processor Document", ext : [".wpa", ".tpl", ".rep", ".wpd"], magic : ["ACT! word processor document"], weakMagic : true},
		adorageScript            : {name : "Adorage Script", ext : [".scp"], magic : ["Adorage Script"]},
		amigaProWrite            : {name : "Amiga ProWrite Document", magic : ["Amiga ProWrite document", "IFF data, ProWrite document"]},
		amiProWordProDocument    : {name : "Ami Pro/Word Pro document", ext : [".sam"], magic : ["Ami Pro/Word Pro document", "Lotus AmiPro Dokument", /^x-fmt\/191( |$)/], weakMagic : true},
		appleWorksDocument       : {name : "AppleWorks Document", magic : ["AppleWorks Word Processor", "AppleWorks document"], forbiddenMagic : TEXT_MAGIC},
		askSamDatabase           : {name : "askSam Database", ext : [".ask"], magic : ["askSam data base", "askSam for Windows data base", "askSam DB"]},
		atariWorks               : {name : "Atari Works Document", ext : [".stw"], magic : ["Atari Works Wordprocessor document"]},
		atariWorksDatabase       : {name : "Atari Works Database", ext : [".std"], magic : ["Atari Works Database"]},
		atariWorksSpreadsheet    : {name : "Atari Works Spreadsheet", ext : [".sts"], magic : ["Atari Works Spreadsheet"]},
		bankBookForWindows       : {name : "Bank Book for Windows Account Data", ext : [".dat"], magic : ["Bank Book for Windows account Data"]},
		borlandTurboVisionHelp   : {name : "Borland Turbo Vision Help", ext : [".hlp"], magic : ["Borland Turbo Vision Help", "Turbo Vision Hilfedatei"]},
		cambridgeZ88Basic        : {name : "Cambridge Z88 Basic", ext : [".bas"], magic : ["Cambridge Z88 BASIC tokenized source"], weakMagic : true},
		catalogTranslation       : {name : "Amiga Catalog Translation file", ext : [".ct"], magic : ["catalog translation", "Amiga Catalog Translation"]},
		centralPointHelp         : {name : "Central Point Help", ext : [".hlp"], magic : ["Central Point Software Help data"]},
		clarionHelp              : {name : "Clarion Help", ext : [".hlp"], magic : ["Clarion for DOS Help", "Clarion Developer (v2 and above) help data"]},
		clarionMemo              : {name : "Clarion Memo", ext : [".mem"], magic : ["Clarion Developer (v2 and above) memo data"]},
		codeViewHelp             : {name : "Codeview Help", ext : [".hlp"], magic : ["Codeview Help"]},
		comitHelp                : {name : "COMit Help", ext : [".h!"], magic : ["COMit Help"], weakMagic : true},
		corelPresentations       : {name : "Corel/WordPerfect Presentations", ext : [".shw", ".mst", ".prt"], magic : ["WordPerfect Presentation", "WordPerfect/Corel Presentations", /^fmt\/(878|1837)( |$)/], website : "http://fileformats.archiveteam.org/wiki/SHW_(Corel)"},
		dageshDocument           : {name : "Dagesh Document", ext : [".dgs"], magic : ["Dagesh document"]},
		dataBaseProfessional     : {name : "DataBase Professional Database", ext : [".db"], magic : ["DataBase Professional database"]},
		dBaseMultipleIndex       : {name : "dBase Multiple Index", ext : [".mdx"], magic : ["dBASE IV Multiple index", "FoxBase MDX"], weakMagic : true},
		decisionPadWorksheet     : {name : "Decision Pad Worksheet", ext : [".dpw"], magic : ["Decision Pad Worksheet"]},
		demoManiacScript         : {name : "DemoManiac SCript", ext : [".script"], magic : ["DemoManiac Script"], weakMagic : true},
		deScribe                 : {name : "DeScribe Document", ext : [".doc", ".des"], magic : ["DeScribe document"]},
		deskMate                 : {name : "DeskMate Document", ext : [".doc"], magic : ["DeskMate document"]},
		easyCalc                 : {name : "EasyCalc Spreadsheet file", ext : [".calc"], magic : ["EasyCalc spreadsheet"]},
		enableDocument           : {name : "Enable Document", ext : [".wpf"], magic : ["Enable document"], weakMagic : true},
		epicITS                  : {name : "Epic ITS", ext : [".int"], magic : ["Epic ITS format"]},
		epocDatabase             : {name : "EPOC Database", magic : ["Psion Series 5 database Data file", "EPOC Data database"]},
		expressPublisher         : {name : "Express Publisher Document", ext : [".epd"], magic : ["Express Publisher document"]},
		firstChoiceDatabase      : {name : "First Choice Database", ext : [".fol", ".pfs"], magic : ["First Choice database", /^fmt\/1284( |$)/], weakMagic : true},
		fl2com                   : {name : "FL2COM", ext : [".com"], magic : ["FL2COM", "16bit COM FL2COM reader"], website : "http://fileformats.archiveteam.org/wiki/FL2COM"},
		formMasterForm           : {name : "Form Master Form", ext : [".frm"], magic : ["Form Master Form"]},
		fourDWriteDocument       : {name : "4D Write document", magic : ["4D Write document"], idMeta : ({macFileType, macFileCreator}) => macFileType==="4WRT" && ["Twri", "B.G.", "BGCV"].includes(macFileCreator)},
		frameMakerBook           : {name : "FrameMaker Book", ext : [".book"], magic : ["FrameMaker book"], idMeta : ({macFileType, macFileCreator}) => macFileType==="FBok" && macFileCreator==="Fram"},
		geoWorksGeoWriteDocument : {name : "GeoWorks GeoWrite document", ext : [".000"], magic : ["GeoWorks GeoWrite document"]},
		goldDiskSpreadsheet      : {name : "Gold Disk Spreadsheet", ext : [".adv", ".pcf"], magic : ["Gold Disk Office Calc/Graph spreadsheet"]},
		helmMultimediaBook       : {name : "Helm Multimedia Book", magic : ["Helm multimedia book"]},
		helpLibrarian            : {name : "Help Librarian Help File", ext : [".hlp"], magic : ["C-Worthy Help Librarian Data", /^fmt\/1790( |$)/], website : "http://fileformats.archiveteam.org/wiki/Help_Librarian"},
		homeAccounts             : {name : "Home Accounts", ext : [".ha", ".ha2"], magic : ["Home Accounts account"]},
		hotHelpCatalog           : {name : "HotHelp Catalog", ext : [".cat"], magic : ["HotHelp Catalog"]},
		hpPhoneDatabaseNote      : {name : "HP Phone/Database/Note", ext : [".gdb", ".adb", ".ndb", ".pdb"], magic : ["HP Phone/Database/Note database"], weakMagic : true},
		hyperBook                : {name : "HyperBook", magic : ["HyberBook document"]},
		hyperTextVSUM            : {name : "HyperText VSUM", ext : [".xdb"], magic : ["HyperText VSUM"]},
		ibmStoryboardStory       : {name : "IBM Storyboard Story", ext : [".sh", ".sh~"], magic : ["IBM Storyboard Story", "IBM PC Storyboard Story"]},
		ibmWorksForOS2           : {name : "IBM Works for OS/2", ext : [".lwp", ".lpw"], magic : ["IBM Works for OS/2 word processor document"]},
		iffDOCDesktopPublishing  : {name : "IFF DOC Desktop Publishing", magic : ["IFF data, DOC desktop publishing document"]},
		interBaseData            : {name : "InterBase Data", ext : [".dta"], magic : ["InterBase Data"]},
		interPress               : {name : "Xerox InterPress Document", ext : [".ip", ".ip2"], magic : ["Xerox InterPress data", "Interpress format"]},
		itsInternational         : {name : "ITS International Module", ext : [".int"], magic : ["ITS international module"]},
		kamasOutline             : {name : "KAMAS Outline", ext : [".kam"], magic : ["KAMAS Outline"]},
		locomotiveBASIC          : {name : "Locomotive BASIC", ext : [".bas"], magic : ["Amstrad CPC Locomotive BASIC tokenized source"]},
		lotusNotes               : {name : "Lotus Notes Storage Facility", ext : [".nsf", ".ntf"], magic : ["Lotus Notes Storage Facility", "Lotus Notes 4.5 Datenbank", "Lotus Note Template"]},
		lotusScreenCamScript     : {name : "Lotus ScreenCam Caption Script", ext : [".scs"], magic : ["Lotus ScreenCam Caption Script"]},
		maxonWORD                : {name : "MaxonWORD", ext : [".dok"], magic : ["MaxonWORD document"]},
		magneticPages            : {name : "Magnetic Pages Article", magic : ["Magnetic Pages article"]},
		megaDots                 : {name : "MegaDots", ext : [".meg"], magic : [/^MegaDots version /], weakMagic : true},
		messageLibrarian         : {name : "Novell/C-Worthy Message Librarian", ext : [".msg", ".dat"], magic : [/^Novell [Mm]essage [Ll]ibrarian [Dd]ata/, "C-Worthy Message Librarian Data"]},
		microHelp                : {name : "MicroHelp", ext : [".slb"], magic : ["MicroHelp Library"]},
		microsoftLesson          : {name : "Microsoft Lesson", ext : [".les", ".lsn"], magic : ["Microsoft Lesson/tutorial"]},
		newAgeHelp               : {name : "NewAge Help", ext : [".hlp"], magic : ["NewAge Help"]},
		novellDOSClientMessage   : {name : "Novell DOS Client Message", ext : [".msg"], magic : ["Novell DOS client message"]},
		novellHelpLibrarian      : {name : "Novell Help Librarian", ext : [".hlp"], magic : ["Novell Help Librarian Data"]},
		oberonDocument           : {name : "Oberon Document", ext : [".odc"], magic : ["Oberon/F Document"], idMeta : ({macFileType, macFileCreator}) => macFileType==="oODC" && macFileCreator==="obnF"},
		oberonText               : {name : "Oberon Text", ext : [".mod"], magic : ["Oberon V4 text format"], idMeta : ({macFileType, macFileCreator}) => macFileType===".Ob." && [".Ob2", ".Ob4"].includes(macFileCreator)},
		os2Message               : {name : "OS/2 Message File", ext : [".msg"], magic : [/^OS\/2 help [Mm]essage/], website : "http://fileformats.archiveteam.org/wiki/MSG_(OS/2)"},
		ovationPro               : {name : "Ovation Pro Document", ext : [".dpd"], magic : ["Ovation Pro", "OvationPro document"]},
		pageSetter               : {name : "PageSetter Document", ext : [".ps"], magic : [/^PageSetter I{0,3} ?document/]},
		palmJFileProDatabase     : {name : "Palm JFile Pro database", ext : [".pdb"], magic : ["Palm JFile Pro database", /^JFile Pro PalmOS document/]},
		palmSuperMemo            : {name : "Palm SuperMemo", ext : [".pdb"], magic : ["Palm SuperMemo", /^SuperMemo PalmOS document/]},
		palmTealMeal             : {name : "Palm TealMeal Document", ext : [".pdb"], magic : ["Palm TealMeal", "TealMeal PalmOS document"]},
		palmThoughtManager       : {name : "Palm ThoughtManager", ext : [".pdb"], magic : ["Palm ThoughtManager"]},
		papyrus                  : {name : "Papyrus", ext : [".pap"], magic : ["Papyrus document", /^fmt\/1965( |$)/]},
		pcpHelpText              : {name : "PCP Help Text", ext : [".pag"], magic : ["PCP Help Text"]},
		pcTypeDocument           : {name : "PC-Type Document", ext : [".pct"], magic : ["PC-Type document"]},
		peterNortonHelp          : {name : "Peter Norton Computing Help", ext : [".hlp"], magic : ["Peter Norton Computing Help"]},
		professionalPage         : {name : "Professional Page Document", magic : ["Professional Page document", "Professional Page page"]},
		proText                  : {name : "ProText Document", magic : ["Protext document"]},
		psion3Word               : {name : "Psion Series 3 Word Document", ext : [".wrd"], magic : ["Psion serie 3 word document"], website : "http://fileformats.archiveteam.org/wiki/Psion_Series_3_Word"},
		psionAgenda              : {name : "Psion Agenda", ext : [".agn"], magic : ["Psion S3a/3c/Siena Agenda"]},
		psionDatabase            : {name : "Psion Database", ext : [".dbf", ".odb"], magic : ["Psion serie 3 Database"]},
		psionSpreadsheet         : {name : "Psion Spreadsheet", ext : [".spr"], magic : ["Psion SH3 Spreadsheet"]},
		qAndADocument            : {name : "Q&A Document", ext : [".doc"], magic : ["Q and A Document", /^fmt\/1045( |$)/]},
		quill                    : {name : "Quill Document", ext : [".doc"], magic : ["Quill Document"], website : "http://www.rwapadventures.com/ql_wiki/index.php?title=Quill"},
		riscOSBBCBasic           : {name : "RISC OS BBC BASIC V Source", magic : ["RISC OS BBC BASIC V source"]},
		smartSoftwareDocument    : {name : "Smart Software Document", ext : [".doc"], magic : ["Smart Software Document"]},
		smartSoftwareWorksheet   : {name : "Smart Software WorkSheet", ext : [".ws"], magic : ["Smart Software WorkSheet"]},
		sprint                   : {name : "Sprint Document", ext : [".spr"], magic : ["Sprint document"], weakMagic : true},
		stFaxScript              : {name : "STFax Script", ext : [".script"], magic : ["STFax Script"]},
		stWriter                 : {name : "ST Writer Document", magic : ["ST Writer document"]},
		sundialClearlook         : {name : "Sundial Clearlook", ext : [".ctx"], magic : ["Sundial Clearlook document"]},
		superCalc                : {name : "SuperCalc Worksheet", ext : [".cal"], magic : ["SuperCalc worksheet", "SuperCalc 2/3 spreadsheet", "SuperCalc 3 spreadsheet", /^fmt\/403( |$)/, /^x-fmt\/364( |$)/]},
		symantecQADatabase       : {name : "Symantec Q&A Database File", ext : [".dtf"], magic : ["Symantec QandA Database File"]},
		tempusWord               : {name : "Tempus Word Document", ext : [".twd"], magic : ["Tempus Word Document"]},
		textEngine               : {name : "Text Engine Document", ext : [".std"], magic : ["TextEngine document (generic)", "TextEngine document (v4.0)", "TextEngine document (v5.2)"], weakMagic : ["TextEngine document (generic)"]},
		textMakerDocument        : {name : "TextMaker Document", ext : [".tmd"], magic : ["TextMaker document", "SoftMaker TextMaker template"]},
		textPlus                 : {name : "Text Plus Document", ext : [".txp"], magic : ["Text Plus document"]},
		theWorksSpreadsheet      : {name : "The Works! Spreadsheet", ext : [".sht"], magic : ["The Works! Spreadsheet"]},
		turboBASICHelp           : {name : "Turbo BASIC Help", ext : [".tbh"], magic : ["Turbo BASIC Help"]},
		twistDB                  : {name : "Twist Database file", ext : [".db"], magic : ["Twist DataBase"]},
		usefulNotesNote          : {name : "Useful Notes Note", ext : [".uno"], magic : ["Useful Notes Note"], weakMagic : true},
		vendInfoDataRecord       : {name : "VENDINFO Data Record", magic : ["VENDINFO data record"]},
		vgaPaint386Help          : {name : "VGAPaint 386 Help", ext : [".hlp"], magic : ["VGAPaint 386 Help"]},
		vipPhonebook             : {name : "V.I.P. Phonebook", ext : [".dat"], magic : ["V.I.P. phonebook data"]},
		visualXBaseForm          : {name : "Visual XBase Form", ext : [".ww"], magic : ["Visual XBase form/screen"], weakMagic : true},
		vxRexxInfo               : {name : "VX-REXX Windows/Object Info", ext : [".vry", ".vrw"], magic : ["VX-REXX windows/object info"]},
		winAsksQuestionaire      : {name : "WinAsks Questionnaire", ext : [".wap", ".wa"], magic : ["WinAsks Editor Questionnaire"]},
		windows31Registry        : {name : "Windows 3.1 Registry", magic : ["MS Windows 3.1 registry file"]},
		wingzHelp                : {name : "Wingz Help", magic : [/^Wingz [Hh]elp/], idMeta : ({macFileType, macFileCreator}) => macFileType==="WZHP" && macFileCreator==="WNGZ"},
		wingzSpreadsheet         : {name : "Wingz Spreadsheet", ext : [".wkz"], magic : ["Wingz spreadsheet"], idMeta : ({macFileType, macFileCreator}) => macFileType==="WZSS" && macFileCreator==="WNGZ"},
		winWorks                 : {name : "WinWorks Document", ext : [".wpd"], magic : ["WinWorks text Document"]},
		zincData                 : {name : "Zinc Data", ext : [".dat", ".znc", ".z_t"], magic : ["Zinc Data", "Format: Zinc Data"], website : "https://en.wikipedia.org/wiki/Zinc_Application_Framework"},
		zxSpectrumDOSBASICSource : {name : "ZX Spectrum DOS BASIC Source Code", ext : [".bas"], magic : ["ZX spectrum +3 DOS BASIC source", "Spectrum +3 data - BASIC program"]}
	},
	
	other :
	{
		actPhoneQuickList                : {name : "ACT! Phone Quick List", ext : [".pql"], magic : ["ACT! Phone Quick List"], weakMagic : true},
		agSIHelpFile                     : {name : "agSI Help File", ext : [".hlp"], magic : ["agSI Help File"]},
		amiDockConfig                    : {name : "AmiDock Configuration", ext : [".config"], magic : ["AmiDock Configuration"], weakMagic : true},
		amigaGuideIndex                  : {name : "Amigaguide Index", ext : [".index"], magic : ["Amigaguide Index"]},
		amosMenuBank                     : {name : "AMOS Menu Bank", ext : [".abk"], magic : ["AMOS Menu Bank"]},
		appleIIgsShellScript             : {name : "Apple IIgs Shell Script", idMeta : ({proDOSTypeCode}) => proDOSTypeCode==="EXE"},
		atariSTGuideHypertext            : {name : "Atari ST Guide Hypertext", ext : [".hyp"], magic : ["Atari ST Guide Hypertext document", "Atari ST Guide Hypertext"]},
		atariSTGuideREF                  : {name : "Atari ST Guide REF Links", ext : [".ref"], magic : ["Atari ST Guide ref links"]},
		averyDesignClipartIndex          : {name : "Avery Design clipart index", ext : [".zdx"], magic : ["Avery Design clipart index"], weakMagic : true},
		bbxFile                          : {name : "bbX File", magic : [/^BBx,? /]},
		borlandCProject                  : {name : "Borland C/C++ Project", ext : [".prj"], magic : ["Borland Turbo C Project", "Borland C++"]},
		borlandReflexDatabase            : {name : "Borland Reflex Database", ext : [".rxd"], magic : ["Borland Reflex Database", /^fmt\/393( |$)/]},
		borlandTurboVisionResource       : {name : "Borland Turbo Vision Resource", ext : [".res", ".tvr"], magic : ["Borland Turbo Vision Resource"]},
		briefCompiledMacro               : {name : "Brief Compiled Macro", ext : [".cm"], magic : ["Brief Compiled Macro"]},
		calendarCreatorPlus              : {name : "Calendar Creator Plus Project", ext : [".cce", ".bin"], magic : ["Calendar Creator Plus", /^x-fmt\/141( |$)/]},
		canDoVariables                   : {name : "CanDo Variables/Data", ext : [".var", ".data"], magic : ["CanDo Variables/data container"]},
		clarionTopspeed                  : {name : "Clarion Topspeed Data File", ext : [".tps"], magic : ["Clarion Topspeed Data file"]},
		compuserveInformationManager     : {name : "Compuserve Information Manager", magic : ["CompuServe Information Manager for DOS messages container", /^fmt\/1144( |$)/]},
		compuserveInformationManagerDB   : {name : "Compuserve Information Manager DB", magic : ["CompuServe Information Manager DB"]},
		compuserveInformationManagerHelp : {name : "CompuServe Information Manager Help", ext : [".hlp"], magic : ["CompuServe Information Manager for DOS Help"], weakMagic : true},
		corelPlanPerfect                 : {name : "Corel Plan Perfect", ext : [".pln"], magic : ["Corel Plan Perfect", "PlanPerfect spreadsheet"]},
		cubicPlayerModuleInfoDB          : {name : "Cubic Player Module Information Database", ext : [".dat"], magic : ["Cubic Player module information data base"]},
		cWorthyErrorLibrarian            : {name : "C-Worthy Error Librarian Data", ext : [".dat"], magic : ["C-Worthy Error Librarian Data"]},
		cWorthyForm                      : {name : "C-Worthy Form", ext : [".cwa"], magic : ["C-Worthy Form"]},
		cWorthyOverlay                   : {name : "C-Worthy Machine Overlay", ext : [".ovl"], magic : ["C-Worthy Machine Dependant Overlay"]},
		dartDesktop                      : {name : "Dart Desktop", ext : [".dsk"], magic : ["Dart Desktop"]},
		databenchData                    : {name : "Databench Data", magic : ["Databench data"]},
		davidSReadmeCompiler             : {name : "David's Readme Compiler Executable", ext : [".exe"], magic : ["16bit DOS David's Readme Compiler Executable"]},
		db2Bind                          : {name : "DB2 Bind", ext : [".bnd"], magic : ["DB2 Bind"]},
		dBaseLabelDesign                 : {name : "dBase Label Design", ext : [".lbl"], magic : ["dBASE IV Label design"]},
		dBaseQuery                       : {name : "dBase Query", ext : [".qbe"], magic : ["dBASE IV Query", "dBASE 5.0 Query"], weakMagic : true},
		dBaseUpdate                      : {name : "dBase Update", ext : [".upd"], magic : ["dBASE IV Update", "dBASE 5.0 Update"], weakMagic : true},
		deluxePrint                      : {name : "Deluxe Print Document/Project", ext : [".bnr2", ".lbl2", ".lhd2", ".sgn2", ".bnnr", ".labl", ".lthd", ".sign"], magic : ["Deluxe Print"]},
		developerStudioProject           : {name : "Microsoft Developer Studio Project", ext : [".mdp"], magic : ["Microsoft Developer Studio Project"]},
		directorSTXT                     : {name : "Director STXT", ext : [".stxt"], magic : ["Director STXT"], weakMagic : true},
		eaLocalizedStringsGameData       : {name : "EA Localized Strings game data", ext : [".loc"], magic : ["EA Localized Strings game data"]},
		frameMakerHelp                   : {name : "FrameMaker Help", ext : [".prd", ".hlp", ".api"], magic : ["FrameMaker Help"], idMeta : ({macFileType, macFileCreator}) => macFileType==="FHlp" && macFileCreator==="Fram"},
		frontRunnerBinaryModule          : {name : "FrontRunner Binary Module", ext : [".frb"], magic : ["FrontRunner Binary module"]},
		geosConvert                      : {name : "GEOS ConVerT", ext : [".cvt"], magic : ["GEOS ConVerT container format", "GEOS Convert archive"], website : "http://fileformats.archiveteam.org/wiki/GEOS_Convert"},
		gfaBASICAmiga                    : {name : "GFA-BASIC Amiga", ext : [".gfa", ".bas"], magic : ["GFA-BASIC Amiga"]},
		gfaBASICMSDOS                    : {name : "GFA-BASIC MS-DOS", ext : [".gfa", ".bas"], magic : ["GFA-BASIC MS-DOS"]},
		gfaBasicWindows                  : {name : "GFA-BASIC Windows", ext : [".gfw"], magic : ["GFA-BASIC Windows v3 tokenized source"]},
		harvardTotalProject              : {name : "Harvard Total Project Manager Project", ext : [".prj"], magic : ["Harvard Total Project Manager Project"]},
		ibmPCOverlay                     : {name : "IBM PC Overlay", ext : [".ovl"], magic : ["IBM PC Overlay"]},
		iBrowseCookies                   : {name : "iBrowse Cookies", filename : [/^cookies$/i], weakFilename : true, magic : ["IBrowse Cookies"]},
		iffCTLG                          : {name : "Amiga IFF Catalog", ext : [".catalog"], magic : ["IFF data, CTLG message catalog", "Amiga Catalog translation format"], website : "http://fileformats.archiveteam.org/wiki/IFF"},
		innoSetupLog                     : {name : "Inno Setup Log", ext : [".dat"], magic : ["Inno Setup Uninstall Log", "InnoSetup Log"]},
		innoSetupMessages                : {name : "Inno Setup Messages", ext : [".msg"], magic : ["Inno Setup Messages", "InnoSetup messages"]},
		innoSetupScript                  : {name : "Inno Setup Script", ext : [".iss", ".dbg"], magic : ["Inno Setup Script (with rem)"], weakMagic : true, website : "http://fileformats.archiveteam.org/wiki/Inno_Setup_Script"},
		installShieldPackage             : {name : "InstallShield Package", ext : [".pkg"], magic : ["InstallShield compiled setup Package", "installShield Paketdatei"]},
		integerBASICProgram              : {name : "Integer BASIC Program", idMeta : ({proDOSTypeCode}) => proDOSTypeCode==="INT"},
		jamMessageAreaHeaderFile         : {name : "JAM Message Area Header File", ext : [".jhr"], magic : ["JAM message area header file", "JAM message Header"], weakMagic : true},
		javelinCaseStudy                 : {name : "Javelin Case Study", ext : [".cas"], magic : ["Javelin Case study"]},
		lapLinkHelp                      : {name : "LapLink Help", ext : [".hlp"], magic : ["LapLink Editor Help", "LapLink Pro 4 Help"]},
		magneticHint                     : {name : "Magnetic Hint", ext : [".hnt"], magic : ["Magnetic Hint"], weakMagic : true},
		maxonMultimediaScript            : {name : "Maxon Multimedia Script", magic : ["MaxonMULTIMEDIA script"]},
		metaEditMethodDefinition         : {name : "MetaEdit Method Definition", ext : [".mof"], magic : ["MetaEdit Method definition"]},
		microsoftProjectExportedData     : {name : "Microsoft Project exported data", ext : [".mpx"], magic : ["Microsoft Project exported data", /^Microsoft Project$/, /^fmt\/342( |$)/, /^x-fmt\/243( |$)/]},
		microsoftVisualCBinaryResource   : {name : "Microsoft Visual C Binary Resource", ext : [".aps"], magic : ["Microsoft Visual C .APS file", "Visual C++ binary resource"]},
		microStationResource             : {name : "MicroStation Resource Data", ext : [".dat", ".ma"], magic : ["MicroStation Resource data", /^fmt\/1626( |$)/]},
		moneyMatters                     : {name : "Money Matters Data", ext : [".mm"], magic : ["Money Matters"]},
		msvcPCH                          : {name : "Microsoft Visual C/C++ Precompiled Header file", ext : [".pch", ".dbg"], magic : ["Microsoft Visual C .pch", "Microsoft Precompiled Header Datei", "MS Visual C++ precompiled header"]},
		msVisualFoxProApp                : {name : "MS Visual FoxPro App", ext : [".app", ".fxp"], magic : ["Generated application MS Visual FoxPro 7"]},
		msWinCEInstallHeader             : {name : "Microsoft WinCE Install Header", ext : [".000"], magic : ["Microsoft WinCE install header", "Microsoft WinCE installer"]},
		newWordMessagesOverlay           : {name : "NewWord messages Overlay", ext : [".ovr"], magic : ["NewWord messages Overlay"]},
		nortonCommanderModuleMessage     : {name : "Norton Commander module message", ext : [".msg"], magic : ["Norton Commander module message"], weakMagic : true},
		noteWorthyComposure              : {name : "NoteWorthy Composure", ext : [".nw"], magic : ["NoteWorthy song"]},
		novellErrorLibrarian             : {name : "Novell Error Librarian", ext : [".dat", ".idx"], magic : ["Novell Error Librarian Data"]},
		nsFileWrapperSerializedData      : {name : "NSFileWrapper Serialized Data", magic : ["NSFileWrapper serialized data"]},
		omnisStudioDatabase              : {name : "Omnis Studio Database", ext : [".df1", ".lbr"], magic : ["Omnis Studio Database"]},
		objectVisionDatafile             : {name : "ObjectVision Datafile", ext : [".ovd"], magic : ["ObjectVision Datafile"]},
		perFORMMessages                  : {name : "PerFORM Messages", ext : [".msg"], magic : ["PerFORM Messages"]},
		polytronVCSLogfile               : {name : "Polytron VCS logfile", ext : [".pmv"], magic : ["Polytron VCS logfile"]},
		parsonsTechnologyResourceData    : {name : "Parsons Technology resource data", ext : [".us5", ".ovl", ".cfg", ".wrk"], magic : ["Parsons Technology resource data"]},
		playStationRSD3DModelInfo        : {name : "PlayStation RSD 3D model info", ext : [".rsd"], magic : ["PlayStation RSD 3D model info"], weakMagic : true},
		powerWindowsProject              : {name : "PowerWindows Project", ext : [".pw"], magic : ["PowerWindows Project"]},
		qseqProject                      : {name : "QSEQ Project", ext : [".qsq"], magic : ["QSEQ project"]},
		quickBasicTokenizedSource        : {name : "QuickBASIC Tokenized Source", ext : [".bas"], magic : [/^Microsoft QuickBASIC \d\.\d tokenized source$/, /^QuickBASIC Extended .*Source$/]},
		quickPascalUnit                  : {name : "Microsoft QuickPascal Unit", ext : [".qpu"], magic : ["Microsoft QuickPascal Unit"]},
		reSourceControlLanguage          : {name : "ReSource Control Language", ext : [".rcl"], magic : ["ReSource Control Language"], weakMagic : true},
		rayDreamBrowserFile              : {name : "Ray Dream BRW", ext : [".brw"], magic : ["Ray Dream data"], idMeta : ({macFileType, macFileCreator}) => macFileType==="RDBW" && macFileCreator==="RD5A"},
		rmQuestModule                    : {name : "RM/Quest Module", ext : [".qrm"], magic : ["RM/Quest module"]},
		scummRoomNameList                : {name : "SCUMM room name list", ext : [".la0", ".000"], magic : ["SCUMM room name list"]},
		sixtyFourNetContainer            : {name : "64Net Container", ext : [".n64"], magic : ["64NET container"], weakMagic : true},
		softdiskCrossword                : {name : "Softdisk Crossword", ext : [".sxg", ".sxp"], magic : ["Softdisk Crossword"]},
		stormCPPDebugStrings             : {name : "Storm C++ Debug strings", ext : [".debug"], magic : ["Storm C++ Debug strings"]},
		sybaseIAnywhereIndex             : {name : "Sybase iAnywhere Index", ext : [".cdx"], magic : ["Sybase iAnywhere index files", "xBase compound index"], weakMagic : ["xBase compound index"]},
		telemateCompiledScript           : {name : "Telemate Compiled Script", ext : [".tms"], magic : ["Telemate compiled script"]},
		telixPhonebook                   : {name : "Telix Phonebook", ext : [".fbk"], magic : ["Telix Phonebook"]},
		tiCalcGroup                      : {name : "Texas Instruments Calculator Group", ext : [".89g", ".9xg", ".92g"], magic : [/^TI-.* Graphing Calculator$/], weakMagic : true},
		tiCalcList                       : {name : "Texas Instruments Calculator List", ext : [".9xl", ".89l", ".92l"], magic : [/^TI-.* Graphing Calculator \(list|real list\)$/], weakMagic : true},
		tiCalcText                       : {name : "Texas Instruments Calculator Text", ext : [".89t", ".9xt", ".92t"], magic : [/^TI-.* Graphing Calculator \(text\)$/], weakMagic : true},
		turboBASICChainModule            : {name : "Turbo Basic Chain module", ext : [".tbc"], magic : ["Turbo Basic compiled Chain module"]},
		turboCConfiguration              : {name : "Turbo C Configuration", ext : [".tc"], magic : ["Turbo C Configuration"]},
		turboCContextFile                : {name : "Turbo C Context File", ext : [".dsk"], magic : ["Turbo C Context"]},
		turboDebuggerConfig              : {name : "Turbo Debugger Configuration", ext : [".td", ".td2"], magic : ["Turbo Debugger configuration"]},
		turboPascalChainModule           : {name : "Turbo Pascal Chain module", ext : [".chn"], magic : [/^Turbo Pascal [23].0 Chain module$/]},
		turboPascalConfiguration         : {name : "Turbo Pascal Configuration File", ext : [".tp"], magic : ["Turbo Pascal configuration", "Turbo Pascal Konfigurations Datei"]},
		turboPascalCompiledCPMCOM        : {name : "Turbo Pascal Compiled 8bit CP/M-80 COM", ext : [".com"], magic : ["8bit CP/M-80 COM Turbo Pascal compiled"]},
		turboPascalDesktopFile           : {name : "Turbo Pascal Desktop File", ext : [".dsk"], magic : ["Turbo Pascal Desktop"]},
		turboPascalOverlay               : {name : "Turbo Pascal Overlay", ext : [".ovr"], magic : ["Turbo Pascal Overlay"]},
		typedStreamData                  : {name : "NeXT TypedStream Data", magic : ["NeXT typedstream serialized data", "NeXT/Apple typedstream data"]},
		venusMacro                       : {name : "Venus Macro", ext : [".mac"], magic : ["Venus Macro"]},
		venturaPublisherStyleSheet       : {name : "Ventur Publisher Style Sheet", ext : [".sty"], magic : ["Ventura Publisher Style sheet"]},
		verityCollectionIndexDescriptor  : {name : "Verity Collection Index Descriptor", ext : [".wld", ".ddd", ".did", ".pdd", ".rsd"], magic : ["Verity Collection Index Descriptor", /^fmt\/461( |$)/], weakMagic : true},
		videoArchivDataBase              : {name : "VideoArchiv Data base", ext : [".vad"], magic : ["VideoArchiv Data base"]},
		visualBasicForm                  : {name : "Visual Basic Form", ext : [".frm", ".frx"], magic : ["Visual Basic Form", "VisualBasic Form", "Microsoft Visual Basic Form", "eMbedded Visual Basic Form", /^fmt\/(1541|1542)( |$)/], website : "http://fileformats.archiveteam.org/wiki/VisualBasic_form"},
		visualBasicProject               : {name : "Visual Basic Project", ext : [".mak"], magic : ["Visual Basic project"], website : "http://fileformats.archiveteam.org/wiki/VisualBasic_project"},
		windowsHelpFileContent           : {name : "Microsoft Windows Help File Content", ext : [".cnt"], magic : ["Help File Contents", "MS Windows help file Content", /^fmt\/1656( |$)/], weakMagic : ["Help File Contents"]},
		windowsShortcut                  : {name : "Windows Shortcut", ext : [".lnk"], magic : ["Windows Shortcut", "MS Windows shortcut", "Format: Windows Shortcut", /^x-fmt\/428( |$)/, "application/x-ms-shortcut"]},
		wingzScript                      : {name : "Wingz Script", ext : [".scz"], magic : ["Wingz script", "Wingz compiled script"], idMeta : ({macFileType, macFileCreator}) => macFileType==="WZSC" && macFileCreator==="WNGZ"},
		wordSearchManiaPuzzle            : {name : "Wordsearch Mania! Puzzle", ext : [".wsp"], magic : ["Wordsearch Mania! Puzzle"]},
		wordStarMacro                    : {name : "WordStar Macro", ext : [".wsm"], magic : ["WordStar Macro"]},
		zingDirectoryInfo                : {name : "Zing! Directory Info", ext : [".zing"], magic : ["Zing! directory info"]}
	}
};
