import {TEXT_MAGIC} from "../Detection.js";

// All of the formats in this file are 'text' files that should just be handled as text
// Each entry also has the following properties added:
//	forbidExtMatch : true			(Only if ext is set AND we have magic)
//	untouched      : true
//	metaProvider   : ["text"]

export default
{
	text :
	{
		//////////
		// Game //
		//////////
		advancedGravisPhoenixConfiguration : {name : "Advanced Gravis Phoenix configuration", ext : [".phx"], magic : ["Advanced Gravis Phoenix configuration"]},
		adventureGameToolkitMessages       : {name : "Adventure Game Toolkit Messages", ext : [".msg"], magic : ["Adventure Game Toolkit Messages"], weakMagic : true},
		crosswordCreatorPuzzle             : {name : "Crossword Creator Puzzle", ext : [".puz"], magic : ["Crossword Creator Puzzle"]},
		descentMission                     : {name : "Descent Mission", ext : [".msn"], magic : ["Descent Mission"], weakMagic : true},
		doomConfiguration                  : {name : "Doom Configuration", ext : [".cfg"], magic : ["Doom Configuration"], weakMagic : true},
		doomEdASCIIMap                     : {name : "DoomEd ASCII map", ext : [".dwd"], magic : ["DoomEd ASCII map"]},
		flightSimToolkitAirplaneParameters : {name : "Flight Sim Toolkit airplane parameters", filename : [/^params$/i], weakFilename : true, magic : ["Flight Sim Toolkit airplane parameters"], weakMagic : true},
		flightSimToolkitGauges             : {name : "Flight Sim Toolkit Gauges", ext : [".fgd"], magic : ["Flight Sim Toolkit Gauges"]},
		flightSimToolkitModel              : {name : "Flight Sim Toolkit Model", ext : [".fmd"], magic : ["Flight Sim Toolkit Model"]},
		flightSimToolkitPlaces             : {name : "Flight Sim Toolkit Places", ext : [".fst"], magic : ["Flight Sim Toolkit Places"]},
		flightSimToolkitShape              : {name : "Flight Sim Toolkit Shape", ext : [".fsd"], magic : ["Flight Sim Toolkit Shape"]},
		gravisFirebirdConfiguration        : {name : "Gravis Firebird configuration", ext : [".fbd"], magic : ["Gravis Firebird configuration"]},
		indyCarRacingDriversInfo           : {name : "IndyCar Racing drivers info", ext : [".txt"], magic : ["IndyCar Racing drivers info", "IndyCar Racing II drivers info"], weakMagic : true},
		ishiFormatGoGame                   : {name : "Ishi Format Go game", ext : [".go", ".prb"], magic : ["Ishi Format Go game"]},
		plbmGamesDataBaseIndex             : {name : "PLBM Games Data Base index", ext : [".dbk"], magic : ["PLBM Games Data Base index"], weakMagic : true},
		portableDraughtsNotation           : {name : "Portable Draughts Notation", ext : [".pdn"], magic : ["Portable Draughts Notation"], weakMagic : true},
		portableGamingNotation             : {name : "Portable Gaming Notation", ext : [".pgn"], magic : ["Portable Gaming Notation"], weakMagic : true},
		rexxAdventureGameSource            : {name : "Rexx-Adventure game source", ext : [".rad"], magic : ["Rexx-Adventure game source"], weakMagic : true},
		rexxAdventureSavedGame             : {name : "Rexx-Adventure Saved game", ext : [".ras"], magic : ["Rexx-Adventure Saved game"], weakMagic : true},
		simCity3000FreshnessScore          : {name : "SimCity 3000 Freshness Score", ext : [".fsc"], magic : ["SimCity 3000 Freshness Score"], weakMagic : true},
		smartGameFormat                    : {name : "Smart Game Format", ext : [".sgf"], magic : ["Smart Game Format"], weakMagic : true},

		/////////////////////////////////////
		// Image or Poly or other 'Visual' //	Could potentially try and render/convert these into something visual in the future
		/////////////////////////////////////
		autoCADHatchPattern          : {name : "AutoCAD Hatch Pattern", ext : [".pat"], magic : [/^fmt\/1103( |$)/], weakMagic : true},
		edgeDiagrammerDiagram        : {name : "EDGE Diagrammer diagram", ext : [".edg"], magic : ["EDGE Diagrammer diagram"]},
		eeDrawDrawing                : {name : "EEDraw Drawing", ext : [".eed"], magic : ["EEDraw Drawing"], weakMagic : true},
		jascFormatPalette            : {name : "JASC format Palette", ext : [".pal"], magic : ["JASC format Palette", "PaintShop Pro color palette"]},
		gimpPalette                  : {name : "GIMP palette", magic : ["GIMP palette data", /^fmt\/1844( |$)/]},
		landscapeDesignerFractalData : {name : "Landscape Designer fractal data", magic : ["Landscape Designer fractal data"]},
		lightWaveScene               : {name : "LightWave Scene", website : "http://fileformats.archiveteam.org/wiki/LightWave_Scene", ext : [".lws", ".scn"], magic : ["LightWave 3D Scene"]},
		pageRender3DFacetObject      : {name : "PageRender3D facet/object", ext : [".facet"], magic : ["PageRender3D facet/object"]},
		qrtRayTracerSceneDescription : {name : "QRT Ray Tracer scene description", ext : [".qrt"], magic : ["QRT Ray Tracer scene description (with rem)"]},
		usgsDigitalLineGraph         : {name : "USGS Digital Line Graph", ext : [".dlg", ".dat", ".txt"], magic : ["USGS Digital Line Graph format"]},
		vicarLabelFile               : {name : "VICAR label file", ext : [".pal"], magic : ["VICAR label file", "PDS (CCSD) image data"]},
		videoFX2Effect               : {name : "VideoFX2 Effect", ext : [".vfx"], magic : ["VideoFX2 Effect"]},
		wavefrontMaterial            : {name : "Wavefront Material", website : "http://fileformats.archiveteam.org/wiki/Wavefront_MTL", ext : [".mtl"], magic : ["Alias|Wavefront material", /^fmt\/1211( |$)/]},
		wgt3DModel                   : {name : "WGT 3D model", ext : [".3d"], magic : ["WGT 3D model"]},
		windowsDesktopTheme          : {name : "Windows Desktop Theme", ext : [".theme"], magic : ["Windows 98-7 Desktop Theme", "Windows Desktop Theme"]},

		/////////////////
		// Programming //
		/////////////////
		actorLibraryDefinitionLanguage      : {name : "Actor Library Definition Language", ext : [".ldl"], magic : ["Actor Library Definition Language"], weakMagic : true},
		amigaDOSScript                      : {name : "AmigaDOS Script File", website : "https://amigasourcecodepreservation.gitlab.io/mastering-amigados-scripts/", magic : ["AmigaDOS script"]},
		amosSource                          : {name : "AMOS Source Code", ext : [".amossourcecode"]},
		amsLanguage                         : {name : "AMS Language", magic : ["AMS Language"]},
		asm                                 : {name : "Assembly Source File", website : "http://fileformats.archiveteam.org/wiki/Assembly_language", ext : [".asm"], magic : [...TEXT_MAGIC, "C source"], weakMagic : true},
		awk                                 : {name : "AWK Script", ext : [".awk"], magic : ["a /bin/awk", "Shell Skript: '/bin/awk", `Executable script, shebang: "/bin/awk`, "awk or perl script", /^(new|GNU)? ?awk script text executable/], weakMagic : ["awk or perl script"]},
		bas                                 : {name : "BASIC Source File", website : "http://fileformats.archiveteam.org/wiki/BASIC", ext : [".bas"], magic : TEXT_MAGIC, weakMagic : true},
		batDOS                              : {name : "DOS Batch File", website : "http://fileformats.archiveteam.org/wiki/Batch_file", ext : [".bat"], magic : ["DOS batch file", "BAT/CMD Batch Datei", ...TEXT_MAGIC, /^data$/], weakMagic : true},
		borlandDataBaseExplorerInformation  : {name : "Borland DataBase Explorer Information", ext : [".dbi"], magic : ["Borland DataBase Explorer Information"]},
		borlandIDEFile                      : {name : "Borland/MSVC .ide", ext : [".ide"], magic : [/^MSVC \.ide/], weakMagic : true},
		borlandLinkerMappingData            : {name : "Borland Linker Mapping Data", ext : [".map"], magic : ["Borland Linker Mapping Datei"]},
		clispByteCompiled                   : {name : "CLISP byte-compiled Lisp program", ext : [".fas"], magic : ["CLISP byte-compiled Lisp program"]},
		coldFusionComponent                 : {name : "ColdFusion Component", ext : [".cfc"], magic : ["ColdFusion Component"], weakMagic : true},
		diceCProject                        : {name : "Dice C project", ext : [".dice"], magic : ["Dice C project"], weakMagic : true},
		forthSource                         : {name : "FORTH Source", ext : [".f", ".fth", ".forth", ".4th", ".fs"], magic : ["FORTH program"], weakMagic : true},
		gnuBisonGrammar                     : {name : "GNU Bison Grammar", ext : [".yy", ".y"], magic : ["GNU Bison grammar"], weakMagic : true},
		gui4CLIScript                       : {name : "Gui4CLI script", ext : [".g", ".gc"], magic : ["Gui4CLI script"], weakMagic : true},
		jarSignaturesFile                   : {name : "JAR Signatures File", ext : [".sf"], magic : ["JAR Signatures File", "JAR Signature File"], weakMagic : true},
		javaManifest                        : {name : "Java Manifest", ext : [".mf"], magic : ["JAR Manifest", "Java Manifest"], weakMagic : true},
		javaSource                          : {name : "Java Source", ext : [".java"], magic : ["Java source", "Java Source Code"], weakMagic : true},
		js                                  : {name : "JavaScript", ext : [".js"], magic : ["JavaScript Source Code", "JavaScript source"], weakMagic : true},
		ldLinkerScript                      : {name : "LD Linker Script", ext : [".lds", ".xu", ".xn", ".xs", ".xbn", ".xr", ".x"], magic : ["LD Linker Script"]},
		lexDescription                      : {name : "Lex Description", ext : [".l", ".y"], magic : ["lex description"], weakMagic : true},
		libGuideConfiguration               : {name : "LibGuide configuration", ext : [".dvc"], magic : ["LibGuide configuration"]},
		lingoScript                         : {name : "Lingo Script", filename : [/^lingoScript$/, /^lingoScript_\d+$/], magic : TEXT_MAGIC, weakMagic : true},
		linuxMakeConfig                     : {name : "Linux make config build", filename : [/^config$/i], weakFilename : true, magic : ["Linux make config build file"], weakMagic : true},
		lisp                                : {name : "Lisp/Scheme", website : "http://fileformats.archiveteam.org/wiki/LISP", ext : [".lsp"], magic : ["Lisp/Scheme program"]},
		m4                                  : {name : "M4 Source File", website : "http://fileformats.archiveteam.org/wiki/M4", ext : [".m4"], magic : ["m4 preprocessor / macro source", "M4 macro processor script"], weakMagic : true},
		mfcClassWizardInfo                  : {name : "MFC ClassWizard info", ext : [".clw"], magic : ["MFC ClassWizard info"]},
		microsoftDeveloperStudioWorkspace   : {name : "Microsoft Developer Studio Workspace", ext : [".dsw"], magic : ["Microsoft Developer Studio Workspace"]},
		microsoftHelpCompilerProject        : {name : "Microsoft Help compiler Project", ext : [".hpj"], magic : ["Microsoft Help compiler Project"], weakMagic : true},
		microsoftObjectDescriptionLanguage  : {name : "Microsoft Object Description Language", ext : [".odl"], magic : ["Microsoft Object Description Language"], weakMagic : true},
		microsoftProgrammersWorkbenchStatus : {name : "Microsoft Programmer's Workbench Status", ext : [".sts"], magic : ["Microsoft Programmer's Workbench Status"]},
		microsoftVisualCPPWorkspace         : {name : "Microsoft Visual C++ Workspace", ext : [".vcw"], magic : ["Microsoft Visual C++ Workspace"]},
		modulaDefinition                    : {name : "Modula Definition", ext : [".def"], magic : ["Modula Definitionsdatei"]},
		modulaImplementation                : {name : "Modula Implementation", ext : [".mod"], magic : ["Modula Implementierungsdatei"]},
		msDeveloperStudioProject            : {name : "MS Developer Studio Project", ext : [".dsp"], magic : ["MS Developer Studio Project"]},
		pacificCCompilerProject             : {name : "Pacific C Compiler Project", ext : [".prj"], magic : ["Pacific C Compiler Project"], weakMagic : true},
		pas                                 : {name : "Pascal/Delphi Source File", website : "http://fileformats.archiveteam.org/wiki/Pascal", ext : [".pas", ".tp5"], magic : [...TEXT_MAGIC, "Delphi Project source", "Pascal Programm", "Pascal Source Code 'DOS'", "Pascal source"], weakMagic : true},
		perlPODDocument                     : {name : "Perl POD Document", ext : [".pm"], magic : ["Perl POD document", "Perl Packet", "Plain Old Documentation format"], weakMagic : true},
		php                                 : {name : "PHP Script", website : "http://fileformats.archiveteam.org/wiki/PHP", ext : [".php", ".phps"], magic : ["PHP source", "PHP script"], weakMagic : true},
		prologSource                        : {name : "Prolog Source", ext : [".pro"], magic : ["Prolog Source Code"], weakMagic : true},
		pythonSource                        : {name : "Python Source", ext : [".py"], magic : [/^a python script text executable$/, /^Python script/], weakMagic : true},
		redcodeSource                       : {name : "Redcode source", ext : [".red"], magic : ["Redcode source"]},
		rexx                                : {name : "OS/2 REXX Batch file", website : "https://www.tutorialspoint.com/rexx/index.htm", ext : [".rexx", ".rex"], magic : [/OS\/2 REXX batch file/, ...TEXT_MAGIC], weakMagic : true},
		rubySource                          : {name : "Ruby Source", ext : [".rb"], magic : ["Ruby script text"], weakMagic : true},
		sgml                                : {name : "SGML Document", website : "http://fileformats.archiveteam.org/wiki/SGML", ext : [".sgml"], magic : ["exported SGML document", "HyperText Markup Language"], weakMagic : true},
		stormShellProjectMakefile           : {name : "Storm Shell project/makefile", ext : [".¶", ".image"], magic : ["Storm Shell project/makefile"]},
		superKeyMacro                       : {name : "SuperKey Macro", ext : [".mac"], magic : ["SuperKey Macro"], weakMagic : true},
		starWriterKeyboardMacro             : {name : "StarWriter keyboard Macro", ext : [".mac"], magic : ["StarWriter keyboard Macro"], weakMagic : true},
		tasmInstructionsDefinitionTable     : {name : "TASM instructions definition Table", ext : [".tab"], magic : ["TASM instructions definition Table"], weakMagic : true},
		teamDeveloperSQLWindowsAppText      : {name : "Team Developer / SQLWindows application", ext : [".apt"], magic : ["Team Developer / SQLWindows application (text)"]},
		visualBasicMAKFile                  : {name : "Visual Basic MAK File", ext : [".mak"], magic : [/^fmt\/1548( |$)/]},
		visualBasicProjectGeneric           : {name : "VisualBasic Project (Generic)", ext : [".vbp"], magic : [/^VisualBasic Project \(v4\.x|EXE|generic\)/, /^fmt\/1573( |$)/], weakMagic : true},
		visualCPPWorkspaceInfo              : {name : "Visual C++ Workspace info", ext : [".wsp"], magic : ["Visual C++ Workspace info"], weakMagic : true},
		vxREXXProject                       : {name : "VX-REXX Project", ext : [".vrp"], magic : ["VX-REXX Project"]},
		watcomCProject                      : {name : "Watcom C/C++ Project", ext : [".wpj"], magic : ["Watcom C/C++ Project"], weakMagic : true},
		watcomCTarget                       : {name : "Watcom C/C++ Target", ext : [".tgt"], magic : ["Watcom C/C++ Target"], weakMagic : true},
		winFlashFlashcardSource             : {name : "WinFlash Flashcard Source", ext : [".fls"], magic : ["WinFlash Flashcard Source"]},

		///////////
		// Other //
		///////////
		autoCADPlotterConfiguration             : {name : "AutoCAD Plotter Configuration", ext : [".pcp"], magic : ["AutoCAD Plotter Configuration"], weakMagic : true},
		adobeFontList                           : {name : "Adobe Font List", ext : [".lst"], magic : [/^fmt\/526( |$)/]},
		aegisAnimatorScript                     : {name : "Aegis Animator Script", ext : [".script"], magic : ["Aegis Animator Script"]},
		aibbResultsLog                          : {name : "AIBB results log", magic : ["AIBB results log"]},
		asicProjectConfiguration                : {name : "ASIC Project/Configuration", ext : [".prj", ".cfg"], magic : ["ASIC Project/Configuration"], weakMagic : true},
		askEnvRequesterDefinition               : {name : "AskEnv Requester definition", ext : [".req"], magic : ["AskEnv Requester definition"], weakMagic : true},
		atkDataFlowDiagram                      : {name : "ATK Data Flow Diagram", ext : [".dfd"], magic : ["ATK Data Flow Diagram"]},
		audoCADMenu                             : {name : "AudoCAD Menu", ext : [".mnu"], magic : ["AudoCAD Menu"], weakMagic : true},
		autoread                                : {name : "Autoread", ext : [".ard"], magic : ["Autoread format"]},
		aWebHotlistBookmark                     : {name : "AWeb Hotlist / bookmark", ext : [".hotlist"], magic : ["AWeb Hotlist / bookmark"]},
		batMenuConfiguration                    : {name : "BatMenu configuration", ext : [".mnu"], magic : ["BatMenu configuration"]},
		berndWetzelOS2InstallData               : {name : "Bernd Wetzel OS/2 Install Data", ext : [".dat"], magic : ["Bernd Wetzel OS/2 Install Data"]},
		bibTeXStyle                             : {name : "BibTeX style", ext : [".bst"], magic : [/^BibTeX ((custom|standard) bibliography )?style text file/]},
		brikChecksums                           : {name : "Brik checksums", magic : ["Brik checksums"]},
		brutusApplicationDefinition             : {name : "Brutus Application Definition", ext : [".bad"], magic : ["Brutus Application Definition"]},
		bucketOTabTablature                     : {name : "Bucket 'o Tab tablature", ext : [".tbs", ".bot"], magic : ["Bucket 'o Tab tablature"]},
		cartoonStudioScript                     : {name : "Cartoon Studio Script", ext : [".css"], magic : ["Cartoon Studio Script"]},
		chemicalMoleculeData                    : {name : "CHEMICAL molecule Data", ext : [".dat"], magic : ["CHEMICAL molecule Data"]},
		circadData                              : {name : "CIRCAD data", ext : [".tpc", ".tsa", ".tpb", ".tsc", ".pcb", ".tpa", ".tpd", ".tda", ".tsd", ".tdc", ".tsb", ".sch", ".tdb", ".tdd"], magic : ["CIRCAD data"]},
		clarionProject                          : {name : "Clarion Project", ext : [".prj"], magic : ["Clarion Project"], weakMagic : true},
		cPBackupInfo                            : {name : "CPBackup info", ext : [".set"], magic : ["CPBackup info"]},
		cpBackupSettings                        : {name : "CPBackup Settings", ext : [".set"], magic : ["CPBackup backup Settings"], weakMagic : true},
		cuplPLDProgramFormat                    : {name : "CUPL PLD Program format", ext : [".pld"], magic : ["CUPL PLD Program format"], weakMagic : true},
		dataInterchangeFormat                   : {name : "Data Interchange Format", ext : [".dif"], magic : ["Data Interchange Format"], weakMagic : true},
		ddrescueLogfile                         : {name : "ddrescue Logfile", ext : [".bak"], magic : ["ddrescue mapfile/Logfile"]},
		debBuildControl                         : {name : "DEB build control", filename : [/^control$/i], weakFilename : true, magic : ["DEB build control"], weakMagic : true},
		decWSEOObjectFile                       : {name : "DEC-WSE Object File", ext : [".aof", ".aoff"], magic : ["DEC-WSE Object File Format"], weakMagic : true},
		dfAddressDataBase                       : {name : "DFAddress data base", ext : [".file"], magic : ["DFAddress data base"]},
		easigrafGraphParameters                 : {name : "EASIGRAF Graph Parameters", ext : [".grp"], magic : ["EASIGRAF Graph Parameters"]},
		eeDrawLibrary                           : {name : "EEDraw Library", ext : [".lib"], magic : ["EEDraw Library"], weakMagic : true},
		eisaAddOnCardConfiguration              : {name : "EISA add-on card Configuration", ext : [".cfg"], magic : ["EISA add-on card Configuration"], weakMagic : true},
		emacsRMAIL                              : {name : "Emacs RMAIL", magic : ["Emacs RMAIL"]},
		essCodeFilter                           : {name : "ESS-Code Filter", ext : [".flt"], magic : ["ESS-Code Filter"]},
		executorConfigurationFile               : {name : "Executor Configuration File", ext : [".ecf"], magic : ["Executor Configuration File"], weakMagic : true},
		explodExplosionData                     : {name : "EXPLOD explosion Data", ext : [".tra", ".dat"], magic : ["EXPLOD explosion Data"]},
		expressCalcSpreadsheet                  : {name : "ExpressCalc spreadsheet", ext : [".cal"], magic : ["ExpressCalc spreadsheet"], weakMagic : true},
		expressGraphGraph                       : {name : "ExpressGraph Graph", ext : [".grf"], magic : ["ExpressGraph Graph"]},
		fredFishProductInfo                     : {name : "Fred Fish's Product-Info", magic : ["Fred Fish's Product-Info"]},
		freePCBNetlist                          : {name : "FreePCB Netlist", ext : [".asc"], magic : ["FreePCB Netlist"]},
		gedcom                                  : {name : "GEDCOM Genealogy Text", website : "http://fileformats.archiveteam.org/wiki/GEDCOM", ext : [".ged"], magic : ["GEDCOM genealogy text", "GEDCOM Family History", "GEDCOM genealogy, ASCII text", /^fmt\/851( |$)/]},
		genBankSequenceRecord                   : {name : "GenBank sequence record", ext : [".dna"], magic : ["GenBank sequence record"]},
		graphmaticaGraph                        : {name : "Graphmatica Graph", ext : [".gr"], magic : ["Graphmatica Graph"], weakMagic : true},
		hardDiskMenuSystemMenu                  : {name : "Hard Disk Menu System menu", ext : [".999", ".000"], magic : ["Hard Disk Menu System menu"], weakMagic : true},
		hmiSoundOSConfiguration                 : {name : "HMI Sound OS Configuration", ext : [".cfg"], magic : ["HMI Sound Operating System Configuration"]},
		iafaPackageInfo                         : {name : "IAFA Package info", ext : [".pkg", ".age"], magic : ["IAFA Package info"]},
		informationPresentationFacilityMarkup   : {name : "Information Presentation Facility markup", ext : [".ipf"], magic : ["Information Presentation Facility markup"], weakMagic : true},
		installProfessionalProject              : {name : "INSTALL Professional project", ext : [".dat"], magic : ["INSTALL Professional project"]},
		installShieldResponseFile               : {name : "InstallShield Response File", ext : [".iss"], magic : ["InstallShield Response File"]},
		intelHEX                                : {name : "Intel HEX", ext : [".hex", ".hxo"], magic : ["Intel HEX data", "Intel Hexadecimal object format"]},
		kdeConfigFile                           : {name : "KDE config file", ext : [".kdelnk"], magic : ["KDE config file"]},
		keyTronicTrakballProfile                : {name : "KeyTronic Trakball profile", ext : [".pro", ".fil"], magic : ["KeyTronic Trakball profile"], weakMagic : true},
		latexAUXFile                            : {name : "Latex Auxiliary File", ext : [".aux"], magic : ["LaTeX auxiliary file", "LaTeX table of contents"], weakMagic : true},
		libtoolLibraryControlInfo               : {name : "libtool library control info", ext : [".la"], magic : ["libtool library control info", "libtool library file"], weakMagic : true},
		linuxKernelSymbolMap                    : {name : "Linux kernel symbol map", filename : [/system\.map/i], weakFilename : true, magic : ["Linux kernel symbol map, ASCII text"], weakMagic : true},
		linuxSoftwareMapEntry                   : {name : "Linux Software Map entry", ext : [".lsm"], magic : ["Linux Software Map entry"], weakMagic : true},
		lookAndFeelScreen                       : {name : "Look and Feel screen", ext : [".lnf", ".oak"], magic : ["Look and Feel screen"]},
		lotusWorksDocument                      : {name : "Lotus Works Document", ext : [".doc"], magic : ["Lotus Works Document"], weakMagic : true},
		magicianriver                           : {name : "Magician driver", ext : [".vdv", ".rdv"], magic : ["Magician vector/plotter driver", "Magician raster/printer driver"], weakMagic : true},
		magicTextFile                           : {name : "magic text file", filename : [/^magic$/i], weakFilename : true, magic : ["magic text file for file"], weakMagic : true},
		makeindexLogFile                        : {name : "Makeindex log file", ext : [".ilg"], magic : ["Makeindex log file"], weakMagic : true},
		managementInformationFormat             : {name : "DMI Management Information Format", ext : [".mif"], magic : ["DMI Management Information Format", "Management Information Format"], weakMagic : true},
		marcelPrinterDriver                     : {name : "Marcel Printer Driver", ext : [".prd"], magic : ["Marcel Printer Driver"]},
		marxMenuScript                          : {name : "MarxMenu script", ext : [".mnu", ".inc"], magic : ["MarxMenu script"], weakMagic : true},
		mealMasterFormatRecipe                  : {name : "Meal-Master Format recipe", ext : [".mmf", ".rec", ".mm"], magic : ["Meal-Master Format recipe"]},
		menubarToolbarConfig                    : {name : "Menubar toolbar config", ext : [".mbr"], magic : ["Menubar toolbar config"], weakMagic : true},
		metafontTranscript                      : {name : "METAFONT transcript", ext : [".log"], magic : ["METAFONT transcript"], weakMagic : true},
		microChannelArchitectureADL             : {name : "Micro-Channel Architecture Adapter Description Library", ext : [".adl"], magic : ["Micro-Channel Architecture Adapter Description Library"]},
		micrografxGraphData                     : {name : "Micrografx Graph data", ext : [".dat"], magic : ["Micrografx Graph data"], weakMagic : true},
		microsoftFrontPageServerExtensionConfig : {name : "Microsoft Front Page Server Extension Configuration", magic : ["FrontPage _VTI_ log/info", /^fmt\/288( |$)/]},
		microsoftMapData                        : {name : "Microsoft Map Data", ext : [".map"], magic : ["Microsoft Map Datei"], weakMagic : true},
		microsoftPRX                            : {name : "Microsoft PRX", magic : ["Windows Media stream Profile"]},
		mindReaderDictionary                    : {name : "MindReader Dictionary", ext : [".dic"], magic : ["MindReader Dictionary"], weakMagic : true},
		minerVGASpritesLibrary                  : {name : "MinerVGA sprites Library", ext : [".lbr"], magic : ["MinerVGA sprites Library"]},
		moduleDescriptionFile                   : {name : "Module Description File", website : "http://fileformats.archiveteam.org/wiki/MDZ", ext : [".mdz"], magic : ["Open Cubic Player Module Information MDZ"]},
		mosaicHotlist                           : {name : "Mosaic Hotlist", ext : [".hot"], magic : ["Mosaic Hotlist"], weakMagic : true},
		multiFaxTemplate                        : {name : "MultiFax Template", ext : [".tem"], magic : ["MultiFax Template"], weakMagic : true},
		naviPressNaviDocData                    : {name : "NaviPress NaviDoc Data", ext : [".nvd"], magic : ["NaviPress NaviDoc Data"]},
		neoBookDocument                         : {name : "NeoBook Document", ext : [".pub"], magic : ["NeoBook for DOS document"]},
		neoPaintHelp                            : {name : "NeoPaint Help", ext : [".hlp"], magic : ["NeoPaint Help"]},
		notaBenePrinterDefinition               : {name : "Nota Bene Printer definition", ext : [".prn"], magic : ["Nota Bene Printer definition"], weakMagic : true},
		novell16BitLANDriverInstallerData       : {name : "Novell 16-bit LAN driver Installer data", ext : [".ins"], magic : ["Novell 16-bit LAN driver Installer data"]},
		oleoSpreadsheet                         : {name : "Oleo spreadsheet", ext : [".oleo"], magic : ["Oleo spreadsheet"], weakMagic : true},
		os2InstallCatalogFile                   : {name : "OS/2 Install Catalog File", ext : [".icf"], magic : ["OS/2 Install Catalog File"], weakMagic : true},
		oS2InstallPackage                       : {name : "OS/2 install Package", ext : [".pkg"], magic : ["OS/2 install Package"], weakMagic : true},
		os2NetworkInformationFile               : {name : "OS/2 Network Information File", ext : [".nif"], magic : ["OS/2 Network Information File"], weakMagic : true},
		pcBoardConfigData                       : {name : "PCBoard config data", ext : [".dat"], magic : ["PCBoard config data"]},
		pcTypeMacro                             : {name : "PC-Type Macro", ext : [".mac"], magic : ["PC-Type Macro"]},
		pcTypePrinterEscapeCodes                : {name : "PC-Type Printer escape codes", ext : [".prn"], magic : ["PC-Type Printer escape codes"]},
		pdsPanel                                : {name : "PDS Panel", ext : [".pnl"], magic : ["PDS Panel"]},
		pdtStructureDefinition                  : {name : "PDT structure definition", ext : [".pdt", ".dat"], magic : ["PDT structure definition"]},
		pemCertificate                          : {name : "PEM Certificate", ext : [".cer"], magic : ["PEM certificate", "Internet Security Certificate"]},
		pemDSAPrivateKey                        : {name : "PEM DSA private key", magic : [/^PEM DSA private key/]},
		picsRatingSystem                        : {name : "PICS Rating System", ext : [".rat"], magic : ["PICS Rating System"], weakMagic : true},
		pgpPublicKey                            : {name : "PGP Public Key", website : "http://fileformats.archiveteam.org/wiki/PGP_public_key", ext : [".asc", ".aexpk", ".pgp", ".pub"], magic : ["PGP public key block", "PGP armored data, public key block"]},
		pgpMessage                              : {name : "PGP Message", website : "http://fileformats.archiveteam.org/wiki/PGP", magic : ["PGP ASCII-Armor", "PGP armored data", "PGP signature", "PGP Nachricht", /^PGP (clear text )?(signed )?message/, /^PGP armored data, (signed )?message/]},
		powerBaseDatabase                       : {name : "PowerBase database", ext : [".pb"], magic : ["PowerBase database"]},
		ppd                                     : {name : "PostScript Printer Description", website : "http://fileformats.archiveteam.org/wiki/PostScript_Printer_Description", ext : [".ppd", ".pp"], magic : ["PPD file", "PostScript Printer Description"]},
		proteinDataBank                         : {name : "Protein DataBank", ext : [".pdb"], magic : ["Protein DataBank", "Format: Protein Data Bank file", "Protein Data Bank data"], weakMagic : true},
		protelPADMacro                          : {name : "Protel PAD macro", ext : [".pad"], magic : ["Protel PAD macro"]},
		protoGenApplicationConfiguration        : {name : "ProtoGen Application configuration", ext : [".pva"], magic : ["ProtoGen Application configuration"], weakMagic : true},
		ps2MicroChannelAdapterDescription       : {name : "PS/2 MicroChannel Adapter Description", ext : [".adf"], magic : ["PS/2 MicroChannel Adapter Description File"], weakMagic : true},
		pv3DEffect                              : {name : "PV3D Effect", ext : [".eff"], magic : ["PV3D Effect"]},
		pv3DValueData                           : {name : "PV3D Value data", ext : [".val"], magic : ["PV3D Value data"], weakMagic : true},
		quickenInterchangeFormat                : {name : "Quicken Interchange Format", ext : [".qif"], magic : ["Quicken Interchange Format"], weakMagic : true},
		realNumbersTape                         : {name : "REAL Numbers Tape", ext : [".tap"], magic : ["REAL Numbers Tape"], weakMagic : true},
		reg                                     : {name : "Windows Registry Data", website : "http://fileformats.archiveteam.org/wiki/Windows_Registry", ext : [".reg", ".dat"], magic : [/^Windows Registry (Data|text)/, "Windows Registry Datei", "MS Windows 95/98/ME registry file"]},
		renderizeProject                        : {name : "Renderize Project", ext : [".bin"], magic : ["Renderize Project"]},
		rtPatchDocumentation                    : {name : "RTPatch Documentation", ext : [".rtd"], magic : ["RTPatch Documentation"]},
		samplitudePlaylist                      : {name : "Samplitude Playlist", ext : [".pl"], magic : ["Samplitude Playlist"]},
		scalaMultimediaScript                   : {name : "Scala Multimedia Script", ext : [".script"], magic : ["Scala Multimedia Script"]},
		scSpreadsheetCalculatorSpreadsheet      : {name : "sc Spreadsheet Calculator spreadsheet", ext : [".sc"], magic : ["sc Spreadsheet Calculator spreadsheet", "sc spreadsheet file"], weakMagic : true},
		sendmailM4                              : {name : "sendmail m4", ext : [".m4"], magic : ["sendmail m4 text file, ASCII text"]},
		sharewareInformationFile                : {name : "Shareware Information File", ext : [".sif"], magic : ["Shareware Information File"]},
		starcatDisksCatalogue                   : {name : "Starcat disks catalogue", ext : [".cat"], magic : ["Starcat disks catalogue"], weakMagic : true},
		stormEdSettings                         : {name : "StormEd settings", ext : [".ed"], magic : ["StormEd settings"]},
		studioPrinterDitherMethod               : {name : "Studio Printer Dither method", ext : [".dit"], magic : ["Studio Printer Dither method"]},
		svgaVESAConfiguration                   : {name : "SVGAVESA configuration", ext : [".svc"], magic : ["SVGAVESA configuration"]},
		terminateSmartnote                      : {name : "Terminate Smartnote", ext : [".not"], magic : ["Terminate Smartnote"]},
		texTranscript                           : {name : "TeX transcript", ext : [".log"], magic : ["TeX transcript"]},
		totalCommanderButtonBarConfig           : {name : "Total Commander button Bar config", ext : [".bar"], magic : ["Total Commander button Bar config"], weakMagic : true},
		tplotGraphSource                        : {name : "TPLOT graph source", ext : [".plt"], magic : ["TPLOT graph source"], weakMagic : true},
		traconSectorInfo                        : {name : "Tracon Sector info", ext : [".sec"], magic : ["Tracon Sector info"]},
		traconSimulationData                    : {name : "Tracon Simulation data", ext : [".dem", ".sim"], magic : ["Tracon Simulation data"]},
		trumpetWindsockSettings                 : {name : "Trumpet Windsock settings", ext : [".ini"], magic : ["Trumpet Windsock settings"]},
		twentyTwoDisk                           : {name : "22DISK", ext : [".def"], magic : ["22DISK format Definition"], weakMagic : true},
		twistForm                               : {name : "Twist Form", ext : [".frm", ".bak"], magic : ["Twist Form"], weakMagic : true},
		twistImportScript                       : {name : "Twist Import script", ext : [".i"], magic : ["Twist Import script"], weakMagic : true},
		twistReportScript                       : {name : "Twist Report script", ext : [".r"], magic : ["Twist Report script"], weakMagic : true},
		vendinfo                                : {name : "VENDINFO", ext : [".diz"], filename : [/^vendinfo\.diz$/i], magic : ["VENDINFO information"]},
		venturaFontMetrics                      : {name : "Ventura Font Metrics", ext : [".vfm"], magic : ["Ventura Font Metrics"], weakMagic : true},
		venturaPublisherCaption                 : {name : "Ventura Publisher Caption", ext : [".cap"], magic : ["Ventura Publisher Caption"]},
		videoFX2Script                          : {name : "VideoFX2 Script", ext : [".script"], magic : ["VideoFX2 Script"]},
		wildfireBenoitCoordinates               : {name : "Wildfire Benoit Coordinates", ext : [".coords"], magic : ["Wildfire Benoit Coordinates"], weakMagic : true},
		windowsAutorun                          : {name : "Windows Autorun File", website : "http://fileformats.archiveteam.org/wiki/INF_(Windows)", ext : [".nf"], filename : [/^autorun.inf$/i], magic : ["Microsoft Windows Autorun file", "AutoRun Info", "INF Datei [AutoRun]", /^fmt\/331( |$)/]},
		windowsSetupINFormation                 : {name : "Windows Setup INFormation", website : "http://fileformats.archiveteam.org/wiki/INF_(Windows)", magic : ["Windows setup INFormation", "Windows driver setup Information", "INF Datei [Version]", /^x-fmt\/420( |$)/]},
		windowsSetupTableFile                   : {name : "Windows Setup Table File", ext : [".stf"], magic : ["Windows Setup Table File"]},
		windowsURLShortcut                      : {name : "Windows URL shortcut", ext : [".url"], magic : ["Windows URL shortcut", "URL Datei", "MS Windows 95 Internet shortcut", /^x-fmt\/(428|454)( |$)/], weakMagic : ["Windows URL shortcut"]},
		winJackForMSWin                         : {name : "WinJack for MS Win", ext : [".bj"], magic : ["WinJack for MS Win game variant"]},
		wiseInstallerLog                        : {name : "Wise Installer log", ext : [".log"], magic : ["Wise Installer log"]},
		xantippeProject                         : {name : "Xantippe project", ext : [".xan"], magic : ["Xantippe project"]}
	}
};
