import {TEXT_MAGIC} from "../Detection.js";

// All of the formats in this file are 'text' files that should just be handled as text
// Each entry also has the following properties added:
//	forbidExtMatch : true			(Only if ext is set AND we have magic)
//	untouched      : true
//	metaProvider   : ["text"]

export default
{
	text :
	{
		adventureGameToolkitMessages          : {name : "Adventure Game Toolkit Messages", ext : [".msg"], magic : ["Adventure Game Toolkit Messages"], weakMagic : true},
		aegisAnimatorScript                   : {name : "Aegis Animator Script", ext : [".script"], magic : ["Aegis Animator Script"]},
		amigaDOSScript                        : {name : "AmigaDOS Script File", website : "https://amigasourcecodepreservation.gitlab.io/mastering-amigados-scripts/", magic : ["AmigaDOS script"]},
		amosSource                            : {name : "AMOS Source Code", ext : [".amossourcecode"]},
		askEnvRequesterDefinition             : {name : "AskEnv Requester definition", ext : [".req"], magic : ["AskEnv Requester definition"], weakMagic : true},
		asm                                   : {name : "Assembly Source File", website : "http://fileformats.archiveteam.org/wiki/Assembly_language", ext : [".asm"], magic : [...TEXT_MAGIC, "C source"], weakMagic : true},
		atkDataFlowDiagram                    : {name : "ATK Data Flow Diagram", ext : [".dfd"], magic : ["ATK Data Flow Diagram"]},
		audoCADMenu                           : {name : "AudoCAD Menu", ext : [".mnu"], magic : ["AudoCAD Menu"], weakMagic : true},
		autoCADHatchPattern                   : {name : "AutoCAD Hatch Pattern", ext : [".pat"], magic : [/^fmt\/1103( |$)/], weakMagic : true},
		autoread                              : {name : "Autoread", ext : [".ard"], magic : ["Autoread format (v2.0)"]},
		awk                                   : {name : "AWK Script", ext : [".awk"], magic : ["a /bin/awk", "Shell Skript: '/bin/awk", `Executable script, shebang: "/bin/awk`, "awk or perl script", /^(new|GNU)? ?awk script text executable/], weakMagic : ["awk or perl script"]},
		bas                                   : {name : "BASIC Source File", website : "http://fileformats.archiveteam.org/wiki/BASIC", ext : [".bas"], magic : TEXT_MAGIC, weakMagic : true},
		batDOS                                : {name : "DOS Batch File", website : "http://fileformats.archiveteam.org/wiki/Batch_file", ext : [".bat"], magic : ["DOS batch file", "BAT/CMD Batch Datei", ...TEXT_MAGIC, /^data$/], weakMagic : true},
		batMenuConfiguration                  : {name : "BatMenu configuration", ext : [".mnu"], magic : ["BatMenu configuration"]},
		borlandLinkerMappingData              : {name : "Borland Linker Mapping Data", ext : [".map"], magic : ["Borland Linker Mapping Datei"]},
		brikChecksums                         : {name : "Brik checksums", magic : ["Brik checksums"]},
		chemicalMoleculeData                  : {name : "CHEMICAL molecule Data", ext : [".dat"], magic : ["CHEMICAL molecule Data"]},
		circadData                            : {name : "CIRCAD data", ext : [".tpc", ".tsa", ".tpb", ".tsc", ".pcb", ".tpa", ".tpd", ".tda", ".tsd", ".tdc", ".tsb", ".sch", ".tdb", ".tdd"], magic : ["CIRCAD data"]},
		crosswordCreatorPuzzle                : {name : "Crossword Creator Puzzle", ext : [".puz"], magic : ["Crossword Creator Puzzle"]},
		dataInterchangeFormat                 : {name : "Data Interchange Format", ext : [".dif"], magic : ["Data Interchange Format"], weakMagic : true},
		dfAddressDataBase                     : {name : "DFAddress data base", ext : [".file"], magic : ["DFAddress data base"]},
		diceCProject                          : {name : "Dice C project", ext : [".dice"], magic : ["Dice C project (v3)"], weakMagic : true},
		easigrafGraphParameters               : {name : "EASIGRAF Graph Parameters", ext : [".grp"], magic : ["EASIGRAF Graph Parameters"]},
		eeDrawDrawing                         : {name : "EEDraw Drawing", ext : [".eed"], magic : ["EEDraw Drawing"], weakMagic : true},
		eeDrawLibrary                         : {name : "EEDraw Library", ext : [".lib"], magic : ["EEDraw Library"], weakMagic : true},
		eisaAddOnCardConfiguration            : {name : "EISA add-on card Configuration", ext : [".cfg"], magic : ["EISA add-on card Configuration"]},
		emacsRMAIL                            : {name : "Emacs RMAIL", magic : ["Emacs RMAIL"]},
		explodExplosionData                   : {name : "EXPLOD explosion Data", ext : [".tra", ".dat"], magic : ["EXPLOD explosion Data"]},
		expressCalcSpreadsheet                : {name : "ExpressCalc spreadsheet", ext : [".cal"], magic : ["ExpressCalc spreadsheet"], weakMagic : true},
		expressGraphGraph                     : {name : "ExpressGraph Graph", ext : [".grf"], magic : ["ExpressGraph Graph"]},
		forthSource                           : {name : "FORTH Source", ext : [".f", ".fth", ".forth", ".4th", ".fs"], magic : ["FORTH program"], weakMagic : true},
		fredFishProductInfo                   : {name : "Fred Fish's Product-Info", magic : ["Fred Fish's Product-Info"]},
		gedcom                                : {name : "GEDCOM Genealogy Text", website : "http://fileformats.archiveteam.org/wiki/GEDCOM", ext : [".ged"], magic : ["GEDCOM genealogy text", "GEDCOM Family History", "GEDCOM genealogy, ASCII text", /^fmt\/851( |$)/]},
		genBankSequenceRecord                 : {name : "GenBank sequence record", ext : [".dna"], magic : ["GenBank sequence record"]},
		gnuBisonGrammar                       : {name : "GNU Bison Grammar", ext : [".yy", ".y"], magic : ["GNU Bison grammar"], weakMagic : true},
		hardDiskMenuSystemMenu                : {name : "Hard Disk Menu System menu", ext : [".999", ".000"], magic : ["Hard Disk Menu System menu"], weakMagic : true},
		hmiSoundOSConfiguration               : {name : "HMI Sound OS Configuration", ext : [".cfg"], magic : ["HMI Sound Operating System Configuration"]},
		ishiFormatGoGame                      : {name : "Ishi Format Go game", ext : [".go", ".prb"], magic : ["Ishi Format Go game"]},
		javaSource                            : {name : "Java Source", ext : [".java"], magic : ["Java source", "Java Source Code"], weakMagic : true},
		js                                    : {name : "JavaScript", ext : [".js"], magic : ["JavaScript Source Code", "JavaScript source"], weakMagic : true},
		informationPresentationFacilityMarkup : {name : "Information Presentation Facility markup", ext : [".ipf"], magic : ["Information Presentation Facility markup"], weakMagic : true},
		installProfessionalProject            : {name : "INSTALL Professional project", ext : [".dat"], magic : ["INSTALL Professional project"]},
		installShieldResponseFile             : {name : "InstallShield Response File", ext : [".iss"], magic : ["InstallShield Response File"]},
		latexAUXFile                          : {name : "Latex Auxiliary File", ext : [".aux"], magic : ["LaTeX auxiliary file", "LaTeX table of contents"], weakMagic : true},
		lexDescription                        : {name : "Lex Description", ext : [".l", ".y"], magic : ["lex description"], weakMagic : true},
		lightWaveScene                        : {name : "LightWave Scene", website : "http://fileformats.archiveteam.org/wiki/LightWave_Scene", ext : [".lws", ".scn"], magic : ["LightWave 3D Scene"]},
		lingoScript                           : {name : "Lingo Script", filename : [/^lingoScript$/, /^lingoScript_\d+$/], magic : TEXT_MAGIC, weakMagic : true},
		linuxSoftwareMapEntry                 : {name : "Linux Software Map entry", ext : [".lsm"], magic : ["Linux Software Map entry"], weakMagic : true},
		lisp                                  : {name : "Lisp/Scheme", website : "http://fileformats.archiveteam.org/wiki/LISP", ext : [".lsp"], magic : ["Lisp/Scheme program"]},
		lookAndFeelScreen                     : {name : "Look and Feel screen", ext : [".lnf", ".oak"], magic : ["Look and Feel screen"]},
		m4                                    : {name : "M4 Source File", website : "http://fileformats.archiveteam.org/wiki/M4", ext : [".m4"], magic : ["m4 preprocessor / macro source", "M4 macro processor script"], weakMagic : true},
		marxMenuScript                        : {name : "MarxMenu script", ext : [".mnu", ".inc"], magic : ["MarxMenu script"], weakMagic : true},
		menubarToolbarConfig                  : {name : "Menubar toolbar config", ext : [".mbr"], magic : ["Menubar toolbar config"], weakMagic : true},
		metafontTranscript                    : {name : "METAFONT transcript", ext : [".log"], magic : ["METAFONT transcript"], weakMagic : true},
		mfcClassWizardInfo                    : {name : "MFC ClassWizard info", ext : [".clw"], magic : ["MFC ClassWizard info"]},
		microChannelArchitectureADL           : {name : "Micro-Channel Architecture Adapter Description Library", ext : [".adl"], magic : ["Micro-Channel Architecture Adapter Description Library"]},
		micrografxGraphData                   : {name : "Micrografx Graph data", ext : [".dat"], magic : ["Micrografx Graph data"], weakMagic : true},
		microsoftHelpCompilerProject          : {name : "Microsoft Help compiler Project", ext : [".hpj"], magic : ["Microsoft Help compiler Project"], weakMagic : true},
		microsoftVisualCPPWorkspace           : {name : "Microsoft Visual C++ Workspace", ext : [".vcw"], magic : ["Microsoft Visual C++ Workspace"]},
		mindReaderDictionary                  : {name : "MindReader Dictionary", ext : [".dic"], magic : ["MindReader Dictionary (v2.x)"], weakMagic : true},
		minerVGASpritesLibrary                : {name : "MinerVGA sprites Library", ext : [".lbr"], magic : ["MinerVGA sprites Library"]},
		modulaDefinition                      : {name : "Modula Definition", ext : [".def"], magic : ["Modula Definitionsdatei"]},
		modulaImplementation                  : {name : "Modula Implementation", ext : [".mod"], magic : ["Modula Implementierungsdatei"]},
		moduleDescriptionFile                 : {name : "Module Description File", website : "http://fileformats.archiveteam.org/wiki/MDZ", ext : [".mdz"], magic : ["Open Cubic Player Module Information MDZ"]},
		neoBookDocument                       : {name : "NeoBook Document", ext : [".pub"], magic : ["NeoBook for DOS document"]},
		pas                                   : {name : "Pascal/Delphi Source File", website : "http://fileformats.archiveteam.org/wiki/Pascal", ext : [".pas", ".tp5"], magic : [...TEXT_MAGIC, "Delphi Project source", "Pascal Programm", "Pascal Source Code 'DOS'", "Pascal source"], weakMagic : true},
		pcBoardConfigData                     : {name : "PCBoard config data", ext : [".dat"], magic : ["PCBoard config data"]},
		pcTypeMacro                           : {name : "PC-Type Macro", ext : [".mac"], magic : ["PC-Type Macro"]},
		pcTypePrinterEscapeCodes              : {name : "PC-Type Printer escape codes", ext : [".prn"], magic : ["PC-Type Printer escape codes"]},
		pemCertificate                        : {name : "PEM Certificate", ext : [".cer"], magic : ["PEM certificate", "Internet Security Certificate"]},
		perlPODDocument                       : {name : "Perl POD Document", ext : [".pm"], magic : ["Perl POD document"], weakMagic : true},
		pgpPublicKey                          : {name : "PGP Public Key", website : "http://fileformats.archiveteam.org/wiki/PGP_public_key", ext : [".asc", ".aexpk", ".pgp", ".pub"], magic : ["PGP public key block", "PGP armored data, public key block"]},
		pgpMessage                            : {name : "PGP Message", website : "http://fileformats.archiveteam.org/wiki/PGP", magic : ["PGP signed message", "PGP clear text signed message", "PGP ASCII-Armor", "PGP message, ASCII text", "PGP message Signature", "PGP armored data", "PGP signature", "PGP Nachricht", /^PGP message$/, /^PGP armored data, (signed )?message/]},
		php                                   : {name : "PHP Script", website : "http://fileformats.archiveteam.org/wiki/PHP", ext : [".php", ".phps"], magic : ["PHP source", "PHP script"], weakMagic : true},
		ppd                                   : {name : "PostScript Printer Description", website : "http://fileformats.archiveteam.org/wiki/PostScript_Printer_Description", ext : [".ppd", ".pp"], magic : ["PPD file", "PostScript Printer Description"]},
		prologSourceCode                      : {name : "Prolog Source Code", ext : [".pro"], magic : ["Prolog Source Code"], weakMagic : true},
		ps2MicroChannelAdapterDescription     : {name : "PS/2 MicroChannel Adapter Description", ext : [".adf"], magic : ["PS/2 MicroChannel Adapter Description File"], weakMagic : true},
		qrtRayTracerSceneDescription          : {name : "QRT Ray Tracer scene description", ext : [".qrt"], magic : ["QRT Ray Tracer scene description (with rem)"]},
		reg                                   : {name : "Windows Registry Data", website : "http://fileformats.archiveteam.org/wiki/Windows_Registry", ext : [".reg", ".dat"], magic : [/^Windows Registry (Data|text)/, "Windows Registry Datei", "MS Windows 95/98/ME registry file"]},
		rexx                                  : {name : "OS/2 REXX Batch file", website : "https://www.tutorialspoint.com/rexx/index.htm", ext : [".rexx", ".rex"], magic : [/OS\/2 REXX batch file/, ...TEXT_MAGIC], weakMagic : true},
		rubySource                            : {name : "Ruby Source", ext : [".rb"], magic : ["Ruby script text"], weakMagic : true},
		rtPatchDocumentation                  : {name : "RTPatch Documentation", ext : [".rtd"], magic : ["RTPatch Documentation"]},
		scalaMultimediaScript                 : {name : "Scala Multimedia Script", ext : [".script"], magic : ["Scala Multimedia Script"]},
		scSpreadsheetCalculatorSpreadsheet    : {name : "sc Spreadsheet Calculator spreadsheet", magic : ["sc Spreadsheet Calculator spreadsheet", "sc spreadsheet file"]},
		sgml                                  : {name : "SGML Document", website : "http://fileformats.archiveteam.org/wiki/SGML", ext : [".sgml"], magic : ["exported SGML document", "HyperText Markup Language"], weakMagic : true},
		sharewareInformationFile              : {name : "Shareware Information File", ext : [".sif"], magic : ["Shareware Information File"]},
		stormEdSettings                       : {name : "StormEd settings", ext : [".ed"], magic : ["StormEd settings"]},
		stormShellProjectMakefile             : {name : "Storm Shell project/makefile", ext : [".¶", ".image"], magic : ["Storm Shell project/makefile"]},
		superKeyMacro                         : {name : "SuperKey Macro", ext : [".mac"], magic : ["SuperKey Macro"], weakMagic : true},
		tasmInstructionsDefinitionTable       : {name : "TASM instructions definition Table", ext : [".tab"], magic : ["TASM instructions definition Table"], weakMagic : true},
		teamDeveloperSQLWindowsAppText        : {name : "Team Developer / SQLWindows application", ext : [".apt"], magic : ["Team Developer / SQLWindows application (text) (v2.0)"]},
		terminateSmartnote                    : {name : "Terminate Smartnote", ext : [".not"], magic : ["Terminate Smartnote"]},
		texTranscript                         : {name : "TeX transcript", ext : [".log"], magic : ["TeX transcript"]},
		tplotGraphSource                      : {name : "TPLOT graph source", ext : [".plt"], magic : ["TPLOT graph source"], weakMagic : true},
		traconSectorInfo                      : {name : "Tracon Sector info", ext : [".sec"], magic : ["Tracon Sector info (v2)"]},
		traconSimulationData                  : {name : "Tracon Simulation data", ext : [".dem", ".sim"], magic : ["Tracon Simulation data"]},
		trumpetWindsockSettings               : {name : "Trumpet Windsock settings", ext : [".ini"], magic : ["Trumpet Windsock settings"]},
		vendinfo                              : {name : "VENDINFO", ext : [".diz"], filename : [/^vendinfo\.diz$/i], magic : ["VENDINFO information"]},
		venturaFontMetrics                    : {name : "Ventura Font Metrics", ext : [".vfm"], magic : ["Ventura Font Metrics"], weakMagic : true},
		venturaPublisherCaption               : {name : "Ventura Publisher Caption", ext : [".cap"], magic : ["Ventura Publisher Caption"]},
		vicarLabelFile                        : {name : "VICAR label file", ext : [".pal"], magic : ["VICAR label file"]},
		videoFX2Effect                        : {name : "VideoFX2 Effect", ext : [".vfx"], magic : ["VideoFX2 Effect"]},
		videoFX2Script                        : {name : "VideoFX2 Script", ext : [".script"], magic : ["VideoFX2 Script"]},
		visualBasicMAKFile                    : {name : "Visual Basic MAK File", ext : [".mak"], magic : [/^fmt\/1548( |$)/]},
		visualCPPWorkspaceInfo                : {name : "Visual C++ Workspace info", ext : [".wsp"], magic : ["Visual C++ Workspace info"], weakMagic : true},
		wavefrontMaterial                     : {name : "Wavefront Material", website : "http://fileformats.archiveteam.org/wiki/Wavefront_MTL", ext : [".mtl"], magic : ["Alias|Wavefront material", /^fmt\/1211( |$)/]},
		windowsAutorun                        : {name : "Windows Autorun File", website : "http://fileformats.archiveteam.org/wiki/INF_(Windows)", ext : [".nf"], filename : [/^autorun.inf$/i], magic : ["Microsoft Windows Autorun file", "AutoRun Info", "INF Datei [AutoRun]", /^fmt\/331( |$)/]},
		windowsDesktopTheme                   : {name : "Windows Desktop Theme", ext : [".theme"], magic : ["Windows 98-7 Desktop Theme", "Windows Desktop Theme"]},
		windowsSetupINFormation               : {name : "Windows Setup INFormation", website : "http://fileformats.archiveteam.org/wiki/INF_(Windows)", magic : ["Windows setup INFormation", "Windows driver setup Information", "INF Datei [Version]", /^x-fmt\/420( |$)/]},
		windowsSetupTableFile                 : {name : "Windows Setup Table File", ext : [".stf"], magic : ["Windows Setup Table File"]},
		windowsURLShortcut                    : {name : "Windows URL shortcut", ext : [".url"], magic : ["Windows URL shortcut", "URL Datei", "MS Windows 95 Internet shortcut", /^x-fmt\/(428|454)( |$)/]},
		winJackForMSWin                       : {name : "WinJack for MS Win", ext : [".bj"], magic : ["WinJack for MS Win game variant (v1.x)"]},
		wiseInstallerLog                      : {name : "Wise Installer log", ext : [".log"], magic : ["Wise Installer log"]}
	}
};
