import {TEXT_MAGIC} from "../Detection.js";

// All of the formats in this file are automatically 'unsupported' and are not processed, but can still be 'identified'
// NOTE: Not ALL unsupported formats are listed here. Some are marked as 'unsupported' in the various format/family/subfiles.js
export default
{
	archive :
	{
		abackupDiskImage             : {name : "ABackup Disk Image", ext : [".adf"], magic : ["ABackup backup disk image"]},
		aixBackupRestore             : {name : "AIX backup/restore", ext : [".img"], magic : ["AIX backup/restore format file"]},
		artsAndLettersClipArtLibrary : {name : "Arts and Letters Clip Art Library", ext : [".yal"], magic : ["Arts and Letters clip art library"]},
		beOSInstallPackage           : {name : "BeOS Installation Package", ext : [".pkg"], magic : ["BeOS installation package"]},
		beOSResourceData             : {name : "BeOS Resource Data", ext : [".rsrc"], magic : ["BeOS Resource data"]},
		c16Tape                      : {name : "Commodore 16 Tape", ext : [".tap"], magic : ["C16 Tape image format"]},
		ccs64Cartridge		 	     : {name : "CCS64 Cartridge", ext : [".crt", ".car"], magic : ["C64 Cartridge image", "Commodore 64 cartridge", /^fmt\/822( |$)/]},
		coloradoMemorySystemPackage  : {name : "Colorado Memory System Package", ext : [".cmp"], magic : ["Colorado Memory System Compressed Package"]},
		ipfFloppyDiskImage           : {name : "Interchangeable Preservation Format Floppy Disk Image", ext : [".ipf"], magic : ["Interchangeable Preservation Format floppy disk image"]},
		metaCardStack                : {name : "MetaCard Stack", ext : [".rev"], magic : ["Revolution MetaCard stack"]},
		micrografxArchive            : {name : "Micrografx Archive", ext : [".mda"], magic : ["Micrografx Archive"]},
		msxCassetteTape	             : {name : "MSX Cassette Tape", ext : [".cas"], magic : ["MSX Cassette tape image", "MSX cassette archive"]},
		pgnPackArchive               : {name : "PGNPack Archive", ext : [".ppk"], magic : ["PGNPack archive"], website : "http://fileformats.archiveteam.org/wiki/PGNPack"},
		shockwaveFlashDebug          : {name : "Shockwave Flash Debug", ext : [".swd"], magic : ["Flash file with debug info"]},
		sixtyFourLANContainer		 : {name : "64LAN Container", ext : [".l64"], magic : ["64LAN container"]},
		snatchItDiskImage            : {name : "SNATCH-IT Disk Image", ext : [".cp2", ".img"], magic : ["SNATCH-IT disk image"]},
		spisTCompress                : {name : "SPIS TCompress", magic : ["SPIS TCompress archive"]},
		unrealPackage                : {name : "Unreal Package", ext : [".ut2", ".uasset"], magic : ["Unreal Package"]},
		wwarpDiskImage               : {name : "WWarp Disk Image", ext : [".wwp"], magic : ["WWarp disk image"]},
		xelaSoftArchive              : {name : "XelaSoft Archive", ext : [".xsa"], magic : ["XelaSoft Archive compressed data"]},
		zxSpectrumTZXTape            : {name : "ZX Spectrum TZX Tape", ext : [".tzx"], magic : ["Spectrum .TZX data", "ZX Spectrum Tape image", /^fmt\/1000( |$)/]}
	},

	audio :
	{
		audioWorksSoundSample      : {name : "AudioWorks Sound Sample", magic : ["AudioWorks sound sample"]},
		deluxeSoundSample          : {name : "Deluxe Sound Sample", ext : [".instr"], magic : ["Deluxe Sound sampled instrument"]},
		digitalSymphonySoundSample : {name : "Digital Symphony Sound Sample", magic : [/^Digital Symphony sound sample/]},
		dmxOP2InstrumentData       : {name : "DMS OP2 Instrument Data", magic : ["DMX OP2 instrument data"]},
		kixtartSPK                 : {name : "KixTart SPK Notation", ext : [".spk"], magic : ["KiXtart SPK notation format"]},
		kurzweilK2Sample           : {name : "Kurzweil K2 Sample", ext : [".kr1", ".kr2", ".krz"], magic : ["Kurzweil K2-serie sample"], weakMagic : true},
		performanceMusicBank       : {name : "Performance Music Bank", magic : ["Performance music bank"]},
		richMusicFormat            : {name : "Rich Music Format", ext : [".rmf"], magic : ["Rich Music Format"]}
	},

	document :
	{
		adobeInDesignDocument  : {name : "Adobe InDesign Document", ext : [".indd", ".ind"], magic : ["Adobe InDesign Document", "InDesign Document", /^fmt\/196( |$)/]},
		dBASECompiledForm      : {name : "dBASE Compiled Form", ext : [".fro", ".fmo"], magic : ["dBASE compiled Form", "dBASE compiled Format"]},
		excellenceDocument     : {name : "Excellence! Document", ext : [".doc"], magic : ["Excellence! document"]},
		interBaseDB            : {name : "InterBase/Firebird Database", ext : [".gdb", ".fdb"], magic : ["Firebird database"], notes : "In theory I could import it into a running FireBird instance and then export to CSV/SQL, but meh."},
		interSpreadSpreadsheet : {name : "InterSpread Spreadsheet", magic : ["InterSpread spreadsheet"]},
		microsoftOneNote       : {name : "Microsoft OneNote", ext : [".one"], magic : ["Microsoft OneNote", /^fmt\/673( |$)/]},
		orCADSchematic         : {name : "OrCAD Schematic", ext : [".sch", ".sht"], magic : ["OrCAD SDT schematic"]},
		penPalDatabase         : {name : "Pen Pal Database", ext : [".flr"], magic : ["Pen Pal data base"]},
		penPalDocument         : {name : "Pen Pal Document", ext : [".wtr"], magic : ["Pen Pal document"]},
		pPrintPage             : {name : "PPrint Page", ext : [".pag"], magic : ["PPrint Page"]},
		storybookWeaver		   : {name : "Storybook Weaver Story", ext : [".swd", ".sts"], magic : ["Storybook Weaver Deluxe"]},
		vizawriteDocument      : {name : "Vizawrite Document", magic : ["Vizawrite document"]},
		winFaxDocument         : {name : "WinFax Document", ext : [".fxm", ".fxr"], magic : ["WinFax Pro multipage document", "WinFax Sent / Received document"]}
	},

	executable :
	{
		aDotOutExecutable       : {name : "a.out Executable", ext : [".o"], magic : [/^a\.out .*executable/, /^a\.out NetBSD/]},
		adventureGameExecutable : {name : "Adventure Game eXecutable", ext : [".agx"], magic : ["Adventure Game eXecutable"]},
		amigaExe                : {name : "AmigaOS Executable", magic : ["AmigaOS loadseg()ble executable/binary", "Amiga Hunk executable"]},
		atariCPX                : {name : "Atari Control Panel Extension Module", ext : [".cpx"], magic : ["Atari 68xxx CPX file", "Atari Control Panel applet"], weakMagic : true},
		atariSTExe              : {name : "Atari ST Executable", magic : ["Atari ST TOS executable", "Atari ST M68K contiguous executable", "Atari ST program/executable"]},
		blackberryExecutable    : {name : "BlackBerry Executable", ext : [".cod"], magic : ["Blackberry Binary Executable"]},
		com                     : {name : "MS-DOS COM Executable", ext : [".com", ".c0m"], magic : ["DOS executable (COM", /^COM executable for (MS-)?DOS/, "16bit COM executable", "16bit DOS COM"]},
		elf                     : {name : "ELF Executable", magic : ["ELF Executable and Linkable format", /^ELF \d\d-bit [LM]SB executable/, "Executable and Linkable Format"]},
		linux8086Exe            : {name : "Linux 8086 Executable", magic : [/^Linux.*8086.*executable/]},
		linux386Exe             : {name : "Linux i386 Executable", magic : [/^Linux.*386.*executable/]},
		omagic                  : {name : "Linux OMAGIC Executable", magic : ["Linux i/386 OMAGIC executable", "Linux/i386 impure executable (OMAGIC)"]},
		macOSXUniversalBinary   : {name : "Mac OS X Universal Binary", magic : ["Mach-O universal binary", "Mac OS X Universal Binary"]},
		macOSXUniversalLibrary  : {name : "Mac OS X Universal Shared Library", ext : [".dylib"], magic : ["Mac OS X Mach-O universal Dynamically linked shared Library"]},
		macPPCPEFExe            : {name : "MacOS PPC PEF Executable", magic : ["Preferred Executable Format (PowerPC)", "header for PowerPC PEF executable"]},
		machOHPPAExe            : {name : "Mach-O HPPA Executable", magic : [/Mach-O hppa .*executable/]},
		machOIntelExe           : {name : "Mach-O Intel Executable", magic : [/Mac OS X Mach-O 32-bit Intel .*executable/]},
		machOm68kExe            : {name : "Mach-O m68k Executable", magic : [/^Mach-O m68k .*executable/, "Mach-O i386"]},
		machOPPCExe             : {name : "Mach-O PPC Executable", magic : [/^Mach-O ppc .*executable/, /^Mac OS X Mach-O 32-bit PPC .*executable/]},
		machOSPARCExe           : {name : "Mach-O SPARC Executable", magic : [/^Mach-O SPARC .*executable/]},
		microsoftCompiledHelp2  : {name : "Microsoft Compiled Help 2", ext : [".HxS", ".HxI"], magic : ["Microsoft compiled help format 2"], website : "http://fileformats.archiveteam.org/wiki/Microsoft_Help_2"},
		mipsECOFFExe            : {name : "MIPSL ECOFF Executable", magic : [/^MIPSE[LB] ECOFF executable/]},
		msDOSDriver             : {name : "MS-DOS Driver", ext : [".sys", ".drv"], magic : [/^DOS executable \(.+ device driver/], weakMagic : true},
		msxTSR                  : {name : "MSX Terminate and Stay Resident Executable", ext : [".tsr"], magic : ["MSX Software Team TSR"]},
		palmOSDynamicLibrary    : {name : "Palm OS Dynamic Library", ext : [".prc"], magic : ["Palm OS dynamic library"], weakMagic : true},
		qDOSExe                 : {name : "QDOS Executable", magic : [/QDOS executable '[\w .,_-]+'/]},
		riscOSExe               : {name : "RISC OS Executable", magic : ["RISC OS AIF executable"]},
		sparcDemandExe          : {name : "SPARC Demand Paged Exe", magic : ["SPARC demand paged dynamically linked executable not stripped"]},
		superbaseProgram        : {name : "Superbase Program", ext : [".sbp"], magic : ["Superbase Program"]},
		tiCalcProgram           : {name : "Texas Instruments Calculator Program", ext : [".73p", ".82p", ".83p", ".85p", ".86p", ".89p", ".92p"], magic : [/^TI-.* Graphing Calculator \(program\)$/]},
		xex                     : {name : "Atari Executable", ext : [".xex"], magic : ["Atari XE Executable"], weakMagic : true},
		zmagicExe               : {name : "Linux ZMAGIC Exectutable", magic : ["Linux i/386 ZMAGIC executable", "Linux/i386 demand-paged executable (ZMAGIC)"]}
	},

	font :
	{
		amigaOSOutlineFont      : {name : "AmigaOS Outline Font", ext : [".ofnt", ".font"], magic : ["AmigaOS outline font", "IFF Outline Font"]},
		amiWriteFont            : {name : "AmiWrite Font", magic : ["Ami Write printer font"]},
		averyFont               : {name : "Avery Font", ext : [".ff1"], magic : ["Avery Font"]},
		bannerManiaFont         : {name : "Banner Mania Font", ext : [".fnt"], magic : ["Bannermania font"]},
		bitmappedSignumFont     : {name : "Bitmapped Signum! Font", ext : [".p24", ".e24", ".p9", ".l30"], magic : ["Bitmapped Signum"]},
		borlandGraphicsFont     : {name : "Borland Graphics Font", ext : [".chr", ".bgi"], magic : ["Borland font BGI Stroked Font", "BGI (Borland Graphics Interface) font", "Borland font"]},
		bradfordFont            : {name : "Bradford Font", ext : [".bf2"], magic : ["Bradford Font"]},
		calamusFont             : {name : "Calamus Font", ext : [".cfn"], magic : ["Calamus Font Data"]},
		chiWriterPrinterFont    : {name : "ChiWriter Printer Font", ext : [".pft"], magic : ["ChiWriter Printer Font"]},
		chiWriterScreenFont     : {name : "ChiWriter Screen Font", ext : [".sft"], magic : ["ChiWriter Screen Font"]},
		corelWiffenFont         : {name : "Corel Wiffen Font", ext : [".wfn"], magic : ["Corel Font/Symbol"]},
		demoManiacFont          : {name : "DemoManiac Font", ext : [".font"], magic : ["DemoManiac Font"]},
		dosCodePageFont         : {name : "DOS Code Page Font", magic : ["DOS code page font data"]},
		dynaCADDVectorFont      : {name : "DynaCADD Vector Font", ext : [".fnt"], magic : ["DynaCADD vector Font"]},
		envisionPublisherFont   : {name : "Envision Publisher Font", ext : [".svf"], magic : ["EnVision Publisher DTP Font"]},
		expertDrawFont          : {name : "ExpertDraw Font", ext : [".expf"], magic : ["ExpertDraw Font"], weakMagic : true},
		frameMakerBitmappedFont : {name : "FrameMaker Font", ext : [".bfont"], magic : ["FrameMaker Font file", "FrameMaker Bitmapped screen Font"]},
		geoWorksGEOSFont        : {name : "GeoWorks GEOS Font", ext : [".fnt"], magic : ["GeoWorks GEOS font"]},
		grxFont                 : {name : "GRX Font", ext : [".fnt"], magic : ["GRX Font", "libGrx font data"]},
		japaneseWPKanjiFont     : {name : "Japanese Word Processor Kanji Font", ext : [".f00"], magic : ["Japanese Word Processor Kanji Font"]},
		laserJetSoftFont        : {name : "LaserJet Soft Font", ext : [".sfl", ".sfp", ".sft"], magic : ["LaserJet Soft Font"]},
		linkWayFont             : {name : "LinkWay Font", ext : [".fmf"], magic : ["LinkWay Font"]},
		lotusImpressFont        : {name : "Lotus Impress Font", ext : [".ifl"], magic : ["Lotus Impress Font"]},
		lotusRasterFont         : {name : "Lotus Raster Font", ext : [".lrf"], magic : ["Lotus Raster Font"]},
		lotusVectorFont         : {name : "Lotus Vector Font", ext : [".lvf"], magic : ["Lotus Vector Font"]},
		macOSFont               : {name : "MacOS Font", ext : [".fnt"], magic : ["Mac OSX datafork font, 'FONT'"]},
		matroxFont              : {name : "Matrox Font", ext : [".fnt"], magic : ["Matrox Font"]},
		maxonCADFont            : {name : "MaconCAD Font", ext : [".mcfont"], magic : ["MaxonCAD Font"]},
		msxKanjiFont            : {name : "MSX Kanji Font", magic : ["MSX Kanji Font"]},
		personalFontMakerFont   : {name : "Personal Font Maker Font/Character Set", ext : [".fnt", ".set"], magic : ["Personal Font Maker Font/character Set"]},
		printPartnerFont        : {name : "PrintPartner Font", ext : [".font"], magic : ["PrintPartner Font"]},
		psionFont               : {name : "Psion Font", ext : [".fon"], magic : ["Psion fast Font", "Psion Font"]},
		riscOSOutlineFontData   : {name : "RISC OS Outline Font Data", ext : ["outlines"], magic : ["RISC OS outline font data", "RISC OS Outline Font"], weakMagic : true},
		ripTermFont             : {name : "RIPterm Font", ext : [".fnt"], magic : ["RIPterm Font"]},
		serverNaturalFormatFont : {name : "X11 Server Natural Format font", ext : [".snf"], magic : ["X11 Server Natural Format font", "X11 SNF font data"], weakMagic : true},
		signumFont              : {name : "Signum Font", ext : [".e24"], magic : ["Bitmapped Signum!2 printer font (screen)"]},
		texPackedFont           : {name : "TeX Packed Font", ext : [".pf"], magic : [/^TeX [Pp]acked font/]},
		theDrawFont             : {name : "TheDraw Font", ext : [".tdf"], magic : ["TheDraw Fonts"], notes : "Bitmap font file used by programs like Neopaint for MSDOS and maybe GEM OS. Fontforge doesn't handle it"},
		threeDCKFont            : {name : "3D Construction Kit Font", ext : [".3fd"], magic : [/^3D Construction Kit \d? ?Font$/]},
		vgaPaint386Font         : {name : "VGAPaint 386 Font", ext : [".vfn"], magic : ["VGAPaint 386 Font"]},
		vFontFont               : {name : "VFONT Font", ext : [".fnt"], magic : ["VFONT Font"]},
		westwoodFont            : {name : "Westwood Font", ext : [".fnt"], magic : ["Westwood Font Format"]},
		wildfire3DFont          : {name : "Wildfire 3D Font", ext : [".3dfont"], magic : ["Wildfire 3D Font"]},
		wordUpToolkitFont       : {name : "WordUp Graphics Toolkit Font", ext : [".wfn"], magic : ["Wordup Graphics Toolkit Font"]},
		x11NeWSBitmapFont       : {name : "X11/NeWS Bitmap Font", ext : [".fb"], magic : ["X11/NeWS bitmap font"]},
		x11NeWSFontFamily       : {name : "X11/NeWS font family", ext : [".ff"], magic : ["X11/NeWS font family"]},
		xCADFont                : {name : "X-CAD Font", magic : ["X-CAD font"]}
	},

	image :
	{
		aldusIntelliDrawDrawing   : {name : "Aldus IntelliDraw Drawing", ext : [".idw"], magic : ["Aldus IntelliDraw Drawing"]},
		amiDrawDrawing            : {name : "AmiDraw Drawing", ext : [".sdw"], magic : ["AmiDraw Drawing"], weakMagic : true},
		animatorPICCEL            : {name : "Animator PIC/CEL", ext : [".pic", ".cel"], magic : [/^x-fmt\/223( |$)/], weakMagic : true},
		applausePalette           : {name : "Applause Palette", ext : [".pal"], magic : ["Applause Palette"]},
		artsAndLettersGraphic     : {name : "Arts and Letters Graphic", ext : [".ged"], magic : ["Arts and Letters Graphics", /^fmt\/1458( |$)/]},
		blueScanDrawing           : {name : "Blue Scan Drawing", ext : [".blsc"], magic : ["Blue Scan drawing"]},
		cadVantageDrawing         : {name : "CAD Vantage Drawing", ext : [".dwg"], magic : ["CAD Vantage drawing"]},
		calamusVectorDocument     : {name : "Calamus Vector Document", ext : [".cvd"], magic : ["Calamus Vector Document"]},
		chompstersSprite          : {name : "Chompsters Sprite", ext : [".spr"], magic : ["Chompsters Sprite"]},
		clarisDraw                : {name : "Claris Draw", ext : [".cdd"], magic : ["Claris Draw document"]},
		crayolaArtStudio          : {name : "Crayola Art Studio", ext : [".art"], magic : ["Crayola Art Studio graphic Art"], weakMagic : true},
		drafixWindowsCADDrawing	  : {name : "Drafix Windows CAD Drawing", ext : [".cad", ".slb"], magic : ["Drafix Windows CAD drawing"]},
		drawingInterchangeBinary  : {name : "Drawing Interchange Binary Format", ext : [".dxb"], magic : ["AutoCAD Drawing Exchange Binary Format", /^fmt\/54( |$)/]},
		easyCADDrawing            : {name : "EasyCAD Drawing", ext : [".fcd"], magic : ["EasyCAD drawing"]},
		freelanceGraphicsDrawing  : {name : "Freelance Graphics Drawing", ext : [".drw"], magic : ["Freelance Graphics Drawing"]},
		fxgBitmap                 : {name : "FXG Bitmap", ext : [".fxg"], magic : ["FXG bitmap"]},
		genericCADD				  : {name : "Generic CADD", ext : [".gcd"], magic : ["Generic CADD drawing"]},
		graphicWorksVectorDrawing : {name : "GraphicWorks Vector Drawing", ext : [".dvg"], magic : ["GraphicWorks Vector Drawing"]},
		intergraphRasterRGB       : {name : "Intergraph Raster RGB", ext : [".rgb"], magic : ["Intergraph Raster bitmap (Adaptive RLE RGB)"]},
		jamBitmap                 : {name : "JAM Bitmap", ext : [".jam"], magic : ["JAM bitmap"]},
		megaPaintVector           : {name : "MegaPaint Vector", ext : [".vek"], magic : ["MegaPaint Vector format"]},
		microsoftBorderArt        : {name : "Microsoft Border Art", ext : [".bdr"], magic : ["Microsoft Border art"]},
		mvpPaintAnimation         : {name : "MVP Paint Animation", ext : [".af"], magic : ["MVP Paint Animation Format"]},
		paintproBitmap            : {name : "Paintpro Bitmap", ext : [".tb1", ".ppp"], magic : ["Paintpro bitmap"]},
		playstation3Icon          : {name : "PlayStation 3 Icon", ext : [".gim"], magic : ["Playstation 3 icon"]},
		pOSWorkbenchIcon          : {name : "p.OS Workbench Icon", ext : [".info"], magic : ["p.OS-Workbench icon"]},
		printMagicGraphic         : {name : "Print Magic Graphic", ext : [".pmg"], magic : ["Print Magic Graphic"]},
		quattroProClipArt         : {name : "Quattro Pro Clip Art", ext : [".clp"], magic : ["Quattro Pro Clip art"]},
		skyRoadsBitmap            : {name : "SkyRoads Bitmap", ext : [".lzs"], magic : ["SkyRoads bitmap"], weakMagic : true},
		someraGraphicFormat       : {name : "Somera Graphic Format", ext : [".sgf"], magic : ["Somera Graphic Format"]},
		winFaxCoverPage           : {name : "WinFax CoverPage Image", ext : [".cvp", ".cv"], magic : ["WinFax CoverPage image"]}
	},

	music :
	{
		aDrumDrumkit            : {name : "ADrum Drumkit", ext : [".kit"], magic : ["ADrum drumkit"]},
		aDrumTrack              : {name : "ADrum Track", magic : ["ADrum track"]},
		cyberTracker64Chiptune  : {name : "CyberTracker 64 Chiptune", ext : [".ct"], magic : ["CyberTracker 64 chiptune"]},
		directMusicSegment      : {name : "DirectMusic Segment", magic : [/^fmt\/957( |$)/]},
		directMusicStyle        : {name : "DirectMusic Style", ext : [".sty"], magic : ["Microsoft DirectMusic Style", /^fmt\/958( |$)/]},
		encoreMusicalNotation   : {name : "Encore Musical Notation", ext : [".enc", ".mus"], magic : ["Encore Musical Notation"]},
		facSoundtrackerModule   : {name : "FAC Soundtracker Module", ext : [".mus"], magic : ["FAC Soundtracker module"]},
		finaleMusicScore        : {name : "Finale Music Score", ext : [".mus"], magic : ["Finale music score"]},
		fredEditorSoundTrack    : {name : "Fred Editor Soundtrack", magic : ["Fred Editor SoundTrack"]},
		improviseMusicData      : {name : "Improvise Music Data", ext : [".imp"], magic : ["Improvise music data"]},
		melodyMakerSong         : {name : "Melody Maker Sing", ext : [".mm"], magic : ["Melody Maker song"]},
		msxProtrackerModule     : {name : "MSX Protracker Module", ext : [".pro"], magic : ["MSX Protracker 1.0 module"]},
		koustrackerModule       : {name : "Koustracker Module", ext : [".sok"], magic : ["Koustracker module"]},
		rolandMIDIMusicRecorder : {name : "Roland MIDI Music Recorder Song", ext : [".sng"], magic : ["Roland Midi Music Recorder song"], weakMagic : true},
		scrullMusicFile         : {name : "Scrull Music File", ext : [".smf"], magic : ["Scrull Music File"]},
		technoSoundTurbo2Track  : {name : "TechnoSound Turbo 2 Track", ext : [".track"], magic : ["TechnoSound Turbo II Track"]},
		wantonPacker            : {name : "Wanton Packer", ext : [".wn"], magic : ["Wanton Packer song/module"]},
		yamahaESEQ              : {name : "Yamaha e-SEQ Music", ext : [".esq", ".fil"], magic : ["Yamaha e-SEQ music"]}
	},

	poly :
	{
		esriShape               : {name : "ESRI/ArcView Shape", ext : [".shp"], magic : ["ArcView Shape", "ESRI Shapefile", /^x-fmt\/235( |$)/], weakMagic : ["ESRI Shapefile"]},
		autoShadeRenderingSlide : {name : "AutoShade Rendering Slide", ext : [".rnd"], magic : ["AutoCAD Autoshade rendering slide"]},
		blender3D               : {name : "Blender 3D", ext : [".blend"], magic : ["Blender 3D", "Blender3D", /^fmt\/902( |$)/]},
		blitz3DObject           : {name : "Blitz3D Object", ext : [".b3d"], magic : ["Blitz3d object", /^fmt\/1182( |$)/], website : "http://fileformats.archiveteam.org/wiki/Blitz3D_Model"},
		createShade3DScene      : {name : "Create+Shade 3D Scene", ext : [".3d"], magic : ["Create+Shade 3D scene"], weakMagic : true},
		dynaCADDPart            : {name : "DynaCADD Part", ext : [".prt", ".dpt"], magic : ["DynaCADD part"]},
		electricImage3DFile     : {name : "Electric Image 3D File", ext : [".fact"], magic : ["ElectricImage 3D file"]},
		halfLifeModel           : {name : "Half Life Model", ext : [".mdl"], magic : ["Half-life Model"]},
		infiniDScene            : {name : "Infini-D Scene", ext : [".ids", ".id4"], magic : ["Infini-D Scene File"]},
		kaydaraFilmboxModel     : {name : "Kaydara Filmbox Model", ext : [".fbx"], magic : ["Kaydara FBX model", "Autodesk - Kaydara FBX 3D format", /^fmt\/1009( |$)/]},
		milkShape3DModel        : {name : "MilkShape 3D Model", ext : [".ms3d"], magic : ["MilkShape 3D model"]},
		mobile3DGraphic			: {name : "Mobile 3D Graphic", ext : [".m3g"], magic : ["Mobile 3D Graphics"], website : "http://www.j2megame.org/j2meapi/JSR_184_Mobile_3D_Graphics_API_1_1/file-format.html"},
		ogreMesh                : {name : "OGRE Mesh", ext : [".mesh"], magic : ["OGRE Mesh", /^fmt\/1188( |$)/]},
		openInventor            : {name : "SGI Open Inventor Scene Graph", ext : [".iv"], magic : ["SGI Open Inventor Scene Graph", "Open Inventor", "IRIS Inventor"]},
		quake3Model             : {name : "Quake 3 Model", ext : [".md3"], magic : ["Quake III Arena model"]},
		radCadDrawing           : {name : "Rad Cad Drawing", ext : [".cad"], magic : ["Rad Cad drawing"]},
		ravenObjectFileFormat   : {name : "Raven Object File Format", ext : [".rof"], magic : ["ROFF 3D animation"]},
		rayDreamDesignerScene   : {name : "Ray Dream Designer Scene", ext : [".rd4", ".rds"], magic : ["Ray Dream Designer scene", "Ray Dream Studio"]},
		rayDreamBRW             : {name : "Ray Dream BRW", ext : [".brw"], magic : ["Ray Dream data"]},
		renderit3DData          : {name : "Renderit3D Data", ext : [".r3d"], magic : ["Renderit3d data"]},
		shockwave3DSceneExport  : {name : "Shockwave 3D Scene Export", ext : [".w3d"], magic : ["Shockwave 3D Scene Export"]},
		simply3DGeometry		: {name : "Simply 3D Geometry", ext : [".ged"], magic : ["Simply 3D Geometry"]},
		strata3DShape           : {name : "Strata 3D Shape", ext : [".ssh"], magic : ["Strata 3D Shape"]},
		strataStudioProVis      : {name : "Strata StudioPro Vis", magic : [/^fmt\/1204( |$)/]},
		superScapeVR			: {name : "SuperScape Virtual Reality", ext : [".svr"], magic : [/^fmt\/734( |$)/]},
		threeDDGFModel          : {name : "3D Dgf Model", ext : [".dgf", ".3dgfo"], magic : ["3D Dgf model"]},
		threeDStudioLoftObject  : {name : "3D Studio Loft Object", ext : [".lft"], magic : ["3D Studio Loft Object"], weakMagic : true},
		valveModelVertices      : {name : "Valve Studio Model Vertices", ext : [".vvd"], magic : ["Valve Studio Model Vertex Data"]},
		virtusVRScene           : {name : "Virtus VR Scene", ext : [".vvr"], magic : ["Virtus VR scene"]}
	},

	video :
	{
		astoundAnimation		: {name : "Astound Animation", ext : [".awa"], magic : ["Astound Animation"]},
		completeAnimatorFilm    : {name : "The Complete Animator Film", ext : [".tca"], magic : ["The Complete Animator Film video"]},
		fujitsuMovie            : {name : "Fujitsu Movie", ext : [".mve"], magic : ["Fujitsu Movie format video"]},
		knowledgeAdventureMovie : {name : "Knowledge Adventure MoVie", ext : [".mov"], magic : ["Knowledge Adventure MoVie video"], website : "https://wiki.multimedia.cx/index.php?title=Space_Adventure_MOV"},
		ratvidVideo             : {name : "RATVID Video", ext : [".vdo"], magic : ["RATVID video"]},
		screenCamVideo          : {name : "ScreenCam Video", ext : [".scm"], magic : ["ScreenCam video"], website : "https://wiki.multimedia.cx/index.php/SCM"}
	},
	
	other :
	{
		//////////
		// Game //
		//////////
		adventureGameToolkitStrings : {name : "Adventure Game Toolkit Strings", ext : [".d$$"], magic : ["Adventure Game Toolkit temporary strings"]},
		abuseLevel                  : {name : "Abuse Level", ext : [".lvl", ".spe"], magic : ["Abuse Level"]},
		binaryDeltaCompressedPatch  : {name : "Binary Delta Compressed Patch", magic : ["Binary Delta Compressed Patch"]},
		blockBreakerPattern         : {name : "Block Breaker Pattern", ext : [".blc"], magic : ["Block Breaker pattern"]},
		callOfDutyMap               : {name : "Call of Duty Map", ext : [".d3dbsp", ".bsp"], magic : ["Call of Duty map"]},
		chessAssistant              : {name : "Chess Assistant File", ext : [".bic", ".bid", ".bim", ".bis", ".lib", ".bfi", ".dsc", ".ndx", ".bdy"], magic : ["Chess Assistant "]},
		corncob3DData               : {name : "Corncob 3D Data File", ext : [".cct"], magic : ["Corncob 3D Theater-of-operation data"]},
		createAdventureGamesProject : {name : "Create Adventure Games Project", ext : [".cag"], magic : ["Create Adventure Games project"]},
		deHackEdPatch               : {name : "DeHackEd Patch", ext : [".deh"], magic : ["DeHackEd patch"]},
		descentLevel                : {name : "Descent Level", ext : [".rdl"], magic : ["Descent Level"]},
		doomSaveGame                : {name : "DOOM Save Game", ext : [".dsg"], magic : ["Doom SaveGame"]},
		diablo1ItemSafe             : {name : "Diablo 1 Item Safe", ext : [".itm"], magic : ["Diablo 1 Item safe file format"]},
		diveFileFormat              : {name : "Dive File Format", ext : [".dff"], magic : ["Dive File Format - RenderWare"]},
		duneIISavedGame             : {name : "Dune II Saved Game", ext : [".dat"], magic : ["Dune II saved game"]},
		dynamixBitmap               : {name : "Dynamix Bitnmap", ext : [".bmp"], magic : ["Dynamix Bitmap data container"]},
		electronicArtsLibContainer  : {name : "Electronic Arts LIB container", ext : [".lib"], magic : ["Electronic Arts LIB container"]},
		esriCoverageAnnotation      : {name : "ESRI ArcInfo Coverage Annotation", magic : [/^fmt\/1591( |$)/]},
		esriDataBaseIndex           : {name : "ESRI/ArcView DataBase Index", ext : [".shx"], magic : ["ArcView DataBase Index", "ESRI Shapefile", /^fmt\/277( |$)/], weakMagic : true},
		esriGridNIT                 : {name : "ESRI ArcInfo Grid NIT", ext : [".nit"], magic : [/^fmt\/1596( |$)/]},
		esriSpatialIndex            : {name : "ESRI Spatial Index",  magic : [/^fmt\/319( |$)/]},
		f1gpEdData                  : {name : "F1GP-Ed Data", ext : [".events", ".settings"], magic : ["F1GP-Ed"], weakMagic : true},
		flashbackObject             : {name : "Flashback Object", ext : [".obj"], magic : ["Flashback Object"]},
		flightSimToolkitTerrain     : {name : "Flight Sim Toolkit Terrain Data", ext : [".ftd"], magic : ["Flight Sim Toolkit Terrain Data"]},
		fullTiltPinballData         : {name : "Full Tilt Pinball Data", ext : [".dat"], magic : ["Full Tilt! Pinball table data"]},
		halfLife2SaveGame           : {name : "Half-Life 2 Save Game", ext : [".sav"], magic : ["Half-Life 2 savegame"]},
		homeBrewLevel               : {name : "HomeBrew Level", ext : [".hle"], magic : ["HomeBrew Level"]},
		homeBrewPalette             : {name : "HomeBrew Palette", ext : [".hpa"], magic : ["HomeBrew Palette"]},
		homeBrewTile                : {name : "HomeBrew Tile", ext : [".hti"], magic : ["HomeBrew Tile"]},
		infinityEngineFile          : {name : "Infinity Engine File", ext : [".dlg", ".cre", ".itm", ".are", ".tlk", ".spl", ".sto"], magic : ["Infinity Engine "]},
		jazzJackrabbitFile          : {name : "Jazz Jackrabbit File", ext : [".0sc", ".0fn"], magic : ["Jazz Jackrabbit font/cutscene", "Jazz Jackrabbit map"]},
		kolekoSaveState             : {name : "KOLEKO Save State", ext : [".rom"], magic : ["KOLEKO Save state"]},
		legendOfKyrandiaEMCFile     : {name : "Legend of Kyrandia EMC File", ext : [".emc"], magic : ["Kyra Engine game data"]},
		lucasFilmData               : {name : "LucasFilm Data", ext : [".lfd"], magic : ["LucasFilm Data", "Lucas Film Data - Panel"]},
		megaZeuxBoard               : {name : "MegaZeux Board", ext : [".mzb"], magic : ["MegaZeux Board"], weakMagic : true},
		megaZeuxSave                : {name : "MegaZeux Save", ext : [".sav"], magic : ["MegaZeux Save"], weakMagic : true},
		megaZeuxWorld               : {name : "MegaZeux World", ext : [".mzx"], magic : ["MegaZeux World"], weakMagic : true},
		midiMazeIIMaze              : {name : "MIDI-MAZE II Maze", ext : [".mze"], magic : ["MIDI-MAZE II Maze"]},
		moonbaseGameData            : {name : "Moonbase Game Data", ext : [".mb"], magic : ["Moonbase game data"]},
		portsOfCallSaveGame         : {name : "Ports of Call Save Game", ext : [".trp"], magic : ["Ports of Call savegame"]},
		prsFormatResourceData       : {name : "PRS Format Resource Data", ext : [".prs"], magic : ["PRS Format Resource data"]},
		puzzleBusterPuzzle          : {name : "Puzzle Buster Puzzle", ext : [".puz"], magic : ["Puzzle Buster Puzzle"]},
		quakeMap                    : {name : "Quake Map", ext : [".bsp"], magic : ["Quake Map"]},
		quake2Map                   : {name : "Quake II Map", ext : [".bsp"], magic : ["Quake2 map", "Quake II Map file"]},
		quake2SpriteReference       : {name : "Quake II Sprite Reference", ext : [".sp2"], magic : ["Quake II SP2 sprite file"]},
		quake3Map                   : {name : "Quake III Map", ext : [".bsp"], magic : ["Quake III Map file"]},
		raptorGLBEncryptedContainer : {name : "Raptor GLB Encrypted Container", ext : [".glb"], magic : ["Raptor GLB encrypted container"]},
		ravenSoftCompiledScript     : {name : "Raven Software Compiled Script", ext : [".ibi"], magic : ["Raven Software compiled script"]},
		riseOfTheTriadLevel         : {name : "Rise of the Triad Level", ext : [".rtc", ".rtl"], magic : ["Rise of the Triad level"]},
		rpgMakerMap                 : {name : "RPG Maker Map", ext : [".lmu"], magic : ["RPG Maker 2000/2003 Map"], notes : "EasyRPG-Tools has lmu2png but requires lots of aux files and I couldn't get it to work"},
		scorchedEarthMountainData   : {name : "Scorched Earth Mountain Data", ext : [".mtn"], magic : ["Scorched Earth Mountain range data"]},
		scummMainData               : {name : "SCUMM main data container", magic : ["SCUMM main data container"]},
		settlers2Map				: {name : "Settlers II Map", ext : [".swd", ".wld"], magic : ["Settlers II map"]},
		simCity2000SaveGameData     : {name : "SimCity 2000 Save Game Data", ext : [".sc", ".sc2"], magic : ["SimCity 2000 save game/map data"]},
		simCityCity                 : {name : "SimCity City", ext : [".cty"], magic : ["SimCity City"]},
		skunnyKartGameData          : {name : "Skunny Kart Library Game Data", ext : [".lid"], magic : ["Skunny Kart Library game data"]},
		slicksNSlidesTrack          : {name : "Slicks 'n' Slide Track", ext : [".ss"], magic : ["Slicks 'n' Slide track data"]},
		starCraftMap                : {name : "StarCraft Map", ext : [".scm", ".scx"], magic : ["StarCraft Map"]},
		starCraftReplay             : {name : "StarCraft Replay", ext : [".rep"], magic : ["Starcraft Replay"]},
		su27FlankerMission          : {name : "Su-27 Flanker Mission", ext : [".mis"], magic : ["Su-27 Flanker Mission"]},
		superZZTFile                : {name : "Super ZZT File", ext : [".szt"], magic : ["Super ZZT Game Creation System data format"], weakMagic : true},
		tads                        : {name : "TADS", ext : [".t", ".gam"], magic : ["TADS 2 Game", /^TADS .*game data$/]},
		threeDCKArea                : {name : "3D Construction Kit Area", ext : [".3ad"], magic : [/^3D Construction Kit \d? ?Area$/]},
		threeDCKBrushes             : {name : "3D Construction Kit Brushes", ext : [".3bd"], magic : ["3D Construction Kit Brushes data"]},
		threeDCKObject              : {name : "3D Construction Kit Object", ext : [".3od", ".obj"], magic : ["3D Construction Kit Object", /^3D Construction Kit (\d? ?)Object$/]},
		threeDCKShapeData           : {name : "3D Construction Kit Shape Data", ext : [".3sd"], magic : ["3D Construction Kit Shape data", /^3D Construction Kit \d? ?Shape data$/]},
		threeDCKWorldData           : {name : "3D Construction Kit World Data", ext : [".kwd", ".kit"], magic : ["3D Construction Kit World data", /^3D Construction Kit \d? ?World [Dd]ata/]},
		valveSourceMap			    : {name : "Valve Source Map", ext : [".bsp"], magic : ["Valve Source BSP format", "Valve Source map"]},
		warCraftMap                 : {name : "WarCraft Map", ext : [".pud"], magic : ["WarCraft map"]},
		warCraft3Map                : {name : "WarCraft III Map", ext : [".w3m"], magic : ["WarCraft III map", "Warcraft III map"]},
		warCraft3RecordedGame       : {name : "WarCraft III Recorded Game", ext : [".w3g"], magic : ["WarCraft III Recorded Game", "Warcraft III recorded game"]},
		winzlePuzzle                : {name : "Winzle Puzzle", ext : [".wzl"], magic : ["Winzle puzzle"]},
		wipeout2097TrackData        : {name : "Wipeout 2097 Track Data", ext : [".wad"], magic : ["Wipeout 2097 track data"]},
		zsnesSaveSate               : {name : "ZSNES Save State", ext : [".zst"], magic : ["ZSNES Save State"]},


		/////////////////
		// Programming //
		/////////////////
		actorImageSnapshot           : {name : "Actor Image Snapshot", ext : [".ima"], magic : ["Actor Image snapshot"], weakMagic : true},
		aegisImpactSlideshow         : {name : "Aegis Impact! Slideshow", ext : [".sld"], magic : ["Aegis Impact! Slideshow"]},
		alphaFourScript              : {name : "Alpha Four Script", ext : [".scp"], magic : ["Alpha Four Script"]},
		amigaBASICProtectedFile      : {name : "Amiga BASIC Protected File", ext : [".bas"], magic : ["AmigaBASIC source (protected)"]},
		amigaEModule                 : {name : "Amiga E Module", ext : [".m"], magic : ["Amiga E module", "E module/library"]},
		amigaLibrary                 : {name : "Amiga Hunk Library/Object", ext : [".lib", ".obj", ".o"], magic : ["AmigaOS object/library data", "Amiga Hunk library/object code"]},
		amigaSharedLibrary           : {name : "Amiga Shared Library", ext : [".lib"], magic : ["AmigaOS shared library"]},
		appleScriptCompiled          : {name : "Compiled AppleScript Script", magic : ["AppleScript compiled", "Compiled AppleScript script"]},
		atariGEMOBM                  : {name : "Atari GEM OBM File", ext : [".obm"], magic : ["Atari GEM OBM File"]},
		autoCADProtectedLISP         : {name : "AutoCAD Protected LISP", ext : [".lsp"], magic : ["AutoCAD Protected LISP Code"]},
		beOSCodeWarriorProject       : {name : "BeOS CodeWarrior Project", ext : [".proj"], magic : ["BeOS CodeWarrior Project"]},
		bnuportPatchTable            : {name : "BNUPORT Patch Table", ext : [".pat"], magic : ["BNUPORT Patch Table"]},
		borlandDelphiCompiledUnit    : {name : "Borland Delphi Compiled Unit", ext : [".dcu"], magic : ["Borland Delphi .DCU file", "Borland Delphi 6 Library", /^Delphi \d+ Compiled Unit/]},
		borlandLanguageLibrary       : {name : "Borland Language Library", ext : [".bll"], magic : ["Borland Language Library"]},
		borlandOverlay               : {name : "Borland Overlay", ext : [".ovr"], magic : ["Borland Overlay"]},
		clipperPreLinkedLibrary      : {name : "Clipper Pre-Linked Library", ext : [".pll"], magic : ["Clipper Pre-Linked Library"]},
		codeWarriorProject           : {name : "CodeWarrior Project", ext : [".mcp"], magic : ["CodeWarrior Project"]},
		coffLibrary                  : {name : "COFF Library", ext : [".lib", ".obj", ".a"], magic : ["Common Object File Format (COFF) Library"]},
		coolPageProject 			 : {name : "Cool Page Project", ext : [".cpg"], magic : ["Cool Page Project"]},
		creativeSignalMicrocode      : {name : "Creative Signal Processor Microcode", ext : [".csp"], magic : ["Creative Signal Processor microcode"]},
		cornelHuthComprssedLibrary   : {name : "Cornel Huth Compressed Library", ext : [".li_"], magic : ["Cornel Huth compressed library"]},
		emacsCompiledLisp            : {name : "Emacs Compiled Lisp", ext : [".elc"], magic : [/^Emacs.*byte-compiled Lisp data$/], notes : "Could decompile it with: https://github.com/rocky/elisp-decompile"},
		gwBasicProtectedSource       : {name : "GW-BASIC Protected Source", ext : [".bas"], magic : ["GW-BASIC protected source"], weakMagic : true},
		highSpeedPascalUnit          : {name : "High Speed Pascal Unit", ext : [".unit"], magic : ["High Speed Pascal compiled Unit"]},
		iffSDBG                      : {name : "Amiga IFF Debug File", ext : [".debug"], magic : ["IFF SDBG file"]},
		installShieldUninstallScript : {name : "InstallShield Uninstall Script", ext : [".isu"], magic : ["InstallShield Uninstall Script"]},
		intellCOFFObject             : {name : "Intel Common Object File Format Object", ext : [".obj"], magic : [/^Intel .*Common Object File Format (COFF) object/, /^Intel .*COFF object file/]},
		javaClass                    : {name : "Java Class File", ext : [".class"], magic : ["Java Compiled Object Code", "compiled Java class data", "Java bytecode", /^x-fmt\/415( |$)/]},
		kickPascalUnitInterface      : {name : "KICK-Pascal Unit Interface", ext : [".u"], magic : ["KICK-Pascal Unit Interface"]},
		linux8086ObjectFile          : {name : "Linux 8086 Object File", ext : [".o"], magic : ["Linux-8086 object file"]},
		linuxi386ObjectFile          : {name : "Linux i386 Object File", ext : [".o"], magic : ["Linux/i386 object file"]},
		luaBytecode                  : {name : "Lua bytecode", magic : ["Lua bytecode"]},
		machOObject                  : {name : "Mach-O Object", ext : [".o"], magic : [/^Mach-O object$/], weakMagic : true},
		machOM68kObject              : {name : "Mach-O m68k Object", ext : [".o"], magic : [/^Mach-O m68k .*object/]},
		machOHPPAObject              : {name : "Mach-O HPPA Object", ext : [".o"], magic : [/^Mach-O hppa .*object/]},
		machOSparcObject             : {name : "Mach-O SPARC Object", ext : [".o"], magic : [/^Mach-O SPARC .*object/]},
		mapleCommonBinary            : {name : "Maple Common Binary", ext : [".m"], magic : ["Maple Common Binary"]},
		mdiffPatchFile               : {name : "MDIFF Patch File", ext : [".mdf"], magic : ["MDIFF patch"]},
		microsoftDebug               : {name : "Microsoft Separate Debug Format", ext : [".dbg"], magic : ["Microsoft separate Debug format"]},
		microsoftDirectInputFFE      : {name : "Microsoft DirectInput Force Feedback Effect", ext : [".ffe"], magic : ["Microsoft DirectInput Force Feedback Effect"]},
		microsoftDierctMusicSegments : {name : "Microsoft DirectMusic Segments Type", ext : [".sgt"], magic : ["Microsoft DirectMusic Segments Type"]},
		microsoftIncrementalLinker   : {name : "Microsoft Incremental Linker Data", ext : [".ilk"], magic : ["Microsoft Incremental Linker data"]},
		microsoftVisualCFiles        : {name : "Microsoft Visual C Files", ext : [".bsc", ".sbr", ".wsp"], magic : ["MSVC .bsc", "MSVC .sbr", "MSVC .wsp"]},
		mySQLIndexFile               : {name : "MySQL Index", ext : [".myi"], magic : ["MySQL MyISAM index file", "MySQL MyISAM tables index", /^fmt\/1197( |$)/]},
		mySQLTableDefinition         : {name : "MySQL Table Definition", ext : [".frm"], magic : ["MySQL table definition", /^MySQL Database.* Dictionary/, /^fmt\/868( |$)/]},
		netwareLoadableModule        : {name : "Netware Loadable Module", ext : [".nlm"], magic : [/^Net[Ww]are Loadable Module/]},
		oberonSymbol                 : {name : "Oberon Symbol", ext : [".sym"], magic : ["Oberon V3 Symbol data", "Oberon/F Symbol File"]},
		olbLib                       : {name : "OLB Library", magic : ["OLB Library"]},
		powerBasicHelp               : {name : "PowerBASIC Help", ext : [".pbh"], magic : ["PowerBASIC Help"]},
		powerBuilderDynamicLibrary   : {name : "PowerBuilder Dynamic Library", ext : [".pbd"], magic : ["PowerBuilder Dynamic library"]},
		psionLibrary                 : {name : "Psion Library", ext : [".dyl"], magic : ["Psion Library"]},
		qtMessage                    : {name : "Qt Message", ext : [".qm"], magic : ["Qt Message", "Qt Translation file"]},
		realBasicProject             : {name : "RealBasic Project", ext : [".rbp"], magic : ["REALbasic/Xojo Project"]},
		riscOSALFLibrary             : {name : "RISC OS ALF Library", magic : ["RISC OS Chunk data, ALF library"]},
		riscOSARMObjectFile          : {name : "RISC OS ARM Object File", magic : ["RISC OS Chunk data, AOF object"]},
		sgmlCompiled                 : {name : "SGML Compiled", ext : [".mtl"], magic : ["Compiled SGML rules"]},
		sqlite2Database              : {name : "SQLite2 Database", ext : [".sqlite", ".sqlite2", ".db"], magic : ["SQLite 2.x database", /^fmt\/1135( |$)/]},
		telixCompiledScript          : {name : "Telix Compiled Script", ext : [".slc"], magic : ["Telix Compiled Script"]},
		turboLightningEnvironment    : {name : "Turbo Lightning Environment", ext : [".env"], magic : ["Turbo Lightning Environment"]},
		turboModula2SymbolData       : {name : "Turbo Modula-2 Symbol Data", ext : [".sym"], magic : ["Turbo Modula-2 Symbol data"]},
		turboPascalHelp              : {name : "Turbo Pascal Help", ext : [".hlp"], magic : ["Turbo Pascal Help"]},
		visualBasicExtension         : {name : "Visual Basic Extension", ext : [".vbx"], magic : ["Visual Basic eXtension/Custom Control"]},
		visualBasicTokenizedSource   : {name : "Visual Basic Tokenized Source", ext : [".bas"], magic : [/^Visual Basic \d source \(tokenized\)$/]},
		visualCLibrary               : {name : "Microsoft Visual C Library", ext : [".lib"], magic : ["Microsoft Visual C Library", "Microsoft Visual C/OMF library"]},
		visualSmalltalkLibrary       : {name : "Visual Smalltalk Enterprise Objects Library", ext : [".sll"], magic : ["Visual Smalltalk Enterprise objects Library"]},
		visualSourceSafeControlFile  : {name : "Visual SourceSafe Control File", ext : [".scc"], magic : [/^Visual SourceSafe control file \(var [12]\)$/, "Visual SourceSafe control file (var 3)"], weakMagic : ["Visual SourceSafe control file (var 3)"]},
		xpcomTypeLibrary			 : {name : "XPCOM Type Library", ext : [".xpt"], magic : ["XPCOM Type Library", "XPConnect Typelib"]},


		/////////////
		// Drivers //
		/////////////
		ailMidiDriver                 : {name : "Audio Interface Library 3 Music/MIDI driver", ext : [".mdi"], magic : ["Audio Interface Library 3 Music/MIDI driver"]},
		ailDigitalAudioDriver         : {name : "Audio Interface Library 3 Digital audio driver", ext : [".dig"], magic : ["Audio Interface Library 3 Digital audio driver"]},
		allwaysPrinterDriver          : {name : "Allways Printer Driver", ext : [".apc", ".apd", ".apf"], magic : ["Allways Printer driver"]},
		autoCADDOSRealModeADIDriver   : {name : "Autocad DOS Real Mode ADI Driver", ext : [".exp", ".ex%"], magic : ["Autocad DOS real mode ADI driver"]},
		borlandDriver                 : {name : "Borland Graphics Interface Driver", ext : [".bgi"], magic : ["Borland Graphics Interface driver", "Borland device BGI Device Driver", "Borland Graphics printer driver"]},
		bwsbMusicSoundDriver          : {name : "BWSB Music and Sound Engine Driver", ext : [".mse"], magic : ["BWSB Music and Sound Engine driver"]},
		creativeGraphicsLibraryDriver : {name : "Creative Graphics Library Driver", ext : [".cgl"], magic : ["Creative Graphics Library driver"]},
		geePrinterDriver              : {name : "Gee! Printer Driver", ext : [".pdr"], magic : ["Gee! Printer Driver"]},
		humanMachineInterfacesDriver  : {name : "Human Machine Interfaces Sound Driver", ext : [".386"], magic : ["Human Machine Interfaces sound driver"]},
		javelinPrinterDriver          : {name : "Javelin Printer Driver", ext : [".pr", ".pr2"], magic : ["Javelin Printer driver"]},
		masiMusicDriver               : {name : "MASI Music Driver", ext : [".mus"], magic : ["MASI 16-bit protected mode Music driver", "MASI 16-bit real mode Music driver"]},
		neoPaintPrinterDriver         : {name : "NeoPaint Printer Driver", ext : [".prd"], magic : ["NeoPaint Printer Driver"]},
		megaPaintPrinterDriver        : {name : "MegaPaint Printer Driver", ext : [".trb"], magic : ["MegaPaint printer driver"]},
		milesSoundSystemDriver        : {name : "Miles Sound System Driver", ext : [".adv"], magic : ["Miles Sound System real mode drivers"]},
		os2DeviceDriver               : {name : "OS/2 Device Driver", ext : [".sys"], magic : ["OS/2 device driver"]},
		patchMeisterDriver            : {name : "PatchMeister Driver", ext : [".pmdriver"], magic : ["PatchMeister Driver"]},
		psionPrinterDriver            : {name : "Psion Printer Driver", ext : [".wdr"], magic : ["Psion Serie 3/3a printer driver", "Psion Series 5 printer driver"]},
		psionPhysicalDeviceDriver     : {name : "Psion Physical Device Driver", ext : [".pdd"], magic : ["Psion Physical Device Driver"]},
		sciTechDriver                 : {name : "SciTech Driver", ext : [".drv"], magic : ["SciTech Software UniVBE driver"]},
		soundImagesSoundDriver        : {name : "Sound Images Sound Driver", ext : [".bin"], magic : ["Sound Images Gen. 2 sound driver (v1.11)"]},
		starWriterPrinterDriver       : {name : "StarWriter Printer Driver", ext : [".gpm"], magic : ["StarWriter for MS-DOS Graphics Printer driver"]},
		starWriterVideoDriver         : {name : "StarWriter Video Driver", ext : [".hgd"], magic : ["StarWriter for MS-DOS Graphics video Driver"]},
		threeDFXGlideDriver           : {name : "3DFX Glide driver", ext : [".dxe"], magic : ["3DFX Glide driver"]},
		vektorGrafixDriver            : {name : "Vektor Grafix Driver", ext : [".drv"], magic : ["Vektor Grafix video Drivers"]},
		wordPerfectDriver             : {name : "WordPerfect Driver", ext : [".vrs"], magic : ["Corel WordPerfect: Unknown filetype 36, v5.0"]},


		//////////
		// ROMS //
		//////////
		atari7800ROM        : {name : "Atari 7800 ROM", ext : [".a78"], magic : ["Atari 7800 ROM"]},
		dreamcastDisc       : {name : "Dreamcast Disc", ext : [".bin"], magic : ["Sega Dreamcast disc image"]},
		gameBoyROM          : {name : "Game Boy ROM", ext : [".gb", ".gbc"], magic : ["GameBoy Color ROM File", "Game Boy ROM image"]},
		gameBoyAdvanceROM   : {name : "Game Boy Advance ROM", ext : [".gba"], magic : ["Game Boy Advance ROM image"]},
		genesisROM          : {name : "Sega Genesis/Megadrive/32x ROM", ext : [".bin", ".md"], magic : ["Sega Genesis / Megadrive / 32x ROM image", "Sega Mega Drive / Genesis ROM image"]},
		nintendoROM         : {name : "Nintendo ROM", ext : [".nes"], magic : ["NES ROM image", "Nintendo Entertainment System ROM"]},
		n64ROM              : {name : "Nintendo 64 ROM", ext : [".v64"], magic : ["Nintendo 64 ROM", "Doctor V64 ROM dump"]},
		qlPluginROM         : {name : "QL Plugin-ROM", magic : [/QL plugin-ROM data, named: [\w ;'"\][():/,._-]+$/]},
		segaMasterSystemROM : {name : "Sega Master System ROM", ext : [".sms"], magic : ["Sega Master System ROM image"]},
		vectrexGameROM      : {name : "Vectrex Game ROM", ext : [".vec", ".gam", ".bin"], magic : ["Vectrex game ROM"]},

		///////////
		// Other //
		///////////
		activInspireFlipchart        : {name : "ActivInspire Flipchart", ext : [".flipchart"], magic : ["ActivInspire Flipchart"]},
		adoragePreferences           : {name : "Adorage preferences", magic : ["Adorage preferences"]},
		adobeDuotoneOptions          : {name : "Adobe Duotone Options", ext : [".ado"], magic : ["Adobe Duotone Options"]},
		adobeMultipleMasterMetrics   : {name : "Adobe Multiple Master Metrics", ext : [".mmm"], magic : ["Adobe Multiple Master font", "Adobe Type Manager Multiple Master Metrics"]},
		adobePhotoshopGradient       : {name : "Adobe Photoshop Gradient", ext : [".grd"], magic : ["Adobe Photoshop gradient"]},
		adobeTypeFontInfo            : {name : "Adobe Type Manager Font Information", ext : [".inf"], magic : ["Adobe Type Manager Font Information"]},
		adobeHyphenationDictionary   : {name : "Adobe Hyphenation/Spelling Dictionary", ext : [".hyp"], magic : ["Adobe Hyphenation/spelling dictionary"]},
		adobePhotoshopColorBook      : {name : "Adobe Photoshop Color Book", ext : [".acb"], magic : ["Adobe Photoshop Color Book"]},
		adobePhotoshopCustomShape    : {name : "Adobe Photoshop Custom Shape", ext : [".csh"], magic : ["Adobe Photoshop Custom Shape"]},
		aegisProMotionGeometry       : {name : "Aegis Pro Motion Geometry", ext : [".geo"], magic : ["Aegis ProMotion Geometry"]},
		aibbLoadModule               : {name : "AIBB load Module", ext : [".module", ".aibb"], magic : ["AIBB load Module"]},
		alchemyMindworksResource     : {name : "Alchemy Mindworks Resource", ext : [".res"], magic : ["Alchemy Mindworks Resource data"]},
		alteraWaveformDesignFile     : {name : "Altera Waveform Design File", ext : [".wdf"], magic : ["Altera Waveform Design File"], weakMagic : true},
		amiAtlasFile                 : {name : "AmiAtlas File", ext : [".borders", ".coasts", ".index", ".islands", ".prefs", ".rivers", ".route", ".town", ".countries", ".country"], magic : ["AmiAtlas "]},
		amigaActionReplay3           : {name : "Amiga Action Replay 3 Freeze File", magic : ["Amiga Action Reply 3 Freeze File"]},
		amigaBlkDev                  : {name : "Amiga ADF BlkDev File", ext : [".blkdev"], magic : [...TEXT_MAGIC, /^data$/], weakMagic : true},
		amigaBootCode                : {name : "Amiga ADF Bootcode", ext : [".bootcode"], magic : [...TEXT_MAGIC, /^data$/], weakMagic : true},
		amigaCLIMateDirIndex         : {name : "Amiga CLI-Mate Directory Index File", filename : [".fastdir"]},
		amigaOutlineTag              : {name : "Amiga Outline Tag", ext : [".otag"], magic : ["AmigaOS outline tag"]},
		amigaXDFMeta                 : {name : "Amiga ADF XDF Meta", ext : [".xdfmeta"], magic : [...TEXT_MAGIC, /^data$/], weakMagic : true},
		amosAmalBank                 : {name : "Amos Amal Animation Bank", ext : [".abk"], magic : ["AMOS AMAL Bank"]},
		amosAsmBank                  : {name : "AMOS ASM Bank", ext : [".abk"], magic : ["AMOS Asm Bank"]},
		amosDatasBank                : {name : "AMOS Datas Bank", ext : [".abk"], magic : ["AMOS Data Bank", "AMOS Memory Bank, Data format", /^AMOS Basic memory bank.* type Data$/]},
		amosWorkBank                 : {name : "AMOS Work Bank", ext : [".abk"], magic : ["AMOS Work Bank"]},
		aniMouseTutorial             : {name : "AniMouse Tutorial", ext : [".sdemo"], magic : ["AniMouse Tutorial"]},
		apAssistCompressedData       : {name : "ApAssist Compressed Data", magic : ["ApAssist compressed data"]},
		artEffectBrush               : {name : "ArtEffect Brush", magic : ["ArtEffect brush"]},
		artEffectConvolution         : {name : "ArtEffect Convolution", magic : ["ArtEffect convolution"]},
		asciiFontMetrics             : {name : "ASCII Font Metrics", ext : [".afm"], magic : ["ASCII font metrics", "Outline Font Metric", "Adobe/Outline Font Metric"]},
		astoundActor                 : {name : "Astound Actor", ext : [".act"], magic : ["Astound Actor"]},
		atariCassetteTapeImage       : {name : "Atari Cassette Tape Image", ext : [".cas"], magic : ["Atari Cassette tape image"], weakMagic : true},
		atariCTBFile                 : {name : "Atari CTB File", ext : [".ctb"], magic : ["Atari CTB File"]},
		authorwareLibrary            : {name : "Authorware Library", ext : [".apl"], magic : ["Authorware Library"]},
		autoCADCompiledMenu          : {name : "AutoCAD Compiled Menu", ext : [".mnx"], magic : ["AutoCAD compiled Menu"]},
		autoDesk3DStudioMaterialLib  : {name : "AutoDesk 3D-Studio Material Library", ext : [".mli"], magic : ["AutoDesk 3D-Studio Material-Library"]},
		avsVideoEditorProject        : {name : "AVS Video Editor Project", ext : [".vep"], magic : ["AVS Video Editor Project"]},
		babbleData                   : {name : "Babble! Data", ext : [".bab"], magic : ["Babble! text data"]},
		barsAndPipesFile             : {name : "Bars and Pipes File", ext : [".gchone", ".gchord", ".song"], magic : ["Bars and Pipes"]},
		berkeleyDB                   : {name : "Berkeley DB", ext : [".db"], magic : ["Berkeley DB"]},
		billOfMaterials              : {name : "Bill of Materials", ext : [".bom"], magic : ["Bill Of Materials", "Mac OS X bill of materials"]},
		binaryColorFormat            : {name : "Binary Color Format", ext : [".bcf"], magic : ["Binary Color Format	"]},
		binPatchPatch                : {name : "BinPatch Patch", ext : [".utp"], magic : ["BinPatch patch"]},
		boyanActionModule            : {name : "BOYAN Action Model", ext : [".bam"], magic : ["BOYAN Action Module"]},
		buildEngineDemoData          : {name : "Build Engine Demo Data", ext : [".dem"], magic : ["Build engine Demo/replay data"]},
		butcherShape                 : {name : "Butcher Shape", ext : [".shape"], magic : ["Butcher Shape"]},
		cadDrawLibrary               : {name : "CAD/Draw Library", ext : [".tbl"], magic : ["TommySoftware CAD/Draw Library"]},
		cadDrawSettings              : {name : "CAD/Draw Settings", ext : [".mpi"], magic : ["TommySoftware CAD/Draw settings"]},
		cakewalkStudioWarePanel      : {name : "Cakewalk Studio Ware Panel", ext : [".CakewalkStudioWare"], magic : ["Cakewalk Studio Ware panel"]},
		cakeWalkWorkFile             : {name : "CakeWalk Work File", ext : [".wrk"], magic : ["Cakewalk Music project"]},
		calamusFarbColorTable        : {name : "Calamus Farb Color Table", ext : [".cft", ".cf"], magic : ["Calamus Farb (Colour) Table"]},
		calamusRasterInfo            : {name : "Calamus Raster Information", ext : [".cri", ".cr"], magic : ["Calamus Raster Information"]},
		calamusTextStyleList         : {name : "Calamus Text Style List", ext : [".csl", ".cs"], magic : ["Calamus textStyle List"]},
		calCompressedData            : {name : "Confusion and Light Compressed Data", ext : [".cal"], magic : ["CAL compressed data"]},
		caligariTrueSpaceData        : {name : "Caligari TrueSpace Data", magic : [/^Caligari TrueSpace data/]},
		chaosultdGEMParameters       : {name : "CHAOSultdGEM Parameters", ext : [".chs"], magic : ["CHAOSultdGEM parameters"]},
		characterTableLibrary        : {name : "Character Table Library", ext : [".tlb"], magic : ["Character Table Library"]},
		chemViewAnimationData        : {name : "Chemview Animation Data", ext : [".d"], magic : ["CHEMVIEW animation Data"]},
		cloneCDSubChannelData        : {name : "CloneCD CDImage SubChannel Data", ext : [".sub"], magic : ["Elaborate Bytes/SlySoft CloneCD CDImage (subchannel-data)"]},
		corelEditorMacro             : {name : "Corel Editor Macro", ext : [".edm"], magic : ["Corel Editor macro"]},
		corelPhotoPaintToneCurve     : {name : "Corel PhotoPaint Tone Curve", ext : [".crv"], magic : ["Corel PhotoPaint Tone Curve"]},
		corelPhotoPaintUserFilter    : {name : "COREL Photo Paint User Defined Filter", ext : [".usr"], magic : ["COREL Photo Paint User Defined Filter"]},
		corelShellMacro              : {name : "Corel Shell Macro", ext : [".shm"], magic : ["Corel shell macro"]},
		cracklibPasswordIndex        : {name : "Cracklib Password Index", ext : [".pwi"], magic : ["Cracklib password index"]},
		createShadeLights            : {name : "Create+Shade Lights", ext : [".lights"], magic : ["Create+Shade Lights"], weakMagic : true},
		cubaseDrumMap                : {name : "Cubase Drum Map", ext : [".drm"], magic : ["Cubase Drum Map"]},
		crystalAtariBrowserModule    : {name : "Crystal Atari Browser Module", ext : [".mdl"], magic : ["CAB Module"]},
		cybervisionMonitorInfo       : {name : "Cybervision Monitor Info", magic : ["Cybervision monitor info"]},
		cygnusEdDefaultSettings      : {name : "Cygnus Editor Default Settings", filename : ["ceddefaults"], magic : ["CygnusEd default settings"]},
		cygnusEdMacros               : {name : "Cygnus Editor Macros", filename : ["cedmacros"], magic : ["CygnusEd macros"]},
		dataStoreDatabase            : {name : "Datastore Database", magic : ["Datastore database"]},
		dBaseIndex                   : {name : "dBase Index File", ext : [".ntx"]},
		dBaseCompiledObjectProgram   : {name : "dBase Compiled Object Program", ext : [".dbo"], magic : ["dBASE compiled Object program"]},
		dBaseQuery                   : {name : "dBase Query", ext : [".qbe"], magic : ["dBASE IV Query"]},
		dBaseUpdate                  : {name : "dBase Update", ext : [".upd"], magic : ["dBASE IV Update"]},
		demoManiacVectors            : {name : "DemoManiac Vectors", ext : [".dat"], magic : ["DemoManiac vectors"]},
		demoShieldDemo               : {name : "DemoShield Demo", ext : [".dbd", ".bdd"], magic : ["DemoShield Demo"]},
		digitaORganiserTheme         : {name : "Digita Organiser Theme", magic : ["Digita Organiser theme"]},
		directoryOpusSettings        : {name : "Directory Opus Settings", magic : ["Directory Opus settings"]},
		dosCodePage                  : {name : "MS-DOS Code Page Info", ext : [".cp", ".cpi"], magic : ["DOS code page font data collection", "MS-DOS International Code Page Info"]},
		drawStudioGradient           : {name : "DrawStudio Gradient", magic : ["DrawStudio gradient"]},
		drawStudioPattern            : {name : "DrawStudio Pattern", magic : ["DrawStudio Pattern"]},
		drHardwareSysInfo            : {name : "Dr. Hardware Sysinfo", ext : [".dat"], magic : ["Dr. Hardware Sysinfo data"]},
		drWebAntiVirusDatabas        : {name : "Dr.Web Anti-Virus Database", ext : [".vdb"], magic : ["Dr.Web Anti-Virus Database"]},
		dvdInfoFile                  : {name : "DVD Info File", ext : [".ifo", ".bup"], magic : ["Video manager", "DVD Info file", /^x-fmt\/419( |$)/]},
		dynamicMessageSystemFile     : {name : "Dynamic Message System File", ext : [".msg"], magic : ["Dynamic Message System"]},
		ensoniqVFXPatchFile          : {name : "Ensoniq VFX Patch File", ext : [".vfx"], magic : ["SysEx File - Ensoniq"]},
		expresswarePrinterDefFile    : {name : "Expressware Printer Definition File", ext : [".pdf"], magic : ["Expressware Printer Definition File"]},
		fiascoDatabaseFile           : {name : "Fiasco Database File", ext : [".fdat", ".fidx", ".frec", ".fdb", ".fpr"], magic : ["Fiasco Database"]},
		fileExpressIndexHeader       : {name : "File Express Index Header", ext : [".ixh"], magic : ["File Express Index Header"]},
		fileExpressQuickScan         : {name : "File Express Quick Scan", ext : [".qss"], magic : ["File Express Quick Scan"]},
		fourDPaintProject            : {name : "4D Paint Project", ext : [".4dp"], magic : ["4D Paint Project"]},
		foxBaseMultipleIndex         : {name : "FoxBase Multiple Index", ext : [".mdx"], magic : ["FoxBase Multiple index"]},
		foxProCompoundIndex          : {name : "FoxPro Compound Index", ext : [".tdx", ".edx"], magic : [/^fmt\/375( |$)/]},
		foxProMemo                   : {name : "FoxPro Memo File", ext : [".fpt"], magic : ["Microsoft FoxPro Memo", "FoxPro FPT", "Sybase iAnywhere memo files"]},
		fractalDesignPaperTexture    : {name : "Fractal Design Painter Paper Texture", ext : [".pap"], magic : ["Fractal Design Painter Paper texture"]},
		fractalWeaveParameters       : {name : "Fractal Weave Parameters", ext : [".wwv"], magic : ["FractalWeave parameters"]},
		frontPageBTreeIndex          : {name : "Front Page Binary-Tree Index", ext : [".btr"], magic : ["FrontPage Binary-tree index"]},
		gammaCAD                     : {name : "GammaCAD Document", ext : [".sym", ".gc1"], magic : ["GammaCAD drawing/symbol"]},
		geoWorksGEOSData             : {name : "GeoWorks GEOS Data", ext : [".000", ".001", ".002", ".003", ".004", ".005", ".006", ".007", ".008", ".009", ".010", ".011", ".012", ".geo"], magic : ["GeoWorks data", "GeoWorks GEOS data"]},
		gettextMachineObject         : {name : "Gettext Machine Object", ext : [".gmo"], magic : ["GNU Gettext Machine Object"]},
		gfxLab24ConvolutionMatrix    : {name : "GfxLab24 Convolution Matrix", magic : ["GfxLab24 convolution matrix"]},
		gfxLab24Filter               : {name : "GfxLab24 Filter", magic : ["GfxLab24 filter"]},
		goDotC64ImageProcessing      : {name : "GoDot C64 Image Processing", magic : ["GoDot C64 Image Processing"]},
		hotMapRegionsDescription     : {name : "HotMap VBX Regions Description", ext : [".hmd"], magic : ["HotMap VBX regions Description"]},
		hyperPadPad                  : {name : "HyperPAD Pad", ext : [".pad"], magic : ["HyperPAD Pad"]},
		iBrowseGlobalCache           : {name : "iBrowse Global Cache", magic : ["IBrowse Global Cache"]},
		iccColorMap                  : {name : "ICC Color Map", ext : [".iff"], magic : ["IFF Color Map"]},
		iccColorProfile              : {name : "ICC Color Profile", ext : [".icc"], magic : ["ICC Color profile", /^color profile/]},
		idaSignatures                : {name : "IDA Signatures", ext : [".sig"], magic : ["IDA Signatures"]},
		iffBinaryPatch               : {name : "IFF Binary Patch", ext : [".pch", ".patch"], magic : ["IFF data, PTCH binary patch", "IFF binary Patch"]},
		iffDTYP                      : {name : "Amiga IFF DTYP", magic : ["Amiga IFF datatype info", "IFF data, DTYP datatype description"]},
		iffGXUI						 : {name : "Amiga IFF GXUI", ext : [".gui"], magic : ["IFF GXUI file"]},
		iffPrefs                     : {name : "Amiga Preferences", ext : [".prefs"], magic : ["Amiga Preferences", "IFF data, PREF preferences"]},
		imagineStagingData           : {name : "Imagine Staging Data", ext : [".istg"], magic : ["Imagine Staging data"]},
		indexerVolumeGUID            : {name : "Index Volume GUID", magic : ["IndexerVolumeGuid"]},
		internationalPatchingSystem  : {name : "International Patching System", ext : [".ips"], magic : ["International Patching System", "IPS patch file"], weakMagic : true},
		kaperskyAntiVirusLicenseKey  : {name : "Kapersky Anti-Virus License Key", ext : [".key"], magic : ["Kaspersky Anti-virus for DOS license"]},
		kissCELColorPalette		     : {name : "KiSS CEL Color Palette", ext : [".kcf"], magic : ["KiSS CEL color palette", "KISS/GS color"], weakMagic : true},
		klikNPlayGame                : {name : "Klik'n'Play Game", ext : [".gam"], magic : ["Klik'n'Play game"], weakMagic : true},
		kodakPrecisionTransform      : {name : "Kodak Precision Transform", ext : [".pt"], magic : ["Kodak Precision Transform"]},
		korgFile                     : {name : "KORG File", ext : [".pcg", ".bsq", ".arr", ".sty", ".sng"], magic : ["KORG File"], weakMagic : true},
		kryoFluxRawStream            : {name : "KryoFlux Raw Stream", ext : [".raw"], magic : ["KryoFlux raw stream", /^fmt\/656( |$)/]},
		labViewVirtualInstrument     : {name : "LabView Virtual Instrument", ext : [".vi"], magic : ["National Instruments, LabVIEW File, Virtual Instrument", "LABView Virtual Instrument"]},
		ldiffDifferencesData         : {name : "LDIFF Differences Data", ext : [".lzd"], magic : ["LDIFF differences data"]},
		life3000Status               : {name : "LIFE 3000 Status", ext : [".lif"], magic : ["LIFE 3000 status"]},
		linuxKernel                  : {name : "Linux Kernel", filename : ["vmlinuz", "bzImage"], magic : [/^Linux kernel$/, /^Linux kernel .*boot executable/, /^Linux .+kernel root/, "Linux kernel from prehistoric times", "Linux kernel version 1.3.79 or older"]},
		linuxSwapFile                : {name : "Linux Swap File", filename : ["swapfile"], magic : ["Linux old swap file", "Linux swap file"]},
		logicSimCircuit              : {name : "LogicSim Circuit", magic : ["LogicSim circuit"]},
		lotus123FormattingData       : {name : "Lotus 1-2-3 Formatting Data", ext : [".fm3"], magic : ["Formatting Data for Lotus 1-2-3 worksheet"]},
		lotus123SQZCompressed        : {name : "Lotus 1-2-3 SQZ! Compressed", ext : ["wq!"], magic : ["Lotus 123 SQZ! compressed Worksheet"]},
		lotsApproachView             : {name : "Lotus Approach View", ext : [".vew"], magic : ["Lotus Approach View"]},
		lotusFreelancePresentation   : {name : "Lotus Freelance Presentation", ext : [".prz"], magic : ["Lotus Freelance Graphics Presentation"]},
		lotusMagellanViewer          : {name : "Lotus Magellan Viewer", ext : [".vw2"], magic : ["Lotus Magellan Viewer"]},
		neoPaintPallette             : {name : "NeoPaint Palette", ext : [".pal"], magic : ["NeoPaint Palette"]},
		macromediaXtraCache          : {name : "Macromedia Xtra Cache", ext : [".mch"], magic : ["Macromedia Xtra Cache"]},
		maestroMusic                 : {name : "Maestro Music", magic : ["Maestro music", /^fmt\/1464( |$)/]},
		magicC64Preferences          : {name : "MagiC64 Preferences", ext : [".prefs"], magic : ["MagiC64 Preferences/settings"]},
		mapBrowserVectorData         : {name : "MapBrowser/MapWriter Vector Map Data", ext : ["cbd"], magic : ["MapBrowser / MapWriter vector map data"]},
		mathCadDocument              : {name : "MathCad Document", ext : [".mcd"], magic : ["Mathcad document"]},
		maxonResourceCreationData    : {name : "Maxon Resource Creation Tool Data", ext : [".rct"], magic : ["Maxon Resource Creation Tool data"]},
		memoryManagerResourceData    : {name : "Memory Manager Resource Data", magic : ["Memory Manager resource data"]},
		metaCreationsResourceFile    : {name : "MetaCreations Resource Composite File", magic : ["MetaCreations Resource Composite File (generic)", "Axiom Composite File Management System"]},
		microFocusFile               : {name : "Micro Focus File", ext : [".dat"], magic : ["Micro Focus File with Header"], weakMagic : true},
		microFocusIndexFile		     : {name : "Micro Focus Index File", ext : [".idx"], magic : ["Micro Focus Index File"], weakMagic : true},
		microLatheObject             : {name : "Micro Lathe Object", ext : [".lat"], magic : ["MicroLathe object"]},
		microsoftCertificateStore    : {name : "Microsoft Serialized Certificate Store", ext : [".sst"], magic : ["Microsoft Serialized certificate Store"]},
		microsoftFastFindIndex       : {name : "Microsoft FastFind Index", ext : [".ffx"], magic : ["Microsoft Fast Find Index"]},
		microsoftPrinterDefinition   : {name : "Microsoft Printer Definition", ext : [".prd"], magic : ["Microsoft Printer Definition"]},
		microsoftPrivateKey          : {name : "Microsoft Private Key", ext : [".pkv"], magic : ["Microsoft Private Key format"]},
		microsoftProgramDatabase     : {name : "Microsoft Program Database", ext : [".pdb"], magic : ["Microsoft Program DataBase", "MSVC program database"]},
		microsoftSecurityCatalog     : {name : "Microsoft Security Catalog", ext : [".cat"], magic : ["Microsoft Security Catalog"]},
		microsoftWordGlossary        : {name : "Microsoft Word Glossary", ext : [".gly"], magic : ["Microsoft Word for DOS Glossary"]},
		microsoftWordStyleSheet      : {name : "Microsoft Word Style Sheet", ext : [".sty"], magic : ["Microsoft Word for DOS Style sheet"]},
		midiDrumMachine              : {name : "MIDI Drum Machine", ext : [".drm"], magic : ["Midi Drum Machine Drum"], notes : "Program and source at: /browse/111/130%20MIDI%20Tool%20Box.iso/drum"},
		muiBuilderProject            : {name : "MUI Builder Project", ext : [".muib"], magic : ["MUI Builder project"]},
		netCDF                       : {name : "NetCDF", ext : [".nc"], magic : ["NetCDF "]},
		netscapeAddressBook          : {name : "Netscape Address Book", ext : [".nab"], magic : ["Netscape Address book"]},
		netShieldVirusPattern        : {name : "NetShield Virus Pattern Library", ext : [".dat"], magic : ["NetShield virus pattern library"]},
		netwareMessage               : {name : "Netware Message", ext : [".msg"], magic : ["NetWare Message"]},
		neroCoverDesigner            : {name : "Nero Cover Designer", ext : [".bcd"], magic : ["Nero CoverDesigner", /^fmt\/1368( |$)/]},
		nortonChangeDirInfo          : {name : "Norton Change Directory Info", ext : [".ncd"], magic : ["Norton Change Directory info"]},
		novellSystemPrintDef         : {name : "Novell System PrintDef Device Definition", ext : [".pdf"], magic : ["Novell System PrintDef Device Definition"]},
		nWiperShow					 : {name : "NWiper Show", ext : [".nw"], magic : ["NWiper show"]},
		os2ExtendedFileAttributes    : {name : "OS/2 Extended File Attributes", magic : ["OS/2 EA Extended file Attributes"]},
		os2DLL                       : {name : "OS/2 Dynamic Link Library", ext : [".dll"], magic : ["OS/2 Dynamic Link Library"]},
		os968kModule            	 : {name : "OS9/68k Module", filename : ["cdi_appl.pcd", "pcd_exec.pcd", "pcd_exec.dat"], magic : ["OS9/68K module"], weakMagic : true},
		paintersApprenticePrintInfo  : {name : "Painter's Apprentice Printer Info", ext : [".pri"], magic : ["Painter's Apprentice Printer Information"]},
		paperPortSlideShot           : {name : "PaperPort Slide Show", ext : [".fss"], magic : ["PaperPort slide show"]},
		papillonPalette              : {name : "Papillon Palette", ext : [".pal", ".ppal"], magic : ["Papillon Palette"]},
		paRISCObjectCode             : {name : "PA-RISC Object Code", ext : [".o"], magic : [/PA-RISC.* object code/, /PA-RISC.* relocatable object/], weakMagic : true},
		pascalCompiledUnit           : {name : "Pascal Compiled Unit", ext : [".tpu", ".ppu"], magic : ["Borland Turbo Pascal compiled Unit", "FreePascal compiled Unit", "Pascal unit"]},
		pcAnywhere                   : {name : "PCAnywhere Data", ext : [".bhf"], magic : ["PCAnywhere32 Data"]},
		peakGraphicalWaveform        : {name : "Peak Graphical Waveform", ext : [".pk"], magic : [/^fmt\/330( |$)/]},
		photoImpressionsAlbum        : {name : "PhotoImpressions Album", ext : [".abm"], magic : ["PhotoImpressions Album"], weakMagic : true},
		pgpKeyRing                   : {name : "PGP Key Ring", ext : [".key", ".pgp"], magic : ["Pretty Good Privacy (PGP) Public Keyring", "OpenPGP Public Key Version"]},
		platinenLayoutBibliotheken   : {name : "Platinen Layout Programm Bibliotheken/library", ext : [".bib"], magic : ["Platinen Layout Programm Bibliotheken/library"]},
		platinenLayoutLayout         : {name : "Platinen Layout Program Layout", ext : [".pla"], magic : ["Platinen Layout Programm Layout"]},
		polyfilmPrefs                : {name : "Polyfilm Preferences", ext : [".prf"], magic : ["Polyfilm Preferences"]},
		powerUpAlbumProject          : {name : "Power Up! Album Project", ext : [".alb"], magic : ["Power Up! Album project"]},
		printerFontMetrics           : {name : "Printer Font Metrics", ext : [".pfm"], magic : ["Adobe Printer Font Metrics", "Printer Font Metrics"]},
		proximityTechLexicon         : {name : "Proximity Technology Lexicon/Thesaurus", ext : [".lex", ".ths"], magic : ["Proximity Technology Lexicon/Thesaurus"]},
		psionApplicationAlias        : {name : "Psion Application Alias", ext : [".als"], magic : ["Psion serie 3 Application Alias"]},
		quickTextTitles              : {name : "QuickText Titles", magic : ["QuickText Titles"]},
		quickTimeInstallerCache      : {name : "QuickTime Installer Cache", ext : [".qdat", ".qda"], magic : ["QuickTime installer cache"]},
		reflectionsCamera            : {name : "Reflections Camera", ext : [".kam"], magic : ["Reflections camera"]},
		reflectionsData              : {name : "Reflections Data", ext : [".r3"], magic : ["Reflections IFF data (generic)"]},
		reflectionsMaterial          : {name : "Reflections Material", ext : [".mat"], magic : ["Reflections Material"]},
		reflectionsScene             : {name : "Reflections Scene", magic : ["Reflections scene/project"]},
		relocatableObjectModule      : {name : "Relocatable Object Module", ext : [".obj", ".o"], magic : ["OMF - Relocatable Object Module Format", "8086 relocatable"]},
		rfFlowDiagram                : {name : "RFFlow Diagram", ext : [".flo"], magic : ["RFFlow diagram"]},
		riffMSXF                     : {name : "RIFF MSFX File", ext : [".sfx"], magic : ["RIFF MSFX file"], notes : "Just contains meta info about a given soundeffect usually distributed alongside it as a .wav"},
		riffMxSt                     : {name : "RIFF MxSt File", ext : [".si"], magic : ["RIFF MxSt file"], notes : "References to other files, seems to be meta info only. Only info I could find, failed to process: https://github.com/dutchcoders/extract-riff"},
		riffPalette                  : {name : "RIFF Palette", ext : [".pal"], magic : ["RIFF Palette"]},
		riffSTYL                     : {name : "RIFF STYL File", ext : [".par"], magic : ["RIFF STYL file"], notes : "References a font for mac and windows and includes some text in a TEXT chunk"},
		rotObject3DAction            : {name : "ROT Object 3D Action", ext : [".rotact"], magic : ["ROT Object 3D Action"]},
		rtPatchFile                  : {name : "RTPatch File", ext : [".rtp"], magic : ["RTPatch update/diff data"]},
		samplitudeProject            : {name : "Samplitude Project", ext : [".rap", ".vip"], magic : ["Samplitude RAM Project", "Samplitude Virtual Project"]},
		sceneryAnimatorLandscape     : {name : "Scenery Animator Landscape", ext : [".scape"], magic : ["Scenery Animator landscape/keyframes"]},
		sculpt3DTake                 : {name : "Sculpt 3D Take", ext : [".take"], magic : ["Sculpt 3D Take"]},
		showPartnerMasteredShow      : {name : "Show Partner Mastered Show", ext : [".pro"], magic : ["Show Partner mastered show"]},
		smartDrawTemplate            : {name : "SmartDraw Template", ext : [".sdt", ".sdr"], magic : ["SmartDraw template"]},
		snifferCapture               : {name : "Sniffer Capture", ext : [".snf", ".trc"], magic : ["Sniffer capture"]},
		snoopCapture				 : {name : "Snoop Capture", ext : [".snoop"], magic : ["Snoop capture file"]},
		snxSnapshot                  : {name : "SNX Snapshot", ext : [".snx"], magic : ["SNX Snapshot"]},
		softDiskLibrary              : {name : "SoftDisk Library", ext : [".shl"], magic : ["Softdisk Help Library format"]},
		sonixMIDIInstrument          : {name : "Sonix MIDI Instrument", ext : [".instr"], magic : ["Sonix MIDI Instrument"]},
		soundForgePeakData           : {name : "Sound Forge Peak Data", ext : [".sfk"], magic : ["Sound Forge Peak Data File"]},
		speculatorSnapshot           : {name : "Speculator Snapshot", ext : [".zx82", ".zx"], magic : ["Speculator '97 snapshot"]},
		syslinuxLoader               : {name : "SYSLINUX loader", ext : [".sys"], magic : ["SYSLINUX loader"]},
		starTrekkerModuleInfo        : {name : "Startrekker Module Info", ext : [".nt"], magic : [/^Startrekker .*module info$/]},
		starWriterFormula            : {name : "StarWriter Formula", ext : [".frm"], magic : ["StarWriter for MS-DOS Formula"]},
		stormWizardResource          : {name : "StormWizard Resource", ext : [".wizard", ".wizard-all"], magic : ["IFF data, WZRD StormWIZARD resource", "StormWIZARD resource"]},
		superbaseForm                : {name : "Superbase Form", ext : [".sbv"], magic : ["Superbase form"]},
		superJamFile                 : {name : "SuperJAM! File", ext : [".chords", ".style", ".section", ".band", ".keyboard", ".patch", ".drummap"], magic : ["SuperJAM!"]},
		syslinuxCOM32Module          : {name : "Syslinux COM32 Module", ext : [".c32"], magic : ["Syslinux COM32 module"]},
		tcpdumpCapture				 : {name : "TCPDUMP Style Capture", ext : [".dmp", ".pcap"], magic : ["TCPDUMP's style capture", "pcap capture file"]},
		termInfo                     : {name : "TermInfo", magic : ["Compiled terminfo entry"]},
		texFontMetricData            : {name : "TeX Font Metric Data", ext : [".tfm"], magic : ["TeX font metric data"], weakMagic : true},
		texVirtualFont               : {name : "TeX Virtual Font", ext : [".vf"], magic : [/^TeX [Vv]irtual [Ff]ont/]},
		threeDStudioProject          : {name : "3D Studio Project", ext : [".prj"], magic : [/^3D Studio Project/]},
		thunderbyteAV                : {name : "Thunderbyte AV", ext : [".dat", ".eci", ".ec", ".sig", "sig"], magic : ["Thunderbyte AV", "ThunderByte Antivirus"]},
		threeDMovieMaker             : {name : "3D Movie Maker", ext : [".3mm", ".3th", ".chk", ".3cn"], magic : ["3D Movie Maker"]},
		thxTrackerInstrument         : {name : "THX Tracker Instrument", ext : [".ins"], magic : ["THX Tracker instrument"]},
		tiCalcBackup                 : {name : "Texas Instruments Calculator Backup", ext : [".73b", ".82b", ".83b", ".85b", ".86b", ".89b", ".92b"], magic : [/^TI-.* Graphing Calculator \(backup\)$/]},
		timeZoneData                 : {name : "TimeZone Data", ext : [".tz"], magic : [/^[Tt]ime[Zz]one data/]},
		tvPaintProject               : {name : "TVPaint Project", ext : [".tvpp", ".deep", ".aur"], magic : ["TVPaint Project"]},
		typeLibrary                  : {name : "Type Library", ext : [".tlb"], magic : [/^Type Library \(Type[12]\)$/]},
		uleadImageiioThumbnailInfo   : {name : "Ulead Imageioo Thumbnail Info", ext : [".pe3", ".pe4"], magic : ["Ulead Imageiio/Imaginfo thumbnail"]},
		vcdEntries                   : {name : "VCD Entries File", ext : [".vcd"], filename : ["entries.vcd"], magic : ["VCD Entries File"]},
		vesaDisplayIdentification    : {name : "VESA Display Identification File", ext : [".vdb"], magic : ["VESA Display Identification File"]},
		videoFX2Sequence             : {name : "VideoFX2 Sequence", ext : [".seq"], magic : ["VideoFX2 Sequence"]},
		videoTrackerRoutine          : {name : "VideoTracker Routine", ext : [".rot"], magic : ["VideoTracker Routine"]},
		videoMusicBoxProgression     : {name : "Video Music Box Progression", ext : [".prgn"], magic : ["Video Music Box Progression"]},
		videoMusicBoxStyle           : {name : "Video Music Box Style", ext : [".stle"], magic : ["Video Music Box Style"]},
		videoPadProject              : {name : "VideoPad Project", ext : [".vpj"], magic : ["VideoPad project"]},
		visionaireMesh               : {name : "Visionaire Mesh", ext : [".mesh"], magic : ["Visionaire Mesh"]},
		visionaireProject            : {name : "Visionaire Project", ext : [".vis"], magic : ["Visionaire project"]},
		vistaDigitalElevationMap     : {name : "Vista Digital Elevation Map", ext : [".dem"], magic : ["Vista Digital Elevation Map"]},
		vistaMakepathSession         : {name : "Vista Makepath Session", ext : [".ses"], magic : ["Vista Makepath Session (v1.0)"]},
		visualFoxProCompoundIndex    : {name : "Visual FoxPro Compound Index", ext : [".cdx"], magic : ["Compound index MS Visual FoxPro"]},
		vocalEyesSet                 : {name : "Vocal-Eyes Set", ext : [".set"], magic : ["Vocal-Eyes Set"]},
		watcomProfilerSamplingData   : {name : "Watcom Profiler Sampling Data", ext : [".smp"], magic : ["Watcom Profiler Sampling data"]},
		winampAdvVisStudioStyle      : {name : "Winamp Advanced Visualization Studio File", ext : [".avs"], magic : ["Winamp Advanced Visualization Studio File"]},
		windowsCalendar              : {name : "Windows Calendar", ext : [".cal"], magic : ["Windows Calendar"]},
		windowsHelpSearchIndex       : {name : "Windows Help Full Text Search Index", ext : [".fts"], magic : ["Windows Help Full-Text Search index file", "MS Windows help Full Text Search index"]},
		windowsHelpGIDIndex          : {name : "Windows Help Global Index Data", ext : [".gid"], magic : ["GID Help index", "MS Windows help Global Index"]},
		windowsLogoDrawingCode       : {name : "Windows LOGO Drawing Code", ext : [".lgo", ".lg"], magic : ["Windows logo drawing code"]},
		windowsProgramInfo           : {name : "Microsoft Windows Program Information File", ext : [".pif"], magic : ["Program Information File (Windows)", "Windows Program Information File"]},
		windowsShimDatabase          : {name : "Windows Shim Database", ext : [".sdb"], magic : ["Windows application compatibility Shim DataBase", "Windows Shim Database"]},
		windowsShortcut              : {name : "Windows Shortcut", ext : [".lnk"], magic : ["Windows Shortcut", "MS Windows shortcut"]},
		wordPerfectButtonBar         : {name : "WordPerfect for Windows Button Bar", ext : [".wwb"], magic : ["Corel WordPerfect: Unknown filetype 56"]},
		wordPerfectKeyboardFile      : {name : "WordPerfect keyboard file", ext : [".wpk"], magic : ["WordPerfect keyboard file"]},
		wordPerfectMacro             : {name : "WordPerfect Macro File", ext : [".wpm", ".wcm"], magic : [/^WordPerfect [Mm]acro/, "Corel WordPerfect: Unknown filetype 72", "Corel WordPerfect Macro", "WordPerfect (generic)"], weakMagic : ["WordPerfect (generic)"]},
		wordPerfectPrinterData       : {name : "WordPerfect Printer Data", ext : [".all", ".prd"], magic : ["WordPerfect printer data"]},
		wordStarPrinterDescFile      : {name : "WordStar Printer Description File", ext : [".pdf"], magic : ["WordStar Printer Description File"]},
		wordWorthPreferences         : {name : "WordWorth Preferences", magic : ["WordWorth preferences"]},
		yafaCompressionOptions       : {name : "YAFA Compression Options", magic : ["YAFA compression options"]},
		xCADModifierTable            : {name : "X-CAD Modifier Table", ext : [".obj"], magic : ["X-CAD Modifier Table"]},
		xCADOverlay                  : {name : "X-CAD Overlay", magic : ["X-CAD overlay"]}
	}
};
