import {TEXT_MAGIC} from "../Detection.js";

// All of the formats in this file are automatically 'unsupported' and are not processed, but can still be 'identified'
export default
{
	audio :
	{
		deluxeSoundSample : {name : "Deluxe Sound Sample", ext : [".instr"], magic : ["Deluxe Sound sampled instrument"]}
	},

	executable :
	{
		aDotOutExecutable : {name : "a.out Executable", ext : [".o"], magic : [/^a\.out .*executable/]},
		amigaExe          : {name : "AmigaOS Executable", magic : ["AmigaOS loadseg()ble executable/binary", "Amiga Hunk executable"]},
		atariCPX          : {name : "Atari Control Panel Extension Module", ext : [".cpx"], magic : ["Atari 68xxx CPX file", "Atari Control Panel applet"], weakMagic : true},
		atariSTExe        : {name : "Atari ST Executable", magic : ["Atari ST TOS executable", "Atari ST M68K contiguous executable", "Atari ST program/executable"]},
		com               : {name : "MS-DOS COM Executable", ext : [".com", ".c0m"], magic : ["DOS executable (COM", /^COM executable for (MS-)?DOS/, "16bit COM executable", "16bit DOS COM"]},
		elf               : {name : "ELF Executable", magic : ["ELF Executable and Linkable format", /^ELF \d\d-bit [LM]SB executable/, "Executable and Linkable Format"]},
		linux386Exe       : {name : "Linux i386 Executable", magic : [/^Linux.*386.*executable/]},
		omagic            : {name : "Linux OMAGIC Executable", magic : ["Linux i/386 OMAGIC executable", "Linux/i386 impure executable (OMAGIC)"]},
		macPPCPEFExe      : {name : "MacOS PPC PEF Executable", magic : ["Preferred Executable Format (PowerPC)", "header for PowerPC PEF executable"]},
		machOm68kExe      : {name : "Mach-O m68k Executable", magic : ["Mach-O m68k executable"]},
		mipsECOFFExe      : {name : "MIPSL ECOFF Executable", magic : [/^MIPSE[LB] ECOFF executable/]},
		msDOSDriver       : {name : "MS-DOS Driver", ext : [".sys", ".drv"], magic : [/^DOS executable \(.+ device driver/], weakMagic : true},
		riscOSExe         : {name : "RISC OS Executable", magic : ["RISC OS AIF executable"]},
		sparcDemandExe    : {name : "SPARC Demand Paged Exe", magic : ["SPARC demand paged dynamically linked executable not stripped"]},
		superbaseProgram  : {name : "Superbase Program", ext : [".sbp"], magic : ["Superbase Program"]},
		xex               : {name : "Atari Executable", ext : [".xex"], magic : ["Atari XE Executable"], weakMagic : true},
		zmagicExe         : {name : "Linux ZMAGIC Exectutable", magic : ["Linux i/386 ZMAGIC executable", "Linux/i386 demand-paged executable (ZMAGIC)"]}
	},

	font :
	{
		amigaOSOutlineFont    : {name : "AmigaOS Outline Font", ext : [".font"], magic : ["AmigaOS outline font"]},
		amiWriteFont          : {name : "AmiWrite Font", magic : ["Ami Write printer font"]},
		averyFont             : {name : "Avery Font", ext : [".ff1"], magic : ["Avery Font"]},
		bannerManiaFont       : {name : "Banner Mania Font", ext : [".fnt"], magic : ["Bannermania font"]},
		borlandGraphicsFont   : {name : "Borland Graphics Font", ext : [".chr", ".bgi"], magic : ["Borland font BGI Stroked Font", "BGI (Borland Graphics Interface) font", "Borland font"]},
		bradfordFont          : {name : "Bradford Font", ext : [".bf2"], magic : ["Bradford Font"]},
		calamusFont           : {name : "Calamus Font", ext : [".cfn"], magic : ["Calamus Font Data"]},
		corelWiffenFont       : {name : "Corel Wiffen Font", ext : [".wfn"], magic : ["Corel Font/Symbol"]},
		dynaCADDVectorFont    : {name : "DynaCADD Vector Font", ext : [".fnt"], magic : ["DynaCADD vector Font"]},
		envisionPublisherFont : {name : "Envision Publisher Font", ext : [".svf"], magic : ["EnVision Publisher DTP Font"]},
		grxFont               : {name : "GRX Font", ext : [".fnt"], magic : ["GRX Font", "libGrx font data"]},
		laserJetSoftFont      : {name : "LaserJet Soft Font", ext : [".sfl", ".sfp", ".sft"], magic : ["LaserJet Soft Font"]},
		linkWayFont           : {name : "LinkWay Font", ext : [".fmf"], magic : ["LinkWay Font"]},
		lotusRasterFont       : {name : "Lotus Raster Font", ext : [".lrf"], magic : ["Lotus Raster Font"]},
		lotusVectorFont       : {name : "Lotus Vector Font", ext : [".lvf"], magic : ["Lotus Vector Font"]},
		macOSFont             : {name : "MacOS Font", ext : [".fnt"], magic : ["Mac OSX datafork font, 'FONT'"]},
		printPartnerFont      : {name : "PrintPartner Font", ext : [".font"], magic : ["PrintPartner Font"]},
		psionFont             : {name : "Psion Font", ext : [".fon"], magic : ["Psion fast Font", "Psion Font"]},
		signumFont            : {name : "Signum Font", ext : [".e24"], magic : ["Bitmapped Signum!2 printer font (screen)"]},
		texPackedFont         : {name : "TeX Packed Font", ext : [".pf"], magic : [/^TeX [Pp]acked font/]},
		theDrawFont           : {name : "TheDraw Font", ext : [".tdf"], magic : ["TheDraw Fonts"], notes : "Bitmap font file used by programs like Neopaint for MSDOS and maybe GEM OS. Fontforge doesn't handle it"},
		threeDCKFont          : {name : "3D Construction Kit Font", ext : [".3fd"], magic : [/^3D Construction Kit \d? ?Font$/]},
		vFontFont             : {name : "VFONT Font", ext : [".fnt"], magic : ["VFONT Font"]},
		westwoodFont          : {name : "Westwood Font", ext : [".fnt"], magic : ["Westwood Font Format"]},
		wordUpToolkitFont     : {name : "WordUp Graphics Toolkit Font", ext : [".wfn"], magic : ["Wordup Graphics Toolkit Font"]},
		x11NeWSFontFamily     : {name : "X11/NeWS font family", ext : [".ff"], magic : ["X11/NeWS font family"]}
	},

	music :
	{
		encoreMusicalNotation : {name : "Encore Musical Notation", ext : [".enc", ".mus"], magic : ["Encore Musical Notation"]},
		improviseMusicData    : {name : "Improvise Music Data", ext : [".imp"], magic : ["Improvise music data"]}
	},
	
	other :
	{
		//////////
		// Game //
		//////////
		adventureGameToolkitStrings : {name : "Adventure Game Toolkit Strings", ext : [".d$$"], magic : ["Adventure Game Toolkit temporary strings"]},
		abuseLevel                  : {name : "Abuse Level", ext : [".lvl", ".spe"], magic : ["Abuse Level"]},
		blockBreakerPattern         : {name : "Block Breaker Pattern", ext : [".blc"], magic : ["Block Breaker pattern"]},
		chessAssistant              : {name : "Chess Assistant File", ext : [".bic", ".bid", ".bim", ".bis", ".lib", ".bfi", ".dsc", ".ndx", ".bdy"], magic : ["Chess Assistant "]},
		corncob3DData               : {name : "Corncob 3D Data File", ext : [".cct"], magic : ["Corncob 3D Theater-of-operation data"]},
		createAdventureGamesProject : {name : "Create Adventure Games Project", ext : [".cag"], magic : ["Create Adventure Games project"]},
		deHackEdPatch               : {name : "DeHackEd Patch", ext : [".deh"], magic : ["DeHackEd patch"]},
		descentLevel                : {name : "Descent Level", ext : [".rdl"], magic : ["Descent Level"]},
		doomSaveGame                : {name : "DOOM Save Game", ext : [".dsg"], magic : ["Doom SaveGame"]},
		diveFileFormat              : {name : "Dive File Format", ext : [".dff"], magic : ["Dive File Format - RenderWare"]},
		electronicArtsLibContainer  : {name : "Electronic Arts LIB container", ext : [".lib"], magic : ["Electronic Arts LIB container"]},
		flightSimToolkitTerrain     : {name : "Flight Sim Toolkit Terrain Data", ext : [".ftd"], magic : ["Flight Sim Toolkit Terrain Data"]},
		fullTiltPinballData         : {name : "Full Tilt Pinball Data", ext : [".dat"], magic : ["Full Tilt! Pinball table data"]},
		halfLife2SaveGame           : {name : "Half-Life 2 Save Game", ext : [".sav"], magic : ["Half-Life 2 savegame"]},
		homeBrewLevel               : {name : "HomeBrew Level", ext : [".hle"], magic : ["HomeBrew Level"]},
		homeBrewPalette             : {name : "HomeBrew Palette", ext : [".hpa"], magic : ["HomeBrew Palette"]},
		homeBrewTile                : {name : "HomeBrew Tile", ext : [".hti"], magic : ["HomeBrew Tile"]},
		infinityEngineFile          : {name : "Infinity Engine File", ext : [".dlg", ".cre", ".itm", ".are", ".tlk", ".spl", ".sto"], magic : ["Infinity Engine "]},
		jazzJackrabbitFile          : {name : "Jazz Jackrabbit File", ext : [".0sc", ".0fn"], magic : ["Jazz Jackrabbit font/cutscene", "Jazz Jackrabbit map"]},
		legendOfKyrandiaEMCFile     : {name : "Legend of Kyrandia EMC File", ext : [".emc"], magic : ["Kyra Engine game data"]},
		lucasFilmData               : {name : "LucasFilm Data", ext : [".lfd"], magic : ["LucasFilm Data", "Lucas Film Data - Panel"]},
		midiMazeIIMaze              : {name : "MIDI-MAZE II Maze", ext : [".mze"], magic : ["MIDI-MAZE II Maze"]},
		moonbaseGameData            : {name : "Moonbase Game Data", ext : [".mb"], magic : ["Moonbase game data"]},
		portsOfCallSaveGame         : {name : "Ports of Call Save Game", ext : [".trp"], magic : ["Ports of Call savegame"]},
		puzzleBusterPuzzle          : {name : "Puzzle Buster Puzzle", ext : [".puz"], magic : ["Puzzle Buster Puzzle"]},
		quakeMap                    : {name : "Quake Map", ext : [".bsp"], magic : ["Quake Map"]},
		quake2Map                   : {name : "Quake II Map", ext : [".bsp"], magic : ["Quake2 map", "Quake II Map file"]},
		quake2SpriteReference       : {name : "Quake II Sprite Reference", ext : [".sp2"], magic : ["Quake II SP2 sprite file"]},
		riseOfTheTriadLevel         : {name : "Rise of the Triad Level", ext : [".rtc", ".rtl"], magic : ["Rise of the Triad level"]},
		scorchedEarthMountainData   : {name : "Scorched Earth Mountain Data", ext : [".mtn"], magic : ["Scorched Earth Mountain range data"]},
		simCity2000SaveGameData     : {name : "SimCity 2000 Save Game Data", ext : [".sc", ".sc2"], magic : ["SimCity 2000 save game/map data"]},
		simCityCity                 : {name : "SimCity City", ext : [".cty"], magic : ["SimCity City"]},
		slicksNSlidesTrack          : {name : "Slicks 'n' Slide Track", ext : [".ss"], magic : ["Slicks 'n' Slide track data"]},
		starCraftMap                : {name : "StarCraft Map", ext : [".scm", ".scx"], magic : ["StarCraft Map"]},
		su27FlankerMission          : {name : "Su-27 Flanker Mission", ext : [".mis"], magic : ["Su-27 Flanker Mission"]},
		superZZTFile                : {name : "Super ZZT File", ext : [".szt"], magic : ["Super ZZT Game Creation System data format"]},
		tads                        : {name : "TADS", ext : [".t", ".gam"], magic : ["TADS 2 Game", /^TADS .*game data$/]},
		threeDCKArea                : {name : "3D Construction Kit Area", ext : [".3ad"], magic : [/^3D Construction Kit \d? ?Area$/]},
		threeDCKObject              : {name : "3D Construction Kit Object", ext : [".3od", ".obj"], magic : ["3D Construction Kit Object", /^3D Construction Kit (\d? ?)Object$/]},
		threeDCKShapeData           : {name : "3D Construction Kit Shape Data", ext : [".3sd"], magic : ["3D Construction Kit Shape data", /^3D Construction Kit \d? ?Shape data$/]},
		threeDCKWorldData           : {name : "3D Construction Kit World Data", ext : [".kit"], magic : ["3D Construction Kit World data", /^3D Construction Kit \d? ?World data$/]},
		warCraftMap                 : {name : "WarCraft Map", ext : [".pud"], magic : ["WarCraft map"]},
		winzlePuzzle                : {name : "Winzle Puzzle", ext : [".wzl"], magic : ["Winzle puzzle"]},
		wipeout2097TrackData        : {name : "Wipeout 2097 Track Data", ext : [".wad"], magic : ["Wipeout 2097 track data"]},
		zztFile                     : {name : "ZZT File", ext : [".zzt"], magic : ["ZZT Game Creation System data format"]},


		/////////////////
		// Programming //
		/////////////////
		alphaFourScript              : {name : "Alpha Four Script", ext : [".scp"], magic : ["Alpha Four Script"]},
		amigaBASICProtectedFile      : {name : "Amiga BASIC Protected File", ext : [".bas"], magic : ["AmigaBASIC source (protected)"]},
		amigaEModule                 : {name : "Amiga E Module", ext : [".m"], magic : ["Amiga E module", "E module/library"]},
		amigaLibrary                 : {name : "Amiga Hunk Library/Object", ext : [".lib", ".obj", ".o"], magic : ["AmigaOS object/library data", "Amiga Hunk library/object code"]},
		amigaSharedLibrary           : {name : "Amiga Shared Library", ext : [".lib"], magic : ["AmigaOS shared library"]},
		appleScriptCompiled          : {name : "Compiled AppleScript Script", magic : ["AppleScript compiled", "Compiled AppleScript script"]},
		atariGEMOBM                  : {name : "Atari GEM OBM File", ext : [".obm"], magic : ["Atari GEM OBM File"]},
		autoCADProtectedLISP         : {name : "AutoCAD Protected LISP", ext : [".lsp"], magic : ["AutoCAD Protected LISP Code"]},
		bnuportPatchTable            : {name : "BNUPORT Patch Table", ext : [".pat"], magic : ["BNUPORT Patch Table"]},
		borlandDelphiCompiledUnit    : {name : "Borland Delphi Compiled Unit", ext : [".dcu"], magic : ["Borland Delphi .DCU file", "Delphi 3 Compiled Unit"]},
		borlandLanguageLibrary       : {name : "Borland Language Library", ext : [".bll"], magic : ["Borland Language Library"]},
		borlandOverlay               : {name : "Borland Overlay", ext : [".ovr"], magic : ["Borland Overlay"]},
		clipperPreLinkedLibrary      : {name : "Clipper Pre-Linked Library", ext : [".pll"], magic : ["Clipper Pre-Linked Library"]},
		creativeSignalMicrocode      : {name : "Creative Signal Processor Microcode", ext : [".csp"], magic : ["Creative Signal Processor microcode"]},
		cornelHuthComprssedLibrary   : {name : "Cornel Huth Compressed Library", ext : [".li_"], magic : ["Cornel Huth compressed library"]},
		emacsCompiledLisp            : {name : "Emacs Compiled Lisp", ext : [".elc"], magic : [/^Emacs.*byte-compiled Lisp data$/], notes : "Could decompile it with: https://github.com/rocky/elisp-decompile"},
		highSpeedPascalUnit          : {name : "High Speed Pascal Unit", ext : [".unit"], magic : ["High Speed Pascal compiled Unit"]},
		iffSDBG                      : {name : "Amiga IFF Debug File", ext : [".debug"], magic : ["IFF SDBG file"]},
		installShieldUninstallScript : {name : "InstallShield Uninstall Script", ext : [".isu"], magic : ["InstallShield Uninstall Script"]},
		intellCOFFObject             : {name : "Intel Common Object File Format Object", ext : [".obj"], magic : [/^Intel .*Common Object File Format (COFF) object/, /^Intel .*COFF object file/]},
		javaClass                    : {name : "Java Class File", ext : [".class"], magic : ["Java Compiled Object Code", "compiled Java class data", "Java bytecode"]},
		linux8086ObjectFile          : {name : "Linux 8086 Object File", ext : [".o"], magic : ["Linux-8086 object file"]},
		machOM68kObject              : {name : "Mach-O m68k Object", ext : [".o"], magic : ["Mach-O m68k object"]},
		mapleCommonBinary            : {name : "Maple Common Binary", ext : [".m"], magic : ["Maple Common Binary"]},
		mdiffPatchFile               : {name : "MDIFF Patch File", ext : [".mdf"], magic : ["MDIFF patch"]},
		microsoftDebug               : {name : "Microsoft Separate Debug Format", ext : [".dbg"], magic : ["Microsoft separate Debug format"]},
		microsoftIncrementalLinker   : {name : "Microsoft Incremental Linker Data", ext : [".ilk"], magic : ["Microsoft Incremental Linker data"]},
		microsoftVisualCFiles        : {name : "Microsoft Visual C Files", ext : [".bsc", ".sbr", ".wsp"], magic : ["MSVC .bsc", "MSVC .sbr", "MSVC .wsp"]},
		netwareLoadableModule        : {name : "Netware Loadable Module", ext : [".nlm"], magic : [/^Net[Ww]are Loadable Module/]},
		oberonSymbol                 : {name : "Oberon Symbol", ext : [".sym"], magic : ["Oberon V3 Symbol data"]},
		olbLib                       : {name : "OLB Library", magic : ["OLB Library"]},
		powerBasicHelp               : {name : "PowerBASIC Help", ext : [".pbh"], magic : ["PowerBASIC Help"]},
		powerBuilderDynamicLibrary   : {name : "PowerBuilder Dynamic Library", ext : [".pbd"], magic : ["PowerBuilder Dynamic library"]},
		psionLibrary                 : {name : "Psion Library", ext : [".dyl"], magic : ["Psion Library"]},
		telixCompiledScript          : {name : "Telix Compiled Script", ext : [".slc"], magic : ["Telix Compiled Script"]},
		turboLightningEnvironment    : {name : "Turbo Lightning Environment", ext : [".env"], magic : ["Turbo Lightning Environment"]},
		turboModula2SymbolData       : {name : "Turbo Modula-2 Symbol Data", ext : [".sym"], magic : ["Turbo Modula-2 Symbol data"]},
		turboPascalHelp              : {name : "Turbo Pascal Help", ext : [".hlp"], magic : ["Turbo Pascal Help"]},
		visualBasicExtension         : {name : "Visual Basic Extension", ext : [".vbx"], magic : ["Visual Basic eXtension/Custom Control"]},
		visualBasicTokenizedSource   : {name : "Visual Basic Tokenized Source", ext : [".bas"], magic : [/^Visual Basic \d source \(tokenized\)$/]},
		visualCLibrary               : {name : "Microsoft Visual C Library", ext : [".lib"], magic : ["Microsoft Visual C Library"]},
		visualSmalltalkLibrary       : {name : "Visual Smalltalk Enterprise Objects Library", ext : [".sll"], magic : ["Visual Smalltalk Enterprise objects Library"]},


		/////////////
		// Drivers //
		/////////////
		ailMidiDriver             : {name : "Audio Interface Library 3 Music/MIDI driver", ext : [".mdi"], magic : ["Audio Interface Library 3 Music/MIDI driver"]},
		ailDigitalAudioDriver     : {name : "Audio Interface Library 3 Digital audio driver", ext : [".dig"], magic : ["Audio Interface Library 3 Digital audio driver"]},
		allwaysPrinterDriver      : {name : "Allways Printer Driver", ext : [".apc", ".apd", ".apf"], magic : ["Allways Printer driver"]},
		borlandDriver             : {name : "Borland Graphics Interface Driver", ext : [".bgi"], magic : ["Borland Graphics Interface driver", "Borland device BGI Device Driver", "Borland Graphics printer driver"]},
		bwsbMusicSoundDriver      : {name : "BWSB Music and Sound Engine Driver", ext : [".mse"], magic : ["BWSB Music and Sound Engine driver"]},
		geePrinterDriver          : {name : "Gee! Printer Driver", ext : [".pdr"], magic : ["Gee! Printer Driver"]},
		javelinPrinterDriver      : {name : "Javelin Printer Driver", ext : [".pr", ".pr2"], magic : ["Javelin Printer driver"]},
		masiMusicDriver           : {name : "MASI Music Driver", ext : [".mus"], magic : ["MASI 16-bit protected mode Music driver", "MASI 16-bit real mode Music driver"]},
		neoPaintPrinterDriver     : {name : "NeoPaint Printer Driver", ext : [".prd"], magic : ["NeoPaint Printer Driver"]},
		megaPaintPrinterDriver    : {name : "MegaPaint Printer Driver", ext : [".trb"], magic : ["MegaPaint printer driver"]},
		milesSoundSystemDriver    : {name : "Miles Sound System Driver", ext : [".adv"], magic : ["Miles Sound System real mode drivers"]},
		patchMeisterDriver        : {name : "PatchMeister Driver", ext : [".pmdriver"], magic : ["PatchMeister Driver"]},
		psionPrinterDriver        : {name : "Psion Printer Driver", ext : [".wdr"], magic : ["Psion Serie 3/3a printer driver"]},
		psionPhysicalDeviceDriver : {name : "Psion Physical Device Driver", ext : [".pdd"], magic : ["Psion Physical Device Driver"]},
		sciTechDriver             : {name : "SciTech Driver", ext : [".drv"], magic : ["SciTech Software UniVBE driver"]},
		starWriterPrinterDriver   : {name : "StarWriter Printer Driver", ext : [".gpm"], magic : ["StarWriter for MS-DOS Graphics Printer driver"]},
		starWriterVideoDriver     : {name : "StarWriter Video Driver", ext : [".hgd"], magic : ["StarWriter for MS-DOS Graphics video Driver"]},
		vektorGrafixDriver        : {name : "Vektor Grafix Driver", ext : [".drv"], magic : ["Vektor Grafix video Drivers"]},
		wordPerfectDriver         : {name : "WordPerfect Driver", ext : [".vrs"], magic : ["Corel WordPerfect: Unknown filetype 36, v5.0"]},


		//////////
		// ROMS //
		//////////
		gameBoyROM  : {name : "Game Boy ROM", ext : [".gb", ".gbc"], magic : ["GameBoy Color ROM File", "Game Boy ROM image"]},
		nintendoROM : {name : "Nintendo ROM", ext : [".nes"], magic : ["NES ROM image", "Nintendo Entertainment System ROM"]},


		///////////
		// Other //
		///////////
		adobeDuotoneOptions          : {name : "Adobe Duotone Options", ext : [".ado"], magic : ["Adobe Duotone Options"]},
		adobeMultipleMasterMetrics   : {name : "Adobe Multiple Master Metrics", ext : [".mmm"], magic : ["Adobe Multiple Master font", "Adobe Type Manager Multiple Master Metrics"]},
		adobePhotoshopGradient       : {name : "Adobe Photoshop Gradient", ext : [".grd"], magic : ["Adobe Photoshop gradient"]},
		adobeTypeFontInfo            : {name : "Adobe Type Manager Font Information", ext : [".inf"], magic : ["Adobe Type Manager Font Information"]},
		alchemyMindworksResource     : {name : "Alchemy Mindworks Resource", ext : [".res"], magic : ["Alchemy Mindworks Resource data"]},
		adobeHyphenationDictionary   : {name : "Adobe Hyphenation/Spelling Dictionary", ext : [".hyp"], magic : ["Adobe Hyphenation/spelling dictionary"]},
		aegisProMotionGeometry       : {name : "Aegis Pro Motion Geometry", ext : [".geo"], magic : ["Aegis ProMotion Geometry"]},
		amiAtlasFile                 : {name : "AmiAtlas File", ext : [".borders", ".coasts", ".index", ".islands", ".prefs", ".rivers", ".route", ".town", ".countries", ".country"], magic : ["AmiAtlas "]},
		amigaActionReplay3           : {name : "Amiga Action Replay 3 Freeze File", magic : ["Amiga Action Reply 3 Freeze File"]},
		amigaBlkDev                  : {name : "Amiga ADF BlkDev File", ext : [".blkdev"], magic : [...TEXT_MAGIC, /^data$/], weakMagic : true},
		amigaBootCode                : {name : "Amiga ADF Bootcode", ext : [".bootcode"], magic : [...TEXT_MAGIC, /^data$/], weakMagic : true},
		amigaCLIMateDirIndex         : {name : "Amiga CLI-Mate Directory Index File", filename : [".fastdir"]},
		amigaOutlineTag              : {name : "Amiga Outline Tag", ext : [".otag"], magic : ["AmigaOS outline tag"]},
		amigaXDFMeta                 : {name : "Amiga ADF XDF Meta", ext : [".xdfmeta"], magic : [...TEXT_MAGIC, /^data$/], weakMagic : true},
		amosAmalBank                 : {name : "Amos Amal Animation Bank", ext : [".abk"], magic : ["AMOS AMAL Bank"]},
		amosAsmBank                  : {name : "AMOS ASM Bank", ext : [".abk"], magic : ["AMOS Asm Bank"]},
		amosDatasBank                : {name : "AMOS Datas Bank", ext : [".abk"], magic : ["AMOS Data Bank", "AMOS Memory Bank, Data format", /^AMOS Basic memory bank.* type Data$/]},
		amosWorkBank                 : {name : "AMOS Work Bank", ext : [".abk"], magic : ["AMOS Work Bank"]},
		aniMouseTutorial             : {name : "AniMouse Tutorial", ext : [".sdemo"], magic : ["AniMouse Tutorial"]},
		artEffectBrush               : {name : "ArtEffect Brush", magic : ["ArtEffect brush"]},
		artEffectConvolution         : {name : "ArtEffect Convolution", magic : ["ArtEffect convolution"]},
		asciiFontMetrics             : {name : "ASCII Font Metrics", ext : [".afm"], magic : ["ASCII font metrics", "Outline Font Metric"]},
		atariCTBFile                 : {name : "Atari CTB File", ext : [".ctb"], magic : ["Atari CTB File"]},
		autoCADCompiledMenu          : {name : "AutoCAD Compiled Menu", ext : [".mnx"], magic : ["AutoCAD compiled Menu"]},
		autoDesk3DStudioMaterialLib  : {name : "AutoDesk 3D-Studio Material Library", ext : [".mli"], magic : ["AutoDesk 3D-Studio Material-Library"]},
		babbleData                   : {name : "Babble! Data", ext : [".bab"], magic : ["Babble! text data"]},
		barsAndPipesFile             : {name : "Bars and Pipes File", ext : [".gchone", ".gchord", ".song"], magic : ["Bars and Pipes"]},
		binaryColorFormat            : {name : "Binary Color Format", ext : [".bcf"], magic : ["Binary Color Format	"]},
		boyanActionModule            : {name : "BOYAN Action Model", ext : [".bam"], magic : ["BOYAN Action Module"]},
		buildEngineDemoData          : {name : "Build Engine Demo Data", ext : [".dem"], magic : ["Build engine Demo/replay data"]},
		buildEngineRFFContainer      : {name : "Build Engine RFF Container", ext : [".rff"], magic : ["Build Engine RFF encrypted container"]},
		cadDrawLibrary               : {name : "CAD/Draw Library", ext : [".tbl"], magic : ["TommySoftware CAD/Draw Library"]},
		cadDrawSettings              : {name : "CAD/Draw Settings", ext : [".mpi"], magic : ["TommySoftware CAD/Draw settings"]},
		cakewalkStudioWarePanel      : {name : "Cakewalk Studio Ware Panel", ext : [".CakewalkStudioWare"], magic : ["Cakewalk Studio Ware panel"]},
		cakeWalkWorkFile             : {name : "CakeWalk Work File", ext : [".wrk"], magic : ["Cakewalk Music project"]},
		calamusFarbColorTable        : {name : "Calamus Farb Color Table", ext : [".cft", ".cf"], magic : ["Calamus Farb (Colour) Table"]},
		calamusRasterInfo            : {name : "Calamus Raster Information", ext : [".cri", ".cr"], magic : ["Calamus Raster Information"]},
		calamusTextStyleList         : {name : "Calamus Text Style List", ext : [".csl", ".cs"], magic : ["Calamus textStyle List"]},
		calCompressedData            : {name : "Confusion and Light Compressed Data", ext : [".cal"], magic : ["CAL compressed data"]},
		caligariTrueSpaceData        : {name : "Caligari TrueSpace Data", magic : [/^Caligari TrueSpace data/]},
		chaosultdGEMParameters       : {name : "CHAOSultdGEM Parameters", ext : [".chs"], magic : ["CHAOSultdGEM parameters"]},
		characterTableLibrary        : {name : "Character Table Library", ext : [".tlb"], magic : ["Character Table Library"]},
		chemViewAnimationData        : {name : "Chemview Animation Data", ext : [".d"], magic : ["CHEMVIEW animation Data"]},
		corelEditorMacro             : {name : "Corel Editor Macro", ext : [".edm"], magic : ["Corel Editor macro"]},
		corelShellMacro              : {name : "Corel Shell Macro", ext : [".shm"], magic : ["Corel shell macro"]},
		cybervisionMonitorInfo       : {name : "Cybervision Monitor Info", magic : ["Cybervision monitor info"]},
		cygnusEdDefaultSettings      : {name : "Cygnus Editor Default Settings", filename : ["ceddefaults"], magic : ["CygnusEd default settings"]},
		cygnusEdMacros               : {name : "Cygnus Editor Macros", filename : ["cedmacros"], magic : ["CygnusEd macros"]},
		dBaseIndex                   : {name : "dBase Index File", ext : [".ntx"]},
		dBaseCompiledObjectProgram   : {name : "dBase Compiled Object Program", ext : [".dbo"], magic : ["dBASE compiled Object program"]},
		dBaseQuery                   : {name : "dBase Query", ext : [".qbe"], magic : ["dBASE IV Query"]},
		dBaseUpdate                  : {name : "dBase Update", ext : [".upd"], magic : ["dBASE IV Update"]},
		dosCodePage                  : {name : "MS-DOS Code Page Info", ext : [".cp", ".cpi"], magic : ["DOS code page font data collection", "MS-DOS International Code Page Info"]},
		drWebAntiVirusDatabas        : {name : "Dr.Web Anti-Virus Database", ext : [".vdb"], magic : ["Dr.Web Anti-Virus Database"]},
		dynamicMessageSystemFile     : {name : "Dynamic Message System File", ext : [".msg"], magic : ["Dynamic Message System"]},
		ensoniqVFXPatchFile          : {name : "Ensoniq VFX Patch File", ext : [".vfx"], magic : ["SysEx File - Ensoniq"]},
		expresswarePrinterDefFile    : {name : "Expressware Printer Definition File", ext : [".pdf"], magic : ["Expressware Printer Definition File"]},
		fiascoDatabaseFile           : {name : "Fiasco Database File", ext : [".fdat", ".fidx", ".frec", ".fdb", ".fpr"], magic : ["Fiasco Database"]},
		fileExpressIndexHeader       : {name : "File Express Index Header", ext : [".ixh"], magic : ["File Express Index Header"]},
		fileExpressQuickScan         : {name : "File Express Quick Scan", ext : [".qss"], magic : ["File Express Quick Scan"]},
		fourDPaintProject            : {name : "4D Paint Project", ext : [".4dp"], magic : ["4D Paint Project"]},
		foxProMemo                   : {name : "FoxPro Memo File", ext : [".fpt"], magic : ["Microsoft FoxPro Memo", "FoxPro FPT", "Sybase iAnywhere memo files"]},
		fractalDesignPaperTexture    : {name : "Fractal Design Painter Paper Texture", ext : [".pap"], magic : ["Fractal Design Painter Paper texture"]},
		gammaCAD                     : {name : "GammaCAD Document", ext : [".sym", ".gc1"], magic : ["GammaCAD drawing/symbol"]},
		geoWorksGEOSData             : {name : "GeoWorks GEOS Data", ext : [".000", ".001", ".002", ".003", ".004", ".005", ".006", ".007", ".008", ".009", ".010", ".011", ".012", ".geo"], magic : ["GeoWorks data", "GeoWorks GEOS data"]},
		gettextMachineObject         : {name : "Gettext Machine Object", ext : [".gmo"], magic : ["GNU Gettext Machine Object"]},
		harvardGraphicsChart         : {name : "Harvard Graphics Chart", ext : [".ch3"], magic : ["Harvard Graphics Chart"]},
		hotMapRegionsDescription     : {name : "HotMap VBX Regions Description", ext : [".hmd"], magic : ["HotMap VBX regions Description"]},
		humanMachineInterfacesDriver : {name : "Human Machine Interfaces Sound Driver", ext : [".386"], magic : ["Human Machine Interfaces sound driver"]},
		hyperPadPad                  : {name : "HyperPAD Pad", ext : [".pad"], magic : ["HyperPAD Pad"]},
		iccColorMap                  : {name : "ICC Color Map", ext : [".iff"], magic : ["IFF Color Map"]},
		iccColorProfile              : {name : "ICC Color Profile", ext : [".icc"], magic : ["ICC Color profile", /^color profile/]},
		idaSignatures                : {name : "IDA Signatures", ext : [".sig"], magic : ["IDA Signatures"]},
		iffBinaryPatch               : {name : "IFF Binary Patch", ext : [".pch", ".patch"], magic : ["IFF data, PTCH binary patch", "IFF binary Patch"]},
		iffDTYP                      : {name : "Amiga IFF DTYP", magic : ["Amiga IFF datatype info", "IFF data, DTYP datatype description"]},
		iffGXUI						 : {name : "Amiga IFF GXUI", ext : [".gui"], magic : ["IFF GXUI file"]},
		iffPrefs                     : {name : "Amiga Preferences", ext : [".prefs"], magic : ["Amiga Preferences", "IFF data, PREF preferences"]},
		imagineStagingData           : {name : "Imagine Staging Data", ext : [".istg"], magic : ["Imagine Staging data"]},
		indexerVolumeGUID            : {name : "Index Volume GUID", magic : ["IndexerVolumeGuid"]},
		kaperskyAntiVirusLicenseKey  : {name : "Kapersky Anti-Virus License Key", ext : [".key"], magic : ["Kaspersky Anti-virus for DOS license"]},
		kodakPrecisionTransform      : {name : "Kodak Precision Transform", ext : [".pt"], magic : ["Kodak Precision Transform"]},
		kryoFluxRawStream            : {name : "KryoFlux Raw Stream", ext : [".raw"], magic : ["KryoFlux raw stream"]},
		labViewVirtualInstrument     : {name : "LabView Virtual Instrument", ext : [".vi"], magic : ["National Instruments, LabVIEW File, Virtual Instrument", "LABView Virtual Instrument"]},
		ldiffDifferencesData         : {name : "LDIFF Differences Data", ext : [".lzd"], magic : ["LDIFF differences data"]},
		life3000Status               : {name : "LIFE 3000 Status", ext : [".lif"], magic : ["LIFE 3000 status"]},
		linuxKernel                  : {name : "Linux Kernel", filename : ["vmlinuz", "bzImage"], magic : [/^Linux kernel$/, /^Linux kernel .*boot executable/, /^Linux .+kernel root/]},
		linuxSwapFile                : {name : "Linux Swap File", filename : ["swapfile"], magic : ["Linux old swap file", "Linux swap file"]},
		logicSimCircuit              : {name : "LogicSim Circuit", magic : ["LogicSim circuit"]},
		lotus123FormattingData       : {name : "Lotus 1-2-3 Formatting Data", ext : [".fm3"], magic : ["Formatting Data for Lotus 1-2-3 worksheet"]},
		lotus123SQZCompressed        : {name : "Lotus 1-2-3 SQZ! Compressed", ext : ["wq!"], magic : ["Lotus 123 SQZ! compressed Worksheet"]},
		lotusFreelancePresentation   : {name : "Lotus Freelance Presentation", ext : [".prz"], magic : ["Lotus Freelance Graphics Presentation"]},
		lotusMagellanViewer          : {name : "Lotus Magellan Viewer", ext : [".vw2"], magic : ["Lotus Magellan Viewer"]},
		neoPaintPallette             : {name : "NeoPaint Palette", ext : [".pal"], magic : ["NeoPaint Palette"]},
		mathCadDocument              : {name : "MathCad Document", ext : [".mcd"], magic : ["Mathcad document"]},
		mdfMediaDescriptor			 : {name : "Alcohol 120% Media Descriptor", ext : [".mds"], magic : ["Media Descriptor"]},
		metaCreationsResourceFile    : {name : "MetaCreations Resource Composite File", magic : ["MetaCreations Resource Composite File (generic)", "Axiom Composite File Management System"]},
		microLatheObject             : {name : "Micro Lathe Object", ext : [".lat"], magic : ["MicroLathe object"]},
		microsoftCertificateStore    : {name : "Microsoft Serialized Certificate Store", ext : [".sst"], magic : ["Microsoft Serialized certificate Store"]},
		microsoftPrinterDefinition   : {name : "Microsoft Printer Definition", ext : [".prd"], magic : ["Microsoft Printer Definition"]},
		microsoftProgramDatabase     : {name : "Microsoft Program Database", ext : [".pdb"], magic : ["Microsoft Program DataBase", "MSVC program database"]},
		microsoftSecurityCatalog     : {name : "Microsoft Security Catalog", ext : [".cat"], magic : ["Microsoft Security Catalog"]},
		microsoftWordStyleSheet      : {name : "Microsoft Word Style Sheet", ext : [".sty"], magic : ["Microsoft Word for DOS Style sheet"]},
		midiDrumMachine              : {name : "MIDI Drum Machine", ext : [".drm"], magic : ["Midi Drum Machine Drum"], notes : "Program and source at: /browse/111/130%20MIDI%20Tool%20Box.iso/drum"},
		muiBuilderProject            : {name : "MUI Builder Project", ext : [".muib"], magic : ["MUI Builder project"]},
		netwareMessage               : {name : "Netware Message", ext : [".msg"], magic : ["NetWare Message"]},
		nortonChangeDirInfo          : {name : "Norton Change Directory Info", ext : [".ncd"], magic : ["Norton Change Directory info"]},
		novellSystemPrintDef         : {name : "Novell System PrintDef Device Definition", ext : [".pdf"], magic : ["Novell System PrintDef Device Definition"]},
		paperPortSlideShot           : {name : "PaperPort Slide Show", ext : [".fss"], magic : ["PaperPort slide show"]},
		pascalCompiledUnit           : {name : "Pascal Compiled Unit", ext : [".tpu", ".ppu"], magic : ["Borland Turbo Pascal compiled Unit", "FreePascal compiled Unit", "Pascal unit"]},
		pcAnywhere                   : {name : "PCAnywhere Data", ext : [".bhf"], magic : ["PCAnywhere32 Data"]},
		pgpKeyRing                   : {name : "PGP Key Ring", ext : [".key", ".pgp"], magic : ["Pretty Good Privacy (PGP) Public Keyring", "OpenPGP Public Key Version"]},
		platinenLayoutBibliotheken   : {name : "Platinen Layout Programm Bibliotheken/library", ext : [".bib"], magic : ["Platinen Layout Programm Bibliotheken/library"]},
		platinenLayoutLayout         : {name : "Platinen Layout Program Layout", ext : [".pla"], magic : ["Platinen Layout Programm Layout"]},
		polyfilmPrefs                : {name : "Polyfilm Preferences", ext : [".prf"], magic : ["Polyfilm Preferences"]},
		powerUpAlbumProject          : {name : "Power Up! Album Project", ext : [".alb"], magic : ["Power Up! Album project"]},
		printerFontMetrics           : {name : "Printer Font Metrics", ext : [".pfm"], magic : ["Adobe Printer Font Metrics", "Printer Font Metrics"]},
		proximityTechLexicon         : {name : "Proximity Technology Lexicon/Thesaurus", ext : [".lex", ".ths"], magic : ["Proximity Technology Lexicon/Thesaurus"]},
		psionApplicationAlias        : {name : "Psion Application Alias", ext : [".als"], magic : ["Psion serie 3 Application Alias"]},
		quickTextTitles              : {name : "QuickText Titles", magic : ["QuickText Titles"]},
		reflectionsCamera            : {name : "Reflections Camera", ext : [".kam"], magic : ["Reflections camera"]},
		reflectionsData              : {name : "Reflections Data", ext : [".r3"], magic : ["Reflections IFF data (generic)"]},
		reflectionsMaterial          : {name : "Reflections Material", ext : [".mat"], magic : ["Reflections Material"]},
		reflectionsScene             : {name : "Reflections Scene", magic : ["Reflections scene/project"]},
		relocatableObjectModule      : {name : "Relocatable Object Module", ext : [".obj", ".o"], magic : ["OMF - Relocatable Object Module Format", "8086 relocatable"]},
		riffMSXF                     : {name : "RIFF MSFX File", ext : [".sfx"], magic : ["RIFF MSFX file"], notes : "Just contains meta info about a given soundeffect usually distributed alongside it as a .wav"},
		riffMxSt                     : {name : "RIFF MxSt File", ext : [".si"], magic : ["RIFF MxSt file"], notes : "References to other files, seems to be meta info only. Only info I could find, failed to process: https://github.com/dutchcoders/extract-riff"},
		riffPalette                  : {name : "RIFF Palette", ext : [".pal"], magic : ["RIFF Palette"]},
		riffSTYL                     : {name : "RIFF STYL File", ext : [".par"], magic : ["RIFF STYL file"], notes : "References a font for mac and windows and includes some text in a TEXT chunk"},
		rotObject3DAction            : {name : "ROT Object 3D Action", ext : [".rotact"], magic : ["ROT Object 3D Action"]},
		rtPatchFile                  : {name : "RTPatch File", ext : [".rtp"], magic : ["RTPatch update/diff data"]},
		samplitudeRAMProject         : {name : "Samplitude RAM Project", ext : [".rap"], magic : ["Samplitude RAM Project"]},
		sceneryAnimatorLandscape     : {name : "Scenery Animator Landscape", ext : [".scape"], magic : ["Scenery Animator landscape/keyframes"]},
		sculpt3DTake                 : {name : "Sculpt 3D Take", ext : [".take"], magic : ["Sculpt 3D Take"]},
		showPartnerMasteredShow      : {name : "Show Partner Mastered Show", ext : [".pro"], magic : ["Show Partner mastered show"]},
		smartDrawTemplate            : {name : "SmartDraw Template", ext : [".sdt", ".sdr"], magic : ["SmartDraw template"]},
		snoopCapture				 : {name : "Snoop Capture", ext : [".snoop"], magic : ["Snoop capture file"]},
		snxSnapshot                  : {name : "SNX Snapshot", ext : [".snx"], magic : ["SNX Snapshot"]},
		softDiskLibrary              : {name : "SoftDisk Library", ext : [".shl"], magic : ["Softdisk Help Library format"]},
		syslinuxLoader               : {name : "SYSLINUX loader", ext : [".sys"], magic : ["SYSLINUX loader"]},
		starTrekkerModuleInfo        : {name : "Startrekker Module Info", ext : [".nt"], magic : [/^Startrekker .*module info$/]},
		stormWizardResource          : {name : "StormWizard Resource", ext : [".wizard", ".wizard-all"], magic : ["IFF data, WZRD StormWIZARD resource", "StormWIZARD resource"]},
		superbaseForm                : {name : "Superbase Form", ext : [".sbv"], magic : ["Superbase form"]},
		superJamFile                 : {name : "SuperJAM! File", ext : [".chords", ".style", ".section", ".band", ".keyboard", ".patch", ".drummap"], magic : ["SuperJAM!"]},
		tcpdumpCapture				 : {name : "TCPDUMP Style Capture", ext : [".dmp", ".pcap"], magic : ["TCPDUMP's style capture", "pcap capture file"]},
		termInfo                     : {name : "TermInfo", magic : ["Compiled terminfo entry"]},
		texFontMetricData            : {name : "TeX Font Metric Data", ext : [".tfm"], magic : ["TeX font metric data"], weakMagic : true},
		texVirtualFont               : {name : "TeX Virtual Font", ext : [".vf"], magic : [/^TeX [Vv]irtual [Ff]ont/]},
		threeDStudioProject          : {name : "3D Studio Project", ext : [".prj"], magic : [/^3D Studio Project/]},
		thunderbyteAV                : {name : "Thunderbyte AV", ext : [".dat", ".eci", ".ec", ".sig", "sig"], magic : ["Thunderbyte AV", "ThunderByte Antivirus"]},
		timeZoneData                 : {name : "TimeZone Data", ext : [".tz"], magic : [/^[Tt]ime[Zz]one data/]},
		typeLibrary                  : {name : "Type Library", ext : [".tlb"], magic : [/^Type Library \(Type[12]\)$/]},
		uleadImageiioThumbnailInfo   : {name : "Ulead Imageioo Thumbnail Info", ext : [".pe3", ".pe4"], magic : ["Ulead Imageiio/Imaginfo thumbnail"]},
		vcdEntries                   : {name : "VCD Entries File", ext : [".vcd"], filename : ["entries.vcd"], magic : ["VCD Entries File"]},
		vesaDisplayIdentification    : {name : "VESA Display Identification File", ext : [".vdb"], magic : ["VESA Display Identification File"]},
		videoTrackerRoutine          : {name : "VideoTracker Routine", ext : [".rot"], magic : ["VideoTracker Routine"]},
		vistaDigitalElevationMap     : {name : "Vista Digital Elevation Map", ext : [".dem"], magic : ["Vista Digital Elevation Map"]},
		visualFoxProCompoundIndex    : {name : "Visual FoxPro Compound Index", ext : [".cdx"], magic : ["Compound index MS Visual FoxPro"]},
		vocalEyesSet                 : {name : "Vocal-Eyes Set", ext : [".set"], magic : ["Vocal-Eyes Set"]},
		windowsHelpSearchIndex       : {name : "Windows Help Full Text Search Index", ext : [".fts"], magic : ["Windows Help Full-Text Search index file", "MS Windows help Full Text Search index"]},
		windowsHelpGIDIndex          : {name : "Windows Help Global Index Data", ext : [".gid"], magic : ["GID Help index", "MS Windows help Global Index"]},
		windowsLogoDrawingCode       : {name : "Windows LOGO Drawing Code", ext : [".lgo", ".lg"], magic : ["Windows logo drawing code"]},
		windowsProgramInfo           : {name : "Microsoft Windows Program Information File", ext : [".pif"], magic : ["Program Information File (Windows)", "Windows Program Information File"]},
		windowsShimDatabase          : {name : "Windows Shim Database", ext : [".sdb"], magic : ["Windows application compatibility Shim DataBase", "Windows Shim Database"]},
		windowsShortcut              : {name : "Windows Shortcut", ext : [".lnk"], magic : ["Windows Shortcut", "MS Windows shortcut"]},
		wordPerfectButtonBar         : {name : "WordPerfect for Windows Button Bar", ext : [".wwb"], magic : ["Corel WordPerfect: Unknown filetype 56"]},
		wordPerfectKeyboardFile      : {name : "WordPerfect keyboard file", ext : [".wpk"], magic : ["WordPerfect keyboard file"]},
		wordPerfectMacro             : {name : "WordPerfect Macro File", ext : [".wpm", ".wcm"], magic : [/^WordPerfect [Mm]acro/, "Corel WordPerfect: Unknown filetype 72"]},
		wordPerfectPrinterData       : {name : "WordPerfect Printer Data", ext : [".all", ".prd"], magic : ["WordPerfect printer data"]}
	}
};
