from importlib import import_module


type_module_name_map = {
	'Byte': 'nifgen.formats.base.basic',
	'Ubyte': 'nifgen.formats.base.basic',
	'Uint64': 'nifgen.formats.base.basic',
	'Int64': 'nifgen.formats.base.basic',
	'Uint': 'nifgen.formats.base.basic',
	'Ushort': 'nifgen.formats.base.basic',
	'Int': 'nifgen.formats.base.basic',
	'Short': 'nifgen.formats.base.basic',
	'Char': 'nifgen.formats.base.basic',
	'Normshort': 'nifgen.formats.base.basic',
	'Rangeshort': 'nifgen.formats.base.basic',
	'Float': 'nifgen.formats.base.basic',
	'Double': 'nifgen.formats.base.basic',
	'Hfloat': 'nifgen.formats.base.basic',
	'ZString': 'nifgen.formats.base.basic',
	'ZStringBuffer': 'nifgen.formats.base.compounds.ZStringBuffer',
	'PadAlign': 'nifgen.formats.base.compounds.PadAlign',
	'FixedString': 'nifgen.formats.base.compounds.FixedString',
	'Vector2': 'nifgen.formats.base.compounds.Vector2',
	'Vector3': 'nifgen.formats.base.compounds.Vector3',
	'Vector4': 'nifgen.formats.base.compounds.Vector4',
	'Bool': 'nifgen.formats.ovl_base.basic',
	'OffsetString': 'nifgen.formats.ovl_base.basic',
	'Compression': 'nifgen.formats.ovl_base.enums.Compression',
	'VersionInfo': 'nifgen.formats.ovl_base.bitfields.VersionInfo',
	'Pointer': 'nifgen.formats.ovl_base.compounds.Pointer',
	'Reference': 'nifgen.formats.ovl_base.compounds.Reference',
	'LookupPointer': 'nifgen.formats.ovl_base.compounds.LookupPointer',
	'ArrayPointer': 'nifgen.formats.ovl_base.compounds.ArrayPointer',
	'CondPointer': 'nifgen.formats.ovl_base.compounds.CondPointer',
	'ForEachPointer': 'nifgen.formats.ovl_base.compounds.ForEachPointer',
	'MemStruct': 'nifgen.formats.ovl_base.compounds.MemStruct',
	'SmartPadding': 'nifgen.formats.ovl_base.compounds.SmartPadding',
	'ZStringObfuscated': 'nifgen.formats.ovl_base.basic',
	'GenericHeader': 'nifgen.formats.ovl_base.compounds.GenericHeader',
	'Empty': 'nifgen.formats.ovl_base.compounds.Empty',
	'ZStringList': 'nifgen.formats.ovl_base.compounds.ZStringList',
	'MotiongraphHeader': 'nifgen.formats.motiongraph.compounds.MotiongraphHeader',
	'LuaModules': 'nifgen.formats.motiongraph.compounds.LuaModules',
	'MotiongraphRootFrag': 'nifgen.formats.motiongraph.compounds.MotiongraphRootFrag',
	'ActivityEntry': 'nifgen.formats.motiongraph.compounds.ActivityEntry',
	'Activities': 'nifgen.formats.motiongraph.compounds.Activities',
	'Activity': 'nifgen.formats.motiongraph.compounds.Activity',
	'MRFEntry1': 'nifgen.formats.motiongraph.compounds.MRFEntry1',
	'MRFArray1': 'nifgen.formats.motiongraph.compounds.MRFArray1',
	'MotiongraphVar': 'nifgen.formats.motiongraph.compounds.MotiongraphVar',
	'MRFMember1': 'nifgen.formats.motiongraph.compounds.MRFMember1',
	'MRFEntry2': 'nifgen.formats.motiongraph.compounds.MRFEntry2',
	'MRFArray2': 'nifgen.formats.motiongraph.compounds.MRFArray2',
	'MRFMember2': 'nifgen.formats.motiongraph.compounds.MRFMember2',
	'Transition': 'nifgen.formats.motiongraph.compounds.Transition',
	'StateArray': 'nifgen.formats.motiongraph.compounds.StateArray',
	'TransStruct': 'nifgen.formats.motiongraph.compounds.TransStruct',
	'TransStructArray': 'nifgen.formats.motiongraph.compounds.TransStructArray',
	'MGTwo': 'nifgen.formats.motiongraph.compounds.MGTwo',
	'TransStructStop': 'nifgen.formats.motiongraph.compounds.TransStructStop',
	'TransStructStopList': 'nifgen.formats.motiongraph.compounds.TransStructStopList',
	'State': 'nifgen.formats.motiongraph.compounds.State',
	'XMLEntry': 'nifgen.formats.motiongraph.compounds.XMLEntry',
	'XMLArray': 'nifgen.formats.motiongraph.compounds.XMLArray',
	'AnimationFlags': 'nifgen.formats.motiongraph.bitstructs.AnimationFlags',
	'FloatInputData': 'nifgen.formats.motiongraph.compounds.FloatInputData',
	'SubCurveType': 'nifgen.formats.motiongraph.enums.SubCurveType',
	'CurveDataPoint': 'nifgen.formats.motiongraph.compounds.CurveDataPoint',
	'CurveDataPoints': 'nifgen.formats.motiongraph.compounds.CurveDataPoints',
	'CurveData': 'nifgen.formats.motiongraph.compounds.CurveData',
	'DataStreamResourceData': 'nifgen.formats.motiongraph.compounds.DataStreamResourceData',
	'DataStreamResourceDataPoints': 'nifgen.formats.motiongraph.compounds.DataStreamResourceDataPoints',
	'DataStreamResourceDataList': 'nifgen.formats.motiongraph.compounds.DataStreamResourceDataList',
	'AnimationActivityData': 'nifgen.formats.motiongraph.compounds.AnimationActivityData',
	'CoordinatedAnimationActivityData': 'nifgen.formats.motiongraph.compounds.CoordinatedAnimationActivityData',
	'ActivityAnimationInfo': 'nifgen.formats.motiongraph.compounds.ActivityAnimationInfo',
	'LoopedAnimationInfo': 'nifgen.formats.motiongraph.compounds.LoopedAnimationInfo',
	'RandomAnimationActivityData': 'nifgen.formats.motiongraph.compounds.RandomAnimationActivityData',
	'TurnFlags': 'nifgen.formats.motiongraph.bitstructs.TurnFlags',
	'TurnActivityData': 'nifgen.formats.motiongraph.compounds.TurnActivityData',
	'UseValueType': 'nifgen.formats.motiongraph.enums.UseValueType',
	'ForwardActivityData': 'nifgen.formats.motiongraph.compounds.ForwardActivityData',
	'RagdollPhysicsActivityFlags': 'nifgen.formats.motiongraph.bitstructs.RagdollPhysicsActivityFlags',
	'RagdollPhysicsActivityData': 'nifgen.formats.motiongraph.compounds.RagdollPhysicsActivityData',
	'BlendSpaceAxis': 'nifgen.formats.motiongraph.compounds.BlendSpaceAxis',
	'Locomotion2BlendSpace': 'nifgen.formats.motiongraph.compounds.Locomotion2BlendSpace',
	'Locomotion2ActivityData': 'nifgen.formats.motiongraph.compounds.Locomotion2ActivityData',
	'VariableBlendedAnimationData': 'nifgen.formats.motiongraph.compounds.VariableBlendedAnimationData',
	'HeadTargetActivityData': 'nifgen.formats.motiongraph.compounds.HeadTargetActivityData',
	'VariableBlendedAnimationActivityData': 'nifgen.formats.motiongraph.compounds.VariableBlendedAnimationActivityData',
	'Locomotion2AnimationInfo': 'nifgen.formats.motiongraph.compounds.Locomotion2AnimationInfo',
	'Locomotion2BlendSpaceNode': 'nifgen.formats.motiongraph.compounds.Locomotion2BlendSpaceNode',
	'FootPlantActivityData': 'nifgen.formats.motiongraph.compounds.FootPlantActivityData',
	'TimeLimitMode': 'nifgen.formats.motiongraph.enums.TimeLimitMode',
	'SelectActivityActivityMode': 'nifgen.formats.motiongraph.enums.SelectActivityActivityMode',
	'DataStreamProducerActivityData': 'nifgen.formats.motiongraph.compounds.DataStreamProducerActivityData',
	'ActivitiesLink': 'nifgen.formats.motiongraph.compounds.ActivitiesLink',
	'ActivitiesLinks': 'nifgen.formats.motiongraph.compounds.ActivitiesLinks',
	'SelectActivityActivityData': 'nifgen.formats.motiongraph.compounds.SelectActivityActivityData',
	'GroupedActivityActivityData': 'nifgen.formats.motiongraph.compounds.GroupedActivityActivityData',
	'RandomActivityActivityInfoData': 'nifgen.formats.motiongraph.compounds.RandomActivityActivityInfoData',
	'SinglePtr': 'nifgen.formats.motiongraph.compounds.SinglePtr',
	'SingleRef': 'nifgen.formats.motiongraph.compounds.SingleRef',
	'RefList': 'nifgen.formats.motiongraph.compounds.RefList',
	'PtrList': 'nifgen.formats.motiongraph.compounds.PtrList',
	'StateList': 'nifgen.formats.motiongraph.compounds.StateList',
	'MotiongraphVars': 'nifgen.formats.motiongraph.compounds.MotiongraphVars',
	'Something': 'nifgen.formats.motiongraph.compounds.Something',
	'MRFChild': 'nifgen.formats.motiongraph.compounds.MRFChild',
}

name_type_map = {}
for type_name, module in type_module_name_map.items():
	name_type_map[type_name] = getattr(import_module(module), type_name)
for class_object in name_type_map.values():
	if callable(getattr(class_object, 'init_attributes', None)):
		class_object.init_attributes()
