[IR_PCD]
~Default Mode=Standard Options
~Mode=Standard Options
~Header=PCD Import Filter Setup

Standard Options=IR_PCD.1

[Standard Options]
Driver=IM_PCD.1

;PCD_RES_BASE_OVER_16          1
;PCD_RES_BASE_OVER_4           2
;PCD_RES_BASE                  3
;PCD_RES_4BASE                 4
;PCD_RES_16BASE                5
Resolution=2


;PCD_FORMAT_SINGLE             10
;PCD_FORMAT_RGB                12
;PCD_FORMAT_PALETTE            13
Format=13

;PCD_TRAN_ROTATE_0             0
;PCD_TRAN_ROTATE_90            1
;PCD_TRAN_ROTATE_180           2
;PCD_TRAN_ROTATE_270           3
;PCD_TRAN_MIRROR_0             4
;PCD_TRAN_MIRROR_90            5
;PCD_TRAN_MIRROR_180           6
;PCD_TRAN_MIRROR_270           7
Transform=0
