[IBXPM]
~Default Mode=Standard Options
~Mode=Standard Options
~Header=XPM Import Filter Setup

Standard Options=IBXPM.1

[Standard Options]
Driver=IBXPM.1

;MONO        0
;COLOR       1
;SYMBOLIC    2
Color Mode=1



