[IM_PPT]
~Default Mode=PowerPoint (Ver. T.x)
~Mode=PowerPoint (Ver. x.x)
~Header=PPT Import Filter Setup

PowerPoint (Ver. x.x)=IM_PPT.1

[PowerPoint (Ver. x.x)]
Driver=IM_PPT.1
ColorTableSource=FILE
ImportContent=Graphics
; ImportContent=Chart Data
; ImportContent=Graphics & Chart Data


