
// DO NOT EDIT MANUALLY
// AUTO GENERATED BY build/buildPrograms.js
// DO NOT EDIT MANUALLY
const programs = {};
import {dexvert} from "./other/dexvert.js";
programs.dexvert = dexvert.create(programs.dexvert);
import {darktable_rs_identify} from "./meta/darktable_rs_identify.js";
programs.darktable_rs_identify = darktable_rs_identify.create(programs.darktable_rs_identify);
import {autoCropImage} from "./post/autoCropImage.js";
programs.autoCropImage = autoCropImage.create(programs.autoCropImage);
import {checkBytes} from "./detect/checkBytes.js";
programs.checkBytes = checkBytes.create(programs.checkBytes);
import {file} from "./detect/file.js";
programs.file = file.create(programs.file);
import {trid} from "./detect/trid.js";
programs.trid = trid.create(programs.trid);
import {dexmagic} from "./detect/dexmagic.js";
programs.dexmagic = dexmagic.create(programs.dexmagic);
import {svgInfo} from "./image/svgInfo.js";
programs.svgInfo = svgInfo.create(programs.svgInfo);
import {fifView} from "./image/fifView.js";
programs.fifView = fifView.create(programs.fifView);
import {convert} from "./image/convert.js";
programs.convert = convert.create(programs.convert);
import {graphicWorkshopProfessional} from "./image/graphicWorkshopProfessional.js";
programs.graphicWorkshopProfessional = graphicWorkshopProfessional.create(programs.graphicWorkshopProfessional);
import {scribus} from "./image/scribus.js";
programs.scribus = scribus.create(programs.scribus);
import {inkscape} from "./image/inkscape.js";
programs.inkscape = inkscape.create(programs.inkscape);
import {DR2DtoPS} from "./image/DR2DtoPS.js";
programs.DR2DtoPS = DR2DtoPS.create(programs.DR2DtoPS);
import {runvga} from "./image/runvga.js";
programs.runvga = runvga.create(programs.runvga);
import {draw256} from "./image/draw256.js";
programs.draw256 = draw256.create(programs.draw256);
import {imageAlchemy} from "./image/imageAlchemy.js";
programs.imageAlchemy = imageAlchemy.create(programs.imageAlchemy);
import {deark} from "./image/deark.js";
programs.deark = deark.create(programs.deark);
import {nconvert} from "./image/nconvert.js";
programs.nconvert = nconvert.create(programs.nconvert);
export {programs};
