#!/bin/sh
DENO_DIR=/mnt/compendium/.deno deno run --unstable --import-map /mnt/compendium/DevLab/deno/importMap.json --allow-read --allow-env --allow-net --allow-run /mnt/compendium/DevLab/dexvert/util/checkAbydosFormats.js "$@"
