#!/bin/sh
DENO_DIR=/mnt/compendium/.deno deno run --v8-flags=--max-old-space-size=32768,--enable-experimental-regexp-engine-on-excessive-backtracks --no-check --unstable --import-map /mnt/compendium/DevLab/deno/importMap.json --allow-read --allow-write --allow-env --allow-run /mnt/compendium/DevLab/dexvert/util/dexhealth.js "$@"
