export const WEAK_MAC_TYPE_CREATORS =
[
	// common mac type/creators
	"BTFL/pds ",		// AppleShare PDS
	"BTFL/ugbt",		// AppleShare PDS
	"dtpl/dcdc",		// DesktopPrinters DB
	"icon/MACS",		// Icon
	"FFIL/DMOV",		// TTF Font (usually)	(we don't match as a ttf.js because then we don't get the other data that's within the MacBinary font format)
	"FNDR/ERIK",		// Desktop
	"FOLD/MACS",		// OpenFolderListDF
	"rsrc/RSED",		// Resource Editor Resource
	
	// application specific
	"8BIF/8BIM",		// Adobe Photoshop Plugin/Pattern
	"Fltr/Clrs",		// ClarisWorks Translator
	"LINK/MSIE",		// MSIE Link/Shorcut
	"RIFF/FSX3",		// Painter
	"Xtra/Xown",		// Macromedia Director Xtra
	
	// fallthroughs
	"????/????",
	"□□□□/□□□□",

	// these are very generic and can't be acted on
	"BINA/mdos"
];

export const WEAK_PRODOS_TYPES =
[
	// these are very generic or system level stuff and are not useful to act on
	"BAT",		// [F5] User Defined 5
	"BIN",		// [06] Binary File
	"CFG",		// [5A] Configuration
	"DRV",		// [BB] Apple IIgs Device Driver
	"ENT",		// [5D] Entertainment
	"FND",		// [C9] Apple IIgs Finder Data
	"FST", 		// [BD] Apple IIgs File System Translator
	"FTD",		// [42] File Type Definitions
	"OVL",		// [F1] User Defined 1
	"LDF",		// [BC] Apple IIgs Generic Load File
	"P16",		// [F9] ProDOS-16 System File
	"PIF",		// [B6] Apple IIgs Permanent INIT
	"PRG",		// [F8] User Defined 8
	"SYS", 		// [FF] ProDOS-8 System File
	"TIF",		// [B7] Apple IIgs Temporary INIT
	"UD2",		// [F2] User Defined 2
	"UD4",		// [F4] User Defined 4
	"UNK",		// [00] Unknown
	"VAR"		// [FD] Applesoft BASIC Variables
];

export const WEAK_MAC_TYPES =
[
	// common Mac types
	"cdev",		// Control Panel
	"INIT",
	"thng"		// Extension (Component)
];

// these magics should be ignored in terms of reporting 'new magic' discoveries in things like dexrecurse, but are may be legitimate matches by various formats so should not explictly be marked as weak
export const IGNORE_MAGICS =
[
	// detectItEasy
	/^Archive: BAGF$/,
	/^Archive: SW/,	// These are paired with .idb files which we DO support

	// dexmagic
	/^Generic RIFF file /,

	// GT2
	/^DPA Archiv gefunden \(Auflistung ist deaktiviert\)$/,
	/^NSIS 1\.60-2\.0 Archiv gefunden \(Auflistung ist deaktiviert\)$/,		// The installer itself is properly extracted, but some sort of 'meta' file is left behind that is identifed as this, but it's always pretty small thus we just ignore it
	/^RIFF Datei: unbekannter Typ/,

	// file
	/^a .+ script text executable$/,
	/^Apple Driver Map/,
	/^IFF data, /,
	/^DBF,/,
	/^RIFF \((big|little)-endian\) data$/,
	/^text\/isl/,
	/^Unknown Corel\/Wordperfect product/
];

// These magics are untrustworthy and any detections against them should be noted as such
// Note: Some may not be especially weak, they may just be so application-specific that I didn't want to deal with them anymore as they wouldn't be useful to support. Probably should have created an ignored.js file for these, but too late now
export const WEAK_VALUES =
[
	// siegfried
	/^fmt\/(111|134|208|304|328|347|452|473|583|584|639|691|692|819|869|1029|1030|1031|1032|1033|1034|1035|1093|1113|1145|1241|1260|1276|1280|1381|1385|1461|1488|1489|1491|1555|1556|1562|1575|1616|1651|1672|1701|1702|1703|1704|1708|1740|1751|1812|1874|1902)( |$)/,
	/^x-fmt\/(8|10|53|101|157|168|195|324|342)( |$)/,

	// ancientID
	/^<invalid>$/,
	/^Vice: Huffman compressor with RLE$/,

	// binwalkID
	/^Base64 standard index table$/,
	/^Boot section Start/,
	/^Copyright string: /,
	/^CRC32 polynomial table/,
	/^DES PC\d table$/,
	/^ELF, 64-bit/,
	/^ESP Image \(ESP/,
	/^Executable script, /,
	/^IMG0 \(VxWorks\) header/,
	/^JBOOT STAG header/,
	/^LZ4 compressed data$/,
	/^Linux kernel version [\d.]+$/,
	/^MLD sequence date,$/,
	/^Neighborly text/,
	/^OGG audio data$/,
	/^QNX4 Boot Block$/,
	/^Ubiquiti firmware header/,
	/^Unix path: /,
	/^WMA audio data$/,
	/^ZBOOT firmware header/,

	// Detect-It-Easy
	/^Archive: André Osterhues's Code Compression Algorithm \(ACCA\.\)$/,
	/^Archive: DCL$/,
	/^Archive: INSA$/,
	/^Archive: Resources$/,
	/^Archive: Unity\/Unity Asset/,
	/^Archive: XFL game resource file/,
	/^Format: Amiga loadable file$/,
	/^Format: AutoIt$/,
	/^Format: Borland TLINK Symbol Table/,
	/^Format: COFF Library \(\.LIB\)/,
	/^Format: empty file$/,
	/^Format: Guitar Pro Tablature/,
	/^Format: JavaScript Compiled\/Bytenode/,
	/^Format: plain text/,
	/^Format: DBase Database \(\.DBF\)/,
	/^Format: Universal Binary$/,
	/^Installer: Adveractive/,
	/^Installer: InstallShield/,
	/^Installer: SQX Archive Installer/,

	// dexmagic
	/^Generic IFF FORM file /,
	/^IFF CAT file$/,
	/^Visual Novel DPK Archive$/,
	/^ZZT World$/,

	// disktype
	/^Amiga AFS file system Type "AFS\\0"$/,
	/^Amiga Kickstart disk Type "KICK"$/,
	/^Amiga Smart File System Type "SFS\\0"$/,
	/^Amiga type code /,
	/^Archive: C\(ompression\)KIT by Mad Man Software/,
	/^ATARI ST partition map/,
	/^bar archive$/,
	/Blank disk\/medium$/,
	/^compress-compressed data at /,
	/^FAT\d{2} file system/,
	/^FreeBSD boot (loader|manager)/,
	/^GRUB boot loader,/,
	/^ISOLINUX boot loader$/,
	/^MFS file system$/,
	/^Minix file system/,
	/^Old-style Apple partition map/,
	/^QNX4 file system$/,
	/^Solaris SPARC disklabel/,
	/^Statistica Cube LiesMich1/,
	/Volume size off the scale/,
	/^Windows \/ MS-DOS boot loader/,
	/^YZ Archiv gefunden/,

	// ffprobeID
	/^ADP \(adp\)$/,
	/^CD Graphics \(cdg\)$/,
	/^Digital Pictures SGA \(sga\)$/,
	/^DV \(Digital Video\) \(dv\)$/,
	/^Electronic Arts cdata \(ea_cdata\)$/,
	/^Electronic Arts Multimedia \(ea\)$/,
	/^Game Music Emu demuxer \(libgme\)$/,
	/^IFF \(Interchange File Format\) \(iff\)$/,
	/^image2 sequence \(image2\)$/,
	/^LOAS AudioSyncStream \(loas\)$/,
	/^LRC lyrics \(lrc\)$/,
	/^Macintosh HCOM \(hcom\)$/,
	/^MobiClip MOFLEX \(moflex\)$/,
	/^ModPlug demuxer \(libmodplug\)$/,
	/^MP2\/3 \(MPEG audio layer 2\/3\) \(mp3\)$/,
	/^MPlayer subtitles \(mpsub\)$/,
	/^NC camera feed \(nc\)$/,
	/^Nullsoft Streaming Video \(nsv\)$/,
	/^Ogg \(ogg\)$/,
	/^PJS \(Phoenix Japanimation Society\) subtitles \(pjs\)$/,
	/^piped tiff sequence (tiff_pipe)$/,
	/^QuickTime \/ MOV \(mov,mp4,m4a,3gp,3g2,mj2\)$/,
	/^raw (AC-4|AMR-[NW]B|dvdsub|E-AC-3|H\.26[13]|HEVC|lmlm4|MJPEG|MJPEG 2000|MPEG|MPEG-4|VC-1) (video )?\((ac4|amr[nw]b|dvdsub|eac3|h26[13]|hevc|lmlm4|m4v|mjpeg|mjpeg_2000|mpegvideo|vc1)\)$/,
	/^Sega DC STR \(dcstr\)$/,
	/^Sony Playstation STR \(psxstr\)$/,
	/^Tele-typewriter \(tty\)$/,
	/^THP \(thp\)$/,
	/^Tiertex Limited SEQ \(tiertexseq\)$/,
	/^Video CCTV DAT \(luodat\)$/,
	/^VPlayer subtitles \(vplayer\)$/,

	// GT2
	/^AMG Archiv gefunden \(Auflistung ist deaktiviert\)$/,
	/^ARM64EC COFF object/,
	/^BMF $\.F Bild/,
	/^Bitmap BildException/,
	/^Borland Object Datei/,
	/^BSA Archiv gefunden \(Auflistung ist deaktiviert\)$/,
	/^Cobol Daten Datei$/,	// It actually does seem to be correct, but it's not clear what metrics it's actually using and since I can't relly do anything with it anyways, just mark it weak
	/^Common Object File Format \(COFF\) i386/,
	/^Crypt! [v\d.]+/,
	/^Cube$/,
	/^Cygwin Symbolischer Link$/,
	/^DOS Ger.tetreiber/,
	/^ELI Archiv gefunden \(Auflistung ist deaktiviert\)$/,
	/^Eudora Werbungsdatei$/,
	/^Exception in der Quelldatei$/,
	/^Fehler beim/,
	/^FINISH Archiv gefunden \(Auflistung ist deaktiviert\)$/,
	/^FPK Pascal Object Datei$/,
	/^Fractal Extreme Filemdatei$/,
	/^Keine Datei gefunden/,
	/^Kopftext:/,
	/^Java Source Code$/,
	/^JPG Bild/,
	/^IBM Hilfedatei$/,
	/^Icon Datei/,
	/^ID3v[\d.]+ Tag/,
	/^IFF Datei/,
	/^INI Datei/,
	/^Lotus 123 Tabelle/,
	/^MAC Bilddatei/,
	/^Microsoft C\/C\+\+ Bibliothek$/,
	/^Microsoft Debug Information$/,
	/^Microsoft Source Referenz Datei \(SBR\)$/,
	/^Microsoft SQL Server Datenbank Datei$/,
	/^Microsoft Visual C\+\+ Hilfedatei$/,
	/^Modula Programm$/,
	/^MP3 TAG$/,
	/^MPEG \d layer/,
	/^MPEG Filem/,
	/^MPEG-4 Audio Datei/,
	/^PAR Archiv gefunden \(Auflistung ist deaktiviert\)$/,
	/^Pascal Bibliothek/,
	/^Pascal Funktion/,
	/^Pascal Prozedur/,
	/^Pascal Source Code/,
	/^PCX Bild/,
	/^PKCS #7 Zertifikat$/,
	/^Phar Lap \.EXP Datei$/,
	/^PHP Archiv gefunden \(Auflistung ist deaktiviert\)$/,
	/^POIFS Dokument/,
	/^RKive \(\d\) Archiv gefunden \(Auflistung ist deaktiviert\)$/,
	/^SBC Archiv gefunden \(Auflistung ist deaktiviert\)$/,
	/^Scheint eine GIF-Datei zu sein$/,
	/^Shell Skript:/,
	/^SZIP Archiv gefunden \(Auflistung ist deaktiviert\)$/,
	/^Unicode Textdatei/,
	/^Windows Maus Cursor Datei\/Works f.r DOS Datei/,
	/^Windows Verkn.*fungs Datei$/,
	/^Wordperfect <unbekannt>/,
	/^Wordperfect Block Datei/,
	/^Wordperfect Dokument Datei/,
	/^Wordperfect Makro Datei$/,

	// lsar
	/^Arc CBM$/,
	/^LZMA_Alone$/,
	/^Now Compress$/,
	/^Self-extracting ARC$/,
	/^Split file$/,
	/^ZipIt SEA$/,

	// pc98ripperID
	/^PC-98 ElfDOS$/,

	// xdgMime
	/^application\/its\+xml$/,
	/^application\/mathematica$/,
	/^application\/msword$/,
	/^application\/smil\+xml$/,
	/^application\/sparql-query$/,
	/^application\/vnd\.fastcopy-disk-image$/,
	/^application\/vnd\.framemaker$/,
	/^application\/vnd\.microsoft\.portable-executable$/,
	/^application\/vnd\.ms-excel$/,
	/^application\/vnd\.wordperfect$/,
	/^application\/x-atari-lynx-rom$/,
	/^application\/x-ccd$/,
	/^application\/x-daa$/,
	/^application\/x-dar$/,
	/^application\/x-dosexec$/,
	/^application\/x-executable$/,
	/^application\/x-font-sunos-news$/,
	/^application\/x-font-vfont$/,
	/^application\/x-gbi$/,
	/^application\/x-gdbm$/,
	/^application\/x-gtk-builder$/,
	/^application\/x-iff$/,
	/^application\/x-ips-patch$/,
	/^application\/x-lz4$/,
	/^application\/x-mozilla-bookmarks$/,
	/^application\/x-ms-ne-executable$/,
	/^application\/x-msdownload$/,
	/^application\/x-navi-animation$/,
	/^application\/x-object$/,
	/^application\/x-ole-storage$/,
	/^application\/x-sharedlib$/,
	/^application\/x-shellscript$/,
	/^application\/x-subrip$/,
	/^application\/x-wii-wad$/,
	/^application\/xhtml\+xml$/,	// only cheks for the top header which oddly is all that's in some text files out there that should remain as text
	/^audio\/vnd\.dts$/,
	/^audio\/x-mod$/,
	/^image\/x-3ds$/,
	/^image\/x-pic$/,
	/^image\/x-win-bitmap$/,
	/^text\/vnd\.graphviz$/,
	/^text\/x-csrc$/,
	/^text\/x-devicetree-source$/,
	/^text\/x-emacs-lisp$/,
	/^text\/x-makefile$/,
	/^text\/x-matlab$/,
	/^text\/x-microdvd$/,
	/^text\/x-modelica$/,
	/^text\/x-mpl2$/,
	/^text\/x-mpsub$/,
	/^text\/x-objcsrc$/,
	/^text\/x-patch$/,
	/^text\/x-qml$/,
	/^text\/x-systemd-unit$/,	// similar to INI but not the same as an INI (gets matched to INI anyways, but that's ok)
	/^text\/x-todo-txt$/,
	/^text\/x-vb$/,
	/^video\/dv$/,
	/^video\/mpeg$/,
	/^video\/x-flic$/,
	
	// FILE: Improper parsing of output or other file errors
	/^[\d."'\s)(-]+$/,
	/^' (123):$/,
	/^# define/,
	/^\.mp3$/,
	/^$/,	// eslint-disable-line no-control-regex
	/^/,	// eslint-disable-line no-control-regex
	/^ERROR: /,
	/^NTFS$/,
	/^Invalid name\.$/,
	/^P;/,

	// FILE: Very weak checks:
	/^, /,
	/^\(non-conforming\)$/,
	/^\) with pointer 0x[\da-f]+$/,
	/^0421 Alliant compact executable/,
	/^370 sysV/,
	/^370 XA sysV/,
	/^386 compact demand paged pure executable/,
	/^0420 Alliant virtual executable/,
	/^5View capture file/,
	/^64-bit XCOFF executable or object module/,
	/^68k Blit/,
	/^777 archive data/,
	/80386 COFF executable/,
	/^a\.out/,
	/^a .+script, /,
	/^a .*script executable/,
	/^ABComp archive data/,
	/^ACE\/gr ascii file/,
	/^Adobe PageMaker, (big|little)-endian, version [\d.]+$/,
	/^Adobe Photoshop, \d{5}/,
	/^Adobe Photoshop Color swatch/,
	/^AES with 256-bit key$/,
	/^AHX version/,
	/^AIN archive data$/,
	/^AIX compiled message catalog$/,
	/^ALAN game data/,
	/^Aldus PageMaker, /,
	/^Algol 68 source/,
	/^Alpha compressed COFF$/,
	/^Alpha u-code object$/,
	/^amd 29k /,
	/^Amiga Workbench$/,
	/^AmigaOS bitmap font/,
	/^Android ART profile$/,
	/^Android binary XML/,
	/^Android package resource table/,
	/^Apache Avro/,
	/^Apache Hadoop Sequence/,
	/^Apache Hive RC file/,
	/^Apache ORC/,
	/^Apache Parquet/,
	/^(apl|APL) workspace/,
	/^Apollo m68k COFF executable/,
	/^apollo a88k COFF executable/,
	/^Apollo DBF/,
	/^Apple DiskCopy 4.2 image/,
	/^Apple QuickTime$/,
	/^Apple QuickTime multiple URLs$/,
	/^Applesoft BASIC program data/,
	/^application\/(octet-stream|postscript|x-nextmail)((;(, (ASCII|ISO-8859) text)?$)|$)/,
	/^Applixware/,
	/^Arhangel archive data/,
	/^aria2 control file/,
	/^ARM COFF/,
	/^ARM Thumb COFF/,
	/^ARMv7 Thumb/,
	/^ARRI ARI image data/,
	/^ASD archive data/,
	/^ASF_Extended_Content_Description_Object$/,
	/^ASF_Stream_Bitrate_Properties_Object$/,
	/^Aster\*x/,
	/^Atari DEGAS/,
	/^Award BIOS Logo, \d+ x \d+/,
	/^ASCII font (bits|metrics)/,
	/^ASCII vfont/,
	/^assembler source/,
	/^b\.out/,
	/^Bagpipe$/,
	/^Bagpipe, /,
	/^BALANCE NS32000/,
	/^basic-16 executable/,
	/^Beetle VM object file$/,
	/ BCS executable/,
	/^Bentley\/Intergraph Microstation CAD cell library$/,
	/^BibTeX text file,/,
	/^BibTeX-file/,
	/^Bio-Rad \.PIC Image File/,
	/^BIOS \(ia32\) ROM Ext/,
	/^Biosig\/(Axona file format|GDF|EDF|Heka Patchmaster|IgorPro ITX|Plexon v1\.0)/,
	/^BLCR context data/,
	/^Blink archive data/,
	/^BOA archive data/,
	/^BS image/,
	/^BSD makefile script/,
	/^BSN archive data$/,
	/^BTS archive data$/,
	/^C64 PCLink Image$/,
	/^CAST5 \(128 bit key\)/,
	/^CBM BASIC, SYS/,
	/^CCP4 Electron Density Map/,
	/^CDC Codec archive data$/,
	/^Chiasmus key/,
	/^Citrus locale declaration/,
	/^Clarion Developer/,
	/^Claris works dictionary/,
	/^CLIPPER COFF executable/,
	/^Clipper SIX with memo/,
	/^Clojure module/,
	/^CMP archive data/,
	/^COFF DSP21k/,
	/^COFF format/,
	/^ColoRIX Slideshow$/,
	/^ColorSync color profile/,
	/^Commodore ((C16|C64|C128|VIC-20|PET|Plus4)\/?)+ .*program,/,
	/^Common Data Format \(Version 2\.5 or earlier\) data/,
	/^"compact bitmap" format \(Poskanzer\)$/,
	/^compacted data$/,
	/^Compiled 32-bit terminfo entry/,
	/^Compiled PSI/,
	/^Convex old-style/,
	/^Convex SOFF/,
	/^Corel Calendar data file/,
	/^Corel (DataPerfect|DrawPerfect|Printer|WordPerfect)( Office)?: Unknown filetype/,
	/^Corel loadable file/,
	/^Corel Macro editor macro/,
	/^Corel Terminal resource data/,
	/^Corel PlanPerfect macro/,
	/^Corel Presentation/,
	/^CPE executable/,
	/^CRAM version/,
	/^CRAM,/,
	/^Crush archive data/,
	/^cscope reference data/,
	/^(CSV )?((ISO-8859|Non-ISO extended-ASCII) text,? ?)+/,
	/^Cytovision FISH Probe file/,
	/^ctab data/,
	/^DataBaseContainer, no records/,
	/^DCL command file/,
	/^ddis\/ddif/,
	/^DER Encoded Certificate/,
	/^DEC SRC Virtual Paper Lectern file$/,
	/^DemoManiac Text$/,
	/^diff output/,
	/^dBase I[IV]I? DBT/,
	/^ddis\/dots archive/,
	/^ddis\/dtif table data/,
	/^DEC SRC Virtual Paper Lectern file/,
	/^Delta ISO data/,
	/^Delta RPM$/,
	/^DIF \(/,
	/^Disintegrator archive data/,
	/^disk quotas file/,
	/^DitPack archive data/,
	/^ditroff output/,
	/DIY-Thermocam raw data/,
	/^DOS .*backed up sequence/,
	/^DOS 2\.0 backup id file/,
	/^DOS [\d.]+ backup control file/,
	/^DPA archive data/,
	/^DRAGEN ORA file,/,
	/^DSF audio bitstream data/,
	/^DuckDB database file/,
	/^dump format, /,
	/^dump: (4\.1BSD|Convex Storage Manager)/,
	/^Dyalog APL/,
	/^Dzip archive data/,
	/^EBCDIC text/,
	/^EBU-STL subtitles/,
	/ECOFF executable/,
	/^EDID data/,
	/^EdLib, $/,
	/^eCos RTOS string reference/,
	/^ELI 5750 (compressed )?archive/,
	/^Encore( -)?$/,
	/^Encore - version/,
	/^Encore demand-paged executable/,
	/^Encore executable/,
	/^Encore pure executable/,
	/^Encore not stripped/,
	/^Encore unsupported executable/,
	/^EPOC\/Symbian exported MultiBitMap$/,
	/^Epson ESC\/Page language printer data$/,	// actually found these (LSxx_129) but kinda weak and not much we can do with em
	/^ERROR: \(null\)/,
	/^ESP archive data/,
	/^ESP Image segment/,
	/^ESP-IDF partition table entry/,
	/^executable \(RISC System\/6000/,
	/^exported SGML subdocument text$/,
	/^Ext3 external journal/,
	/^Ext3 file system Volume/,
	/^Extended display identification data dump/,
	/^Exuberant Ctags tag file/,
	/^FGDC-STD-001-1998$/,
	/^FIGlet controlfile/,
	/^firmware .*revision/,
	/^First Choice device file/,
	/^FIT image data/,
	/^FreeBSD\/i386/,
	/^FORTRAN program/,
	/^FoxBase\+\/Dbase III/,
	/^FreeDOS KEYBoard Layout/,
	/^fsav macro virus signatures/,
	/^Gather archive data/,
	/^GDSII Stream file/,
	/^gfxboot compiled html help/,
	/^Generic INItialization configuration/,
	/^GEM NOSIG/,
	/^GEOS VMFile/,
	/^GeoSwath RDF/,
	/^Git (blob|index|pack|tree)/,
	/^GKS Metafile/,
	/^GLF_BINARY_LSB_FIRST/,
	/^GLF_BINARY_MSB_FIRST/,
	/^GNU dbm .*database/,
	/^GPG encrypted data/,
	/^GTA (animation data|archive|audio index data|in-game|script)/,
	/^GTA1 /,
	/^GTA2 /,
	/^GRand Unified Bootloader/,
	/^Gringotts data file/,
	/^Group Policy Registry Policy/,
	/^((checksummed|hashed) )?Plaintext or unencrypted data$/,
	/^HIT archive data$/,
	/^Hitachi SH/,
	/^HTML document/,
	/^HP 48 binary/,
	/^HP text/,
	/^HPA archive data/,
	/^hp\d00/,
	/^HP s\d+ ((demand-load|relocatable|pure|old) )?executable/,
	/^HP NLS message catalog/,
	/^huf output/,
	/^HYP archive data/,
	/^i386 COFF object$/,
	/^i960 b\.out relocatable object/,
	/^iAPX 286 executable/,
	/^IBM OS\/400 save file data/,
	/^ICE authority data/,
	/^ID tags data/,
	/^IFF data$/,
	/^IFF data, at .*resource$/,
	/^IFF data, (Non-ISO )?(extended-ASCII|ASCII|ISO-8859) text/,
	/^Impulse Tracker Instrument/,
	/^Intel ia64 COFF/,
	/^Interleaf saved data$/,
	/^(AIX|Intel).* Common Object File Format/,
	/^IRIS Showcase file/,
	/^IRIS Showcase template/,
	/^ISO Media$/,
	/^ISO Media, ASCII text/,
	/jffs2 filesystem data/,
	/^Java JCE KeyStore/,
	/^Java.*KeyStore$/,
	/^Java serialization data/,
	/^JavaScript source, (ASCII|ISO-8859) text/,
	/^JPEG-XR$/,
	/^JSON data$/,
	/^JVT NAL sequence/,
	/^Kerberos Keytab file/,
	/^KiCad Footprint/,
	/^Kickstart disk/,
	/^LADS Caris Ascii Format/,
	/^LaTeX raw glossary/,
	/^LaTeX raw index file/,
	/^LaTeX sorted index/,
	/^lEEt\/OS Application$/,
	/^LFS filesystem image/,
	/^libfprint fingerprint data V\d/,
	/^lif file/,
	/^Linux LVM1 volume/,
	/^Linux-Dev86 executable, headerless/,
	/^(little|big) endian ispell/,
	/^LN03 output/,
	/^locale data table/,
	/^Logitech Compress archive data/,
	/^Lotus 1-2-3 unknown formatting data/,
	/^Lotus 1-2-3 CoNFiguration/,
	/^LX executable/,
	/^Lynx cartridge/,
	/^LZMA compressed data/,
	/^MacBinary, /,
	/^MacBinary.* INVALID date/,
	/^MacBinary II,/,
	/^Macintosh MFS data/,
	/^Mach-O (architecture|i\d86 object|universal binary)/,
	/^Mach-O m68k filetype=\d+/,
	/^magic text fragment/,
	/^mail forwarding/,
	/^Map file for the AssaultCube FPS game/,
	/^Map file for cube/,
	/^Maple help database$/,
	/^Maple something/,
	/^Maple worksheet, but weird/,
	/^Maple worksheet version/,
	/^Mathematica 3.0 notebook/,
	/^Matlab v(4|Mat)/,
	/^Matlab (vDIF|vis|vsta) mat-file/,
	/^MAR archive data$/,
	/^mc68k COFF/,
	/^mc68k executable/,
	/^mcrypt [\d .]*encrypted data/,
	/^MegaPaint (INF|POP|VIN|VPO)$/,	// these MegaPaint's are here instead of unsupported because the magic matches the extension, so weakMagic wouldn't ensure a non-match
	/^MegaPaint plug-in Module$/,
	/^MegaPaint symbols Library$/,
	/^message(, ASCII text)?$/,
	/^Message Sequence Chart \(chart\)/,
	/^Micro Focus File with Header/,
	/^Microsoft a\.out/,
	/^Microsoft HTML Help Project/,
	/^Microsoft Visual C\/OMF library$/,
	/^Microsoft Xbox 360 package/,
	/^Microsoft Xbox XPR0 texture$/,
	/^Mini DuMP crash report/,
	/^Minix filesystem/,
	/^Minix-386/,
	/^MIPSE[BL][ -]/,
	/^MIT scheme/,
	/^MMDF mailbox/,
	/^modulefile/,
	/^Motorola S-Record; binary data in text format/,
	/^MPEG ADTS, layer I(,|$)/,
	/^MPEG sequence$/,
	/^MPEG sequence, (H\.264 video|v4, simpl)/,
	/^MPEG sequence, (v4|Constrained|\d+ fps)$/,
	/^MPEG-4 LOAS/,
	/^MS, \d+ bytes$/,
	/^MS-DOS (CONFIG|MSDOS)\.SYS/,
	/^MS Windows 3.1 group files/,
	/^MS Windows COFF /,
	/^MS Windows y\.z/,
	/^MSVC \.ide$/,
	/^MSX BIOS\+BASIC/,
	/^MSX(-BASIC)? (extension )?ROM/,
	/^MSX-BASIC program/,
	/^MSX2\/2\+\/TR SubROM$/,
	/^MSXiE archive data/,
	/^mumps (avl|blt) global/,
	/^MySQL (ISAM|Maria) (compressed data|index) file Version [\d.-]+$/,
	/^MySQL table definition file Version 0/,
	/^MySQL table definition file.* type UNKNOWN, MySQL version 0/,
	/^MySQL replication log, server id 1, MySQL V3\.2\.3, server version 3\.23\.32-debug-log$/,
	/^National Instruments,/,
	/^NekoVM bytecode/,
	/^Netscape Communicator address book/,
	/^NetStumbler log file/,
	/^New Line Delimited JSON text data/,
	/^NeXT version 1 disklabel/,
	/^Nim source code/,
	/^Nintendo 3DS BCSTM audio file/,
	/^Nintendo Badge Arcade badge/,
	/^Nintendo DS MPEG Video$/,
	/^Nintendo Gameboy Music\/Audio Data/,
	/^Norton GHost image/,
	/^Novell LANalyzer capture file/,
	/^NSQ archive data/,
	/^o65 (executable|library|object)/,
	/^Oak Technologies printer stream/,
	/^Objective-C source/,
	/^Old EZD Electron Density Map$/,
	/^old Microsoft 8086 x\.out/,
	/^old packed data$/,
	/^old timezone data/,
	/^old-fs dump file/,
	/OpenFirmware FORTH Dictionary/,
	/^OpenPGP Public Key/,
	/^OpenPGP Secret Key/,
	/^OS\/2 Boot Manager/,
	/^OS\/2, hotspot/,
	/^OS9\/68K module$/,
	/^overlay object file/,
	/^PA-RISC\d/,
	/^PAK archive data$/,
	/^Palm OS operating system patch data/,
	/^Panorama database, /,
	/^PAQ archive data$/,
	/^Par archive data/,
	/^PARIX T\d+/,
	/^PARity archive data - Index file$/,
	/^PARity archive data - file number \d+$/,
	/^PBF image \(deflate compression\)/,
	/^PCP compiled namespace/,
	/^PCP Help/,
	/^PCX for Windows image data/,
	/^PCP memory mapped values/,
	/^PDP-11/,
	/^PE Unknown /,
	/^Perkin-Elmer executable/,
	/^perl Storable/,
	/^PEX Binary Archive/,
	/^PFS HDR image data/,
	/^PFT archive data/,
	/^PGP encrypted data/,
	/^PGP key security ring/,
	/^PGP Secret Sub-key/,
	/^PGP symmetric key encrypted data/,
	/^Picasso 64 Image$/,
	/Plan 9 executable/,
	/^PPMN archive data/,
	/^PRCS packaged project$/,
	/^Private key in DER format/,
	/^ps database/,
	/^Psion Series 5$/,
	/^Psion Series 5 (([Ee]xecutable)|(ini file)|(ROM multi-bitmap image)|(Sheet file)|(Sheet spreadsheet))$/,
	/^Psion Series 5 database Agenda file$/,
	/^(pure )?object file \(z8000 a\.out\)$/,
	/^pxelinux loader/,
	/^Python script/,
	/^QDOS object /,
	/^QL OS dump data/,
	/^QL plugin-ROM data/,
	/^Quake$/,
	/^QuArk archive data/,
	/^RAD Game Tools Smacker Multimedia/,
	/^RAGE Package Format/,
	/^Raspberry PI EEPROM/,
	/^raw G3/,
	/^raw modem data/,
	/^RCS\/CVS diff output/,
	/^RDI Acoustic Doppler Current Profiler/,
	/^REDCode Video/,
	/^Redis RDB file/,
	/^RenderWare collision data \(COL\)/,
	/^RenderWare data, v/,
	/^RISC OS Chunk data/,
	/^RISC OS music file/,
	/^RISC OS outline font data/,
	/^ROOT file/,
	/^Ruby script, ASCII text/,
	/^RST-format raster font data/,
	/(Samsung|Sega) Pico ROM image/,
	/^SAS$/,
	/^SAS 7\+/,
	/^SAS, /,
	/^SB[CX] archive data/,
	/^Sega FILM\/CPK Multimedia/,
	/^Sendmail frozen configuration/,
	/^separate object file/,
	/^Sequence Alignment\/Map \(SAM\)/,
	/^SHARC COFF binary/,
	/^Spectrum \+3 data - memory block$/,
	/^Spectrum \.SCL Betadisk image/,
	/^SHARC architecture file/,
	/^shared library$/,
	/^shared library, at/,
	/^shared library TTComp archive data/,
	/^SIMH tape data/,
	/^Sky archive data/,
	/^Solitaire Image Recorder format/,
	/^SoftQuad DESC or font file binary/,
	/^SoftQuad troff Context intermediate/,
	/^Software Tools format archive/,
	/^Sony PlayStation (Archive|Audio|PSX image)/,
	/^SPARC demand paged/,
	/^SPARC (pure )?executable(( not)? stripped)?$/,
	/^SPEC(, (ASCII|ISO-8859) text)?/,
	/^Spectrum \.TAP data/,
	/spot sensor temperature/,
	/^Squeak image data$/,
	/^Squeak program/,
	/^SysEx File/,
	/^standard input\/output character device driver/,
	/^StarOffice Gallery theme/,
	/^structured file$/,
	/^StuffIt Deluxe \(data\)/,
	/^StuffIt Deluxe Segment/,
	/^Sun disk label/,
	/^Surfer 6 binary grid file/,
	/^SVR2 executable/,
	/^SVR2 pure executable/,
	/^SVr\d curses screen image/,
	/^SYMMETRY i386/,
	/^system ID:/,
	/^TADS .*game data, at /,
	/^Tcl script/,
	/^Terse archive data$/,
	/^TeX font metric data/,
	/^TeX generic font data/,
	/^TransCopy disk image/,
	/^troff or preprocessor input/,
	/^TRK: \d+ /,
	/^Targa image data/,
	/^TOC sound file/,
	/^Tower\/XP rel/,
	/^Tower32/,
	/^TripleDES$/,
	/^Turbo Pascal TOUR data$/,
	/^UFA archive data/,
	/^Unicode text, SCSU/,
	/^Unicode text, UTF-32, (big|little-endian)/,
	/^unicos \(cray\) executable/,
	/^unified diff output/,
	/^Unix-like shebang/,
	/^unknown demand paged pure executable/,
	/^unknown readable demand paged pure executable/,
	/^v8 bytecode/,
	/^VAX COFF (pure )?executable/,
	/^VAX single precision APL workspace$/,
	/^VAX-order/,
	/^VBOX voice message data/,
	/^very short file/,
	/^very old \(C\/A\/T\) troff output data$/,
	/^VISX image file/,
	/^VISUAL OBJECTS,/,
	/^IDEA$/,
	/^WE32000 COFF/,
	/^WebAssembly \(wasm\)/,
	/^Windows boot log/,
	/^Windows Precompiled iNF/,
	/^Windows SYSTEM.INI/,
	/^Windows WIN.INI/,
	/^WinImage archive data/,
	/^WordPerfect block/,
	/^WWPack archive data/,
	/^X image$/,
	/^X-Post-It-Note/,
	/^x\.out (randomized )?archive/,
	/^X1 archive data/,
	/^X11 SNF font data/,
	/^XENIX 8086 relocatable/,
	/^x86 executable$/,
	/^x86 executable( \(TV\))?( not stripped)?/,
	/^x86 OpenFirmware FORTH Dictionary/,
	/^xBase \(0xa\)$/,
	/^xBase \(0xa\) .*no records/,
	/^xBase \([^)]+\) MDX/,
	/^xBase index/,
	/^xBase, root pointer/,
	/^XPAck archive data/,
	/^YAC archive data/,
	/^YAFFS filesystem root entry/,
	/^YARA 3\.x compiled rule set/,
	/^Zebra Metafile graphic/,
	/^Zope Object Database File Storage/,
	/^ZZip archive data/,

	// TRID: Checks just 1-3 bytes:
	/^1ST Word Plus Document$/,
	/^22DISK format Definition \(tokenized\)$/,
	/^3D-Calc spreadsheet$/,
	/^3M Printscape document \(v1\.x\)$/,
	/^5View capture/,
	/^777 compressed archive$/,
	/^7th Level game data$/,
	/^AAX compressed data$/,
	/^ABC notation \(old\)$/,
	/^Access Video$/,
	/^Adaptive Prediction Tree \(APT\) encoded bitmap$/,
	/^Adobe PRC 3D model$/,
	/^Advanced DB Master data/,
	/^Affix file$/,
	/^Agfa\/Matrix SCODL bitmap$/,
	/^Allways Font Library$/,
	/^Alpha Four data \(generic\)$/,
	/^AMI BIOS Energy Star logo bitmap$/,
	/^Amiga bitmap Font/,
	/^Animecha Animation Data$/,
	/^AngelCode Bitmap Font \(binary\)$/,
	/^Any Password data$/,
	/^APE ProSystem Atari 8-bit disk image/,
	/^ArcMac compressed archive$/,
	/^ARHANGEL compressed archive$/,
	/^ArtBorder data$/,
	/^Artweaver Document$/,
	/^Assault Wing Font$/,
	/^Atari Compressed Disk Communicator image$/,
	/^Atari XE Executable$/,
	/^ATF Texture$/,
	/^AutoDesk Revit Indexed Point Cloud$/,
	/^Award BIOS logo bitmap \(\d+x\d+\)/,
	/^AYFX Editor Bank$/,
	/^Axon Raw Format bitmap \(little endian\)$/,
	/^BALZ compressed data$/,
	/^Band-in-a-Box Song$/,
	/^Bcrypt Encrypted data$/,
	/^Beasts and Bumpkins game data archive$/,
	/^Bennet Yee's face format bitmap$/,
	/Berkeley vfont/,
	/^Big Crunch compressed file$/,
	/^Bio-Rad Image\(s\) bitmap$/,
	/^BIOS ROM Extension /,
	/^Binary NX Vibration data/,
	/^Bit Archiver compressed archive$/,
	/^BitKeeper history data$/,
	/^Borland Client Dataset data$/,
	/^BRender ASF$/,
	/^BSArc compressed archive$/,
	/^BSC ZX Spectrum tape data$/,
	/^BSP bitmap$/,
	/^C64 Hires bitmap$/,
	/^Cal3D Skeleton File$/,
	/^Calcomp raster bitmap$/,
	/^Cardwar Cards deck$/,
	/^CauseWay Compressor compressed data$/,
	/^CBI document$/,
	/^CDX Internet Archive index$/,
	/^Chasm CEL bitmap$/,
	/^CheeseCutter Tune$/,
	/^Chromadrome 2 game data archive/,
	/^Commodore 64 PCLINK container$/,
	/^Commodore .*BASIC .*program/,
	/^Compact compressed data/,
	/^Complete Statistica\(l\) System spreadsheet \(v5\)$/,
	/^Compressed VGM music$/,
	/^Compression KIT compressed C64 disk$/,
	/^Continuous Wave Accelerometry data$/,
	/^Corel Color Palette$/,
	/^Cosmigo Pro Motion SPRites sequence/,
	/^CP\/M 3 COM binary \(no RSX\)$/,
	/^Crosstalk Compiled script$/,
	/^Cubic Tiny XM module$/,
	/^CyberAIDS infected Apple 2 executable$/,
	/^Cybiko Picture bitmap$/,
	/^Dalet Sound format audio \(old\)$/,
	/^Dalet Volume info$/,
	/^[Dd]ar archive/,
	/^dBASE 5\.0 Multiple index$/,
	/^dBASE IV Multiple index$/,
	/^DEGAS low-res compressed bitmap$/,
	/^DEGAS med-res bitmap$/,
	/^DEGAS med-res compressed bitmap$/,
	/^DEGAS hi-res bitmap$/,
	/^DEGAS hi-res compressed bitmap$/,
	/^DeltaCad drawing$/,
	/^Denise Amiga Saved state \(generic\)$/,
	/^Dialogic VOX \(telephony\) encoded audio$/,
	/^DICOM medical imaging bitmap/,
	/^Digifont Outline Font Description$/,
	/^Digital Micrograph Script$/,
	/^Digital Video$/,
	/^DirectX compiled Pixel\/Vertex Shader object \(generic\)$/,
	/^Disk eXPress disk image \(v[012]\.x\)$/,
	/^DiskDupe 5\.12 disk image$/,
	/^DitPack compressed data$/,
	/^DIV Games Studio Palette$/,
	/^DIV Games Studio Map$/,
	/^Doobs database$/,
	/^Doodle bitmap$/,
	/^Drazpaint \(C64\) bitmap$/,
	/^Dr\. Halo Palette$/,
	/^Dr\. Halo IV Display driver$/,
	/^Dr\. Halo IV Locator driver$/,
	/^Dr\. Halo IV Printer driver$/,
	/^DRM Content Format - Separate delivery file \(generic\)$/,
	/^DURILCA compressed file$/,
	/^DVR-Studio stream$/,
	/^Dzip compressed archive/,
	/^eFax Document \(generic\)$/,
	/^Encrypted Windows App Package \(generic\)$/,
	/^Endnote Export Format$/,
	/^Error Code Modeler$/,
	/^eXtended Triton Format$/,
	/^F64 disk image$/,
	/^Face The Music Effect$/,
	/^Farandole Form 2\.0 Linear module$/,
	/^FDX68 disk image \(generic\)$/,
	/^FineCrypt encrypted \(v2\.0\)$/,
	/^FinePrint saved output$/,
	/^FL Studio Drum Patch \(generic\)$/,
	/^FL Studio DrumKit \(generic\)$/,
	/^Flexible Line Interpretation bitmap$/,
	/^Foenix eXecutable binary/,
	/^Fold\(ed\) compressed archive$/,
	/^FONTASY Preview$/,
	/^Footprint\/IBM Works Data Filer DataBase$/,
	/^FormWorx for DOS Foreign Language table$/,
	/^F\.R\.A\.C\. project$/,
	/^Freeze! compressed archive$/,
	/^Full Disk Image$/,
	/^GEM bitmap/,
	/^Generic INI configuration$/,
	/^Genecyst save state$/,
	/^Generator GNM output log \/ music$/,
	/^Genital Save state \(v1\.2\+\)$/,
	/^GEOS Revision$/,
	/^GFX9000 Movie Format$/,
	/^GIF bitmap \(generic\)$/,
	/^Gigatron Compiled Low-Level Language \(v1, with rem\)$/,
	/^Glest 3D model$/,
	/^GLF 3D Font File Format$/,
	/^GNU Info document/,
	/^GNU Privacy Guard public keyring \(generic\)$/,
	/^Graham Systems Disk Sqeezer disk image$/,
	/^GraphiCode Programmable Device Format$/,
	/^Hi-MD Minidisc ATRAC3\+ audio data container$/,
	/^HP Xine compressed$/,
	/^Hrust [12] packed/,
	/^Human Readable Archive$/,
	/^HyperBase data base$/,
	/^Install Creator (Pro )?project$/,
	/^interLaced eXtensible Trace/,
	/^Interpaint bitmap$/,
	/^InterWord document$/,
	/^Ipix Spherical Panorama$/,
	/^IPLAY Enterprise Video$/,
	/^ISIS sketch$/,
	/^ISO base media container$/,
	/^Janome NH10000 Sewing Machine Stitch$/,	// eslint-disable-line unicorn/better-regex
	/^Java serialized data$/,	// It's just 2 bytes and haven't been able to find a reliable way to convert into something else like JSON
	/^JCALG1 compressed data$/,
	/^JCL script \(with rem\)$/,
	/^JMP data table \(v5\)$/,
	/^Jovian Logic VI bitmap$/,
	/^Jupiter Ace snapshot$/,
	/^Koala Paint/,
	/^Korg SysEx preset command$/,
	/^KSS: Author presentation data$/,
	/^Kyocera PRESCRIBE printing language$/,
	/^Legend text$/,
	/^Leonard Guides compiled data$/,
	/^Lepton bitmap/,
	/^Lepton UJG bitmap$/,
	/^LinkWay data$/,
	/^LLVM Bitcode \(generic\)$/,
	/^LMMS Project Zipped$/,
	/^Lotus Manuscript bitmap$/,
	/^LTAC compressed audio/,
	/^LTP Nuclear ZX tape image$/,
	/^LogicWorks circuit/,
	/^Lucid 3-D Macro$/,
	/^Luxor ABC80 tokenized BASIC source$/,
	/^LZMA compressed archive$/,
	/^LZW compressed data$/,
	/^Macromedia Flash SWF\/Scaleform GFX Video \(uncompressed\)$/,
	/^Maddox Games data archive$/,
	/^Mallard BASIC/,
	/^Maple Common Binary file \(generic\)$/,
	/^Marc's Disk Cruncher compressed disk image \(old\)$/,
	/^Master Boot Record dump$/,
	/^Max Payne data file$/,
	/^Macadam Bumper pinball$/,
	/^mcrypt encrypted/,
	/^MegaZeux world data/,
	/^Melco embroidery design$/,
	/^Microsoft Help \(old\)$/,
	/^Microsoft p-code$/,
	/^Microsoft Web query$/,
	/^Microsoft\(\/MSN\) MARC archive$/,
	/^Mini Office II SpreadSheet$/,
	/^miniSlowo document$/,
	/^MosASCII Project Workspace$/,
	/^Mozart functor$/,
	/^MP3 audio/,
	/^MS Age of Empires II: The Conquerors Expansion v1\.0 Saved Game$/,
	/^MSX BASIC tokenized source$/,
	/^MSX ROM Image$/,
	/^MSX2 ROM Image$/,
	/^MultiExpress Data and Fax Cover$/,
	/^MUX video$/,
	/^MyLittleBase database$/,
	/^Mythos Software LIB game data container$/,
	/^NEC JIS encoded file$/,
	/^NeoC Explorer train \/ input patterns$/,
	/^NEW-DOS COMPRESS compressed data$/,
	/^Nice-Install Data$/,
	/^Nokia 3D Map$/,
	/^Nokia Logo Manager bitmap$/,
	/^null bytes$/,
	/^Oberon V4 Symbol data$/,
	/^OCAD map$/,
	/^OMF - Relocatable Object Module Format$/,
	/^Open Access III Data base$/,
	/^openCanvas bitmap$/,
	/^OpenStreetMap Binary map data$/,
	/^Organize! Environment$/,
	/^Orao Tape image$/,
	/^Oric Raw Tape format$/,
	/^Ortho 3D Model$/,
	/^OS\/2 Bitmap Graphics Array \(generic\)$/,
	/^PA-RISC .*/,
	/^Pack compressed data/,
	/^packMP3 compressed MP3 audio$/,
	/^packPNM compressed /,
	/^PaintShow Font$/,
	/^Pajamas Adventure System bitmap$/,
	/^Panasonic JR Cassette image$/,
	/^PAR compressed archive$/,
	/^PAX password protected bitmap$/,
	/^PC9801 rip$/,
	/^PCE Sector Image disk image$/,
	/^PCX bitmap/,
	/^PEA compressed archive/,
	/^Pervasive Btrieve \(generic\)$/,
	/^Pfaff Compatible design card$/,
	/^PGN \(Portable Gaming Notation\) Compressed format$/,
	/^Philips Respironics M-Series data format$/,
	/^Photono-Software Stealther Skin$/,
	/^Pixel image$/,
	/^PKCS #7 Signature/,
	/^PlayStation Patch File/,
	/^Playstation Portable Texture$/,
	/^Pokemon Randomization Quick Settings$/,
	/^Polychrome Recursive Format bitmap$/,
	/^Portable Float Map grayscale bitmap$/,
	/^PR archiving tool archive$/,
	/^Pretty Good Privacy \(PGP\) Private\/Secret Keyring/,
	/^PreTracker module$/,
	/^PrintFox\/Pagefox bitmap/,
	/^ProHance Mouse Keys Definition table/,
	/^Project Dogwaffle animation \(generic\)$/,
	/^Protocol Data Unit message data$/,
	/^Psion Organiser Pack image$/,
	/^Python Pickle serialized data/,
	/^QDOS executable/,
	/^Qmage encoded data$/,
	/^Quarterback backup$/,
	/^Quarterdeck Mosaic History$/,
	/^Quick Help$/,
	/^RASTER Music Tracker Instrument$/,
	/^raw Group 3 FAX bitmap$/,
	/^RealFlight Radio Control Flying Site - Airport$/,
	/^RefPack compressed data$/,
	/^Rigol waveform$/,
	/^RPG Maker data$/,
	/^RR compressed data archive$/,
	/^Scamper WARTS storage$/,
	/^SCCS v4 archive data$/,
	/^SciADV MPK game data Package$/,
	/^Scitex Continuous Tone bitmap$/,
	/^SCODL image$/,
	/^ScreenBuilder image$/,
	/^Scribble! document$/,
	/^Shannara video\/animation$/,
	/^SID-Wizard Instrument$/,
	/^Siemens archived SMS messages$/,
	/^Silicon Graphics Object$/,
	/^Siva archive/,
	/^SLZ compressed data$/,
	/^SMS Material$/,
	/^Solace ENTER hex format \(abbreviated\)$/,
	/^Source Code Control System history data$/,
	/^Sound Club 2 sound bank$/,
	/^Space Quest V Font$/,
	/^Spectrum 512 Anispec animation$/,
	/^Spectrum emulator snapshot$/,
	/^SpeedScript document \(C64\)$/,
	/^Sprint User Interface$/,
	/^SPU Playstation log rip$/,
	/^Spybot-S&D "malware" informations$/,
	/^Spycraft: The Great Game Animation data$/,
	/^SQ2 compressed data$/,
	/^SQLite Zipvfs compressed database$/,
	/^Stata Data format /,
	/^Studio Folio Corsage game data archive$/,
	/^Stunt Island Resource$/,
	/^SubRip subtitles$/,
	/^Superbase Query definition$/,
	/^SuperCard Pro flux image$/,
	/^Taxman's Retro Engine v5 Configuration$/,
	/^Telltale Games Font \(VSM\)$/,
	/^TERSE compressed data \(S?PACK, [UV]\)$/,
	/^Text - UTF-(16|32)/,
	/^TextEngine document \(generic\)$/,
	/^That's Write document$/,
	/^The Apprentice: Los Angeles game data Archive$/,
	/^The Bee Archiver compressed archive$/,
	/^The Incredible Machine puzzle/,
	/^TheC64 Config\/Joystick\/Mode settings/,
	/^THOR compressed data$/,
	/^Tiny Tafel format$/,
	/^Topcon CL3 point cloud data$/,
	/^Total Annihilation saved game$/,
	/^TouchDesigner Environment\/project$/,
	/^Trilo ?Tracker (chiptune|Macro|Sample)$/,
	/^TRS-80 Level II BASIC tokenized source$/,
	/^TRSI Sound Monitor song$/,
	/^TTA True Audio lossless compressed audio$/,
	/^TTComp archive/,
	/^tzip compressed file$/,
	/^V9990 font format$/,
	/^VariCAD Drawing \(generic\)$/,
	/^VersaCAD Shade \(MS-DOS\)$/,
	/^VGAPaint 386 module$/,
	/^Videoscape GEO mesh/,
	/^VisiCalc spreadsheet$/,
	/^WGT Map \(v[2-5](\.\d)?\)$/,
	/^WhatsApp encrypted database$/,
	/^White Wolf Productions game data/,
	/^WillDraw Drawing$/,
	/^WinArcadia Saved State$/,
	/^WinArchiver Mountable compressed Archive$/,
	/^WinDraw Library$/,
	/^Windows Bitmap$/,
	/^WinPlot data/,
	/^WLF WolfMAME recording info$/,
	/^WordPerfect document \(Amiga\)$/,
	/^Wyse WY-60 soft font$/,
	/^X1 compressed archive$/,
	/^XBase DataBase \(generic\)$/,
	/^Xexor disk image$/,
	/^XMash compressed disk image$/,
	/^Yamazaki Zipper compressed archive$/,
	/^Z-Artist Picture bitmap$/,
	/^Z-Code V\d adventure for Infocom Z-Machine$/,
	/^Zoo filter compressed format$/,
	/^Zpng bitmap$/,
	/^ZSNES movie capture$/,
	/^ZX Microdrive cartridge image$/,
	
	// TRID: Checks for almost all zeroes or repeating values/patterns:
	/^\.NET binary serialized data$/,
	/^3D Studio Shape$/,
	/^A-Robots Fighting Robot Object$/,
	/^Acorn RISC OS font/,
	/^AdLib Timbre Bank Format$/,
	/^Adobe PhotoShop Brush$/,
	/^ADPCM \(\?\) compressed file recorded by some MP3 Players\/Voice recorders$/,
	/^Aquarius Cassette tape image$/,
	/^AS-EASY-AS Worksheet \(generic\)$/,
	/^Atari NeoChrome bitmap$/,
	/^AudioZip encoded audio$/,
	/^BackupExpress Pro$/,
	/^bCAD Drawing$/,
	/^BS-DOS MB-0\d disk image$/,
	/^Cadwork 2D Catalog$/,
	/^CAJ database$/,
	/^Cat Daddy Games game data archive$/,
	/^ChemDraw model$/,
	/^Chompsters level data$/,
	/^Coordinate 3D \(subset of ADTech File Format\) file \(more generic\)$/,
	/^CP\/M HUF compressed archive$/,
	/^CP\/M non-bootable disk image$/,
	/^Creative C\/MS packed screen$/,
	/^Cydonia game data$/,
	/^Digital Micrograph DM\d format \(BE\/Mac\)$/,
	/^DOS 2\.0-3\.2 Backup control info/,
	/^Dr\. Halo Font$/,
	/^Dyalog APL transfer$/,
	/^Darkmere game data$/,
	/^EndNote Style \(v3\)$/,
	/^Epic Pinball table data$/,
	/^EPOC Data \(gen\)$/,
	/^EPOC data store/,
	/^EstImage DataBase$/,
	/^exp\/Dos Expanded embroidery format$/,
	/^FarCry \(demo\) saved game$/,
	/^FastCopy DIM disk image$/,
	/^FastDir-like quick directory lookup data$/,
	/^File List Creator list$/,
	/^Final Data r\d data$/,
	/^FlashFloppy Quick Disk image$/,
	/^FleetStreet Installation archive$/,
	/^Form Memo MS Visual FoxPro 7$/,
	/^ForthCMP compiled 16bit executable$/,
	/^FoxGraph Data$/,
	/^Generic RIFF container$/,
	/^GnomeVFS$/,
	/^Gravis UltraSound PnP InterWave patch$/,
	/^HandStory eBook$/,
	/^Harvard Graphics [Pp]resentation \(v[^)]+\)/,
	/^Harvard Total Project Manager Calendar \(v1\)$/,
	/^Hex Edit Macro$/,
	/^HomeLab\/BraiLab Tape image$/,
	/^HP Logical Interchange Format disk image$/,
	/^HP200LX System Application's Help$/,
	/^IBM DisplayWrite 3\.0 document$/,
	/^Id Software Quake II Cinematic video$/,
	/^IDL binary format save file$/,
	/^Immaginaria TNG 3D scene$/,
	/^Indiana Jones and the Infernal Machine Game data archive$/,
	/^Install Maker( Pro)? project$/,
	/^Intel CPU Microcode$/,
	/^Inset PIX bitmap$/,
	/^JEDMICS C4 \(var 1\)$/,
	/^JOC Screen Designer screen$/,
	/^KeyCAD drawing \(v1\.x\)$/,
	/^Kidproof settings \(v1\.0\)$/,
	/^KT-Tech compressed audio$/,
	/^Lombard RAC Rally Track$/,
	/^Lotus 123 configuration/,
	/^Lotus 123\/Symphony worksheet\/format\/configuration \(V1-V2\)$/,
	/^Luigi's Mansion 3D model$/,
	/^M99 compressed data$/,
	/^MacBinary [12]$/,
	/^Macromedia Extension Package$/,
	/^MakerBot 3D print format$/,
	/^MapInfo MapBasic tabular DataBase$/,
	/^Matlab Level 4 MAT-File \(big-endian\)$/,
	/^Microsoft Works for Mac document \(v1\.0\)$/,
	/^Memo File Apollo Database Engine$/,
	/^MICROCAD Drawing$/,
	/^Music Craft Score$/,
	/^MusicMaker Song Data$/,
	/^MS 2\.5 module$/,
	/^MSX sound performance system Player XPL-A song$/,
	/^MSX-DOS disk Image$/,	// Found 1 of these in the wild, but the extension is not reliable and it's only checking 3 generic bytes
	/^NIfTI-2 data format/,
	/^NK - BMP\/TV lossless compressed bitmap$/,
	/^Open Minecraft Note Block Studio Song/,
	/^OS\/2 Dynamic Link Library \(no DOS stub\)$/,
	/^OziExplorer Map$/,
	/^PACKER compressed archive$/,
	/^Palantir WinTime Plan$/,
	/^Palm Address Book$/,
	/^Particles format \(little-endian\)$/,
	/^Paul Robotham Music$/,
	/^Pegasus SPS encoded audio$/,
	/^PERQ disk image$/,
	/^Photoshop Action$/,
	/^PlayStation Hierarchical 3D Model Data$/,
	/^PlayStation high-speed 3D modeling data$/,
	/^PlayStation raw save$/,
	/^PM XV bitmap/,
	/^Pro Pixel Demo Image$/,
	/^Project64 Memory Pack$/,
	/^PSX TMD 3d Model$/,
	/^QLAY MDV image$/,
	/^Quarterdeck Installation Package$/,
	/^Quesant AFM data$/,
	/^S2 Engine Animation$/,
	/^Sierra AGI music format$/,
	/^Sierra patch$/,
	/^Smart Game Format$/,
	/^Source Insight Custom Language File$/,
	/^Speccy snapshot$/,
	/^Stunt Island Resource \(generic\)$/,
	/^Sybase iAnywhere database files$/,
	/^Table Apollo \(DBF\) Database Engine$/,
	/^Take Command: 2nd Manassas game data archive$/,
	/^TERSE compressed archive$/,
	/^TeX Font Metric \(0x1[12]\)$/,
	/^Text - SCSU encoded$/,
	/^Text - UTF-32 \(BE\) encoded$/,
	/^Torque Dynamix Three Space model/,
	/^TrendMicro AntiVirus database$/,
	/^Turbo Pascal Map/,
	/^UbiArt Framework Cooked Asset$/,
	/^Ulead color Map$/,	// Often matches to this are correct, but it's not a useful file
	/^UMV Video$/,
	/^V-Ray Material \(binary\)$/,
	/^VersaCAD 3D drawing \(MS-DOS\)$/,
	/^Videoton TV-Computer tape image$/,
	/^Virtual MC-10\/Alice tape image$/,
	/^Visi On Overlay$/,
	/^VXD Driver$/,
	/^VZ200\/300 image \(type F1\)$/,
	/^Warajevo Tape image format$/,
	/^Warcraft game data archive$/,
	/^Win 3\.x Installed TrueType Font$/,
	/^Windows Device Dependent Bitmap$/,
	/^Windows Font$/,
	/^Windows Jump List$/,
	/^Windows Icon/,
	/^Windows Virtual Device Driver$/,
	/^WinPharoah Filter$/,
	/^Xerox EDMICS-MMR bitmap$/,
	/^YAS serialized data \(binary\)$/,
	/^ZealFS disk image$/,

	// TRID: Weak in some other way, such as commonly used word prefix/global/chars string or ascending/descending bytes
	/^3D texture$/,
	/^4th Dimension database$/,
	/^7DTD player Map$/,
	/^A-10 Tank Killer game data archive$/,
	/^Aard Dictionary$/,
	/^Abacus spreadsheet$/,
	/^Ability document$/,
	/^Abomination: The Nemesis Project game data archive$/,
	/^Adorage scene$/,
	/^AceMoney data$/,
	/^ACID Pro project$/,
	/^Actor Windows Description Language/,
	/^ADEX bitmap$/,
	/^ADFS disk image$/,
	/^Adobe FilmStrip$/,
	/^Aegis Draw plotter definition$/,
	/^Aegis ProMotion\/Videoscape 3D Camera$/,
	/^Aegis Videoscape 3D (Motion|Set)$/,
	/^Agon MOS executable$/,
	/^AIMP Skin \(v2\)$/,
	/^Akai MESA program$/,
	/^Aksharamala Keymap Binary$/,
	/^Aleph One Marathon Markup Language$/,
	/^Aladdin 4D MTR$/,
	/^AMAS Sequence$/,
	/^Amazon Kindle Update Package$/,
	/^Ambisonic B-Format audio$/,
	/^Amiga Action Replay Freezed snapshot$/,
	/^Amiga Disk image File \(generic\)$/,
	/^Amiga PACK_scn1\.library compressed data$/,
	/^Amiga PackDisk compressed disk image$/,
	/^AmigaKonto account$/,
	/^AMOD format module$/,
	/^Amulets and Armor Map$/,
	/^AMX Mod X plugin$/,
	/^Anachronox game data archive$/,
	/^Ancestral Quest family tree database \(zipped\)$/,
	/^AOS File Format$/,
	/^Apocalyptica game data archive$/,
	/^Apricot Character set$/,
	/^Aqualead LZSS compressed game data$/,
	/^Aquaplus P\/ECE Executable$/,
	/^Arc System Works game data package$/,
	/^ArcD compressed data$/,
	/^ArcView Legend$/,
	/^Arena container$/,
	/^Arkos Generic Z80 binary song$/,
	/^Arkos Tracker binary music \(v1\.0\)$/,
	/^ArtCAM 3D Relief model$/,
	/^Artemis Presents! document \(v2\.0\)$/,
	/^Artificial Intelligence Markup Language$/,
	/^asciicast \(v2\)$/,
	/^ASCII Encoded HP 48 Object$/,
	/^ASCII Test Data Format$/,
	/^Atari cartridge memory image$/,
	/^Attack of the PETSCII Robots Amiga module$/,
	/^Attribute-Relation File Format$/,
	/^Audio Disk Jockey (bank|session)$/,
	/^AWE Productions game data$/,
	/^AX-SHELL Group$/,
	/^Axon Raw Format bitmap \(big endian\)$/,
	/^Axon Text File format$/,
	/^Balance of Power: The 1990 Ed\. saved game$/,
	/^Beetris high scores$/,	// Other files use the same magic from this publisher
	/^Berkeley Logic Interchange Format$/,
	/^Better Working Eight-In-One Document$/,
	/^BGA compressed archive \(Gzip\)$/,
	/^BibTeX references$/,
	/^Big Mutha Truckers 2 game data Archive$/,
	/^binpatch format$/,
	/^BioForge IFF objects$/,	// Found these, but it's just for a game, so mark as weak as it's kinda weak
	/^BIS Binarized Rtm animation$/,
	/^BitCom Emulation settings$/,
	/^BlueEyes Animation$/,
	/^Borland Reflex Screen driver$/,
	/^Buzzwords On-Line Manual Program Text\/topic$/,
	/^Carrara Environment$/,
	/^Cavewars sprite$/,
	/^Chain format$/,
	/^Chasys Draw IES convolution Matrix$/,
	/^Chasys Draw IES Gradient$/,
	/^Chasys Draw IES metadata$/,
	/^Chessmaster Opening Book$/,
	/^Cisco IOS mzip compressed data$/,
	/^Clangd Index$/,
	/^ClariSSA internal edit format$/,
	/^CloudCompare BIN V2 format$/,
	/^CMU format - Andrew Toolkit$/,
	/^Compact Font Format$/,
	/^CompDisk compressed disk image$/,
	/^ColdFusion Component \(with rem\)$/,
	/^Colin McRae Rally 2 game data archive$/,
	/^Colossal Raw asset Package$/,
	/^COM\+ catalog file$/,	// Most matches to this are probably correct, but it's a near worthless file so just ignore it
	/^Compressed Alignment format$/,
	/^Compressed File Library 3 compressed data$/,
	/^context diff output/,
	/^Cookeo recipe$/,
	/^Copper Colourz! File$/,	// Found correct matches, but magic 'CCF' (and string 'CCF FILE') are too generic given that the extension is .ccf
	/^CryEngine Project \(generic\)$/,
	/^Cryptx encrypted data$/,
	/^Crystal Dynamics game data archive$/,
	/^CT Special Forces: Fire for effect Saved game$/,
	/^Cyberboard Gamebox$/,
	/^Cydonia game video format$/,
	/^Dagor Engine game data archive$/,
	/^Dan Bricklin's Demo/,
	/^Dance With Intensity song$/,
	/^Dave 2 Huffman compressed game data$/,
	/^DEB build rules$/,
	/^Delphi project Options$/,
	/^Delusion samples library$/,
	/^Deluxe Paint for IBM PC color font$/,
	/^Destruction Derby game data$/,	// Actually found matches that were correct, but the id just arters with "PACKED" which is way too weak to match, even with an extension since it just uses .000 and .RAW
	/^Diagram-Master Diagram$/,
	/^Die Total Verruckte Rallye game data$/,
	/^Digita Organiser text$/,
	/^Digitals\/Delta Map$/,
	/^DirectShow filter$/,
	/^Dired ls-like directory listing/,
	/^Dirk Bialluch TPU samples$/,
	/^Dis bytecode \(not signed\)$/,
	/^Disk Imploder compressed disk image$/,
	/^Disney Animation Studio eXposure Sheet$/,
	/^DKS subtitles$/,
	/^Dockerfile$/,
	/^Doge Serialized Object Notation$/,
	/^Dore Raster bitmap \(with rem\)$/,
	/^Dragon Age: Origins game data$/,
	/^Drive SnapShot Disk Image$/,
	/^DTS encoded audio/,
	/^DuckDB database$/,
	/^DNG Camera Profile \((big|little)-endian\)$/,
	/^DVD-Audio Audio Object$/,
	/^Dynamix Music data container$/,
	/^Dynamix Screen data container$/,
	/^EarthSiege 1\/2 game data archive$/,
	/^EA Seattle game data \(UNCS\)$/,
	/^EASE data \(generic\)$/,
	/^Easy Reading Electronic Book format content$/,
	/^EbSynth project$/,
	/^ED editor Keys definitions$/,
	/^EGS-SpectraPaint palette$/,
	/^EISA add-on card Configuration \(with (CR|rem)\)$/,
	/^Eldritch Config data$/,
	/^Eldritch Packed game data$/,
	/^Electronic Arts audio Bank$/,
	/^Emacs Muse project$/,
	/^Encrypted Blender 3D data$/,
	/^Encrypted Multi-Picture Object bitmap$/,
	/^EngineX Sound effects$/,
	/^ENVI n-D visualizer state$/,
	/^EPOC\/Psion Sheet spreadsheet$/,
	/^Espanso Package \(with rem\)$/,
	/^Esri grid \(ASCII\)$/,
	/^Eudora Address Book$/,
	/^EVE Online data \(generic\)$/,
	/^Faery Tale Adventure 2 Resources$/,
	/^FairyGUI game data archive$/,
	/^Falcon Sequence \(old\)$/,
	/^FAR TC\.Packer PlugIn$/,
	/^FCE Ultra FC0 savestate$/,
	/^FGT virus infected 16-bit COM executable$/,
	/^Fibonacci crunched data$/,
	/^File-Type Image$/,
	/^FileGateway Server configuration$/,
	/^Fine Artist Chunked format/,
	/^FireDAC database$/,
	/^Flash Shared Object file$/,
	/^foobar2000 component$/,
	/^FSEvents Disk Log Stream format \(v1\)$/,
	/^Foundation Stack$/,
	/^Fountain Script$/,
	/^Fox Engine DeForm$/,
	/^Furnace Instrument \(new\)$/,
	/^Game Boy Advance ROM$/,
	/^Game Music$/,
	/^Garry's Mod Addon$/,
	/^Gazebo model Configuration$/,
	/^GEM Application \(Intel\)$/,
	/^Generic IFF container$/,
	/^Gerber format$/,
	/^GetRight Skin$/,
	/^GFA Raytrace (compressed )?(Animation|image|project data) \((low|hi)-res\)$/,
	/^Gigatron Compiled Low-Level Language \(v2, with rem\)$/,
	/^git index$/,
	/^GoBe Productive Document \(gen\)$/,
	/^Grand Theft Auto 3 collision data$/,
	/^Grand Theft Auto: San Andreas game data archive$/,
	/^Groupwise Mail Message$/,
	/^GtkSourceView language definition$/,
	/^Guitar Pro 6 tablature \(non compressed\)$/,
	/^Haines NFF scene/,
	/^Harvard Graphics Symbols \(v2\.x\)$/,
	/^Headspace Inter-Platform File Format \(v1\)$/,
	/^HS2 zipped bitmap\(s\) archive$/,
	/^HTTP Archive format$/,
	/^Hugin Project$/,
	/^IFF Color Map$/,	// Just because it has a CMAP as the first entry, doesn't mean that's what this file is, it's often a Movie Setter file with FACE and BODY elements. If it is a CMAP, IFF ILBM ends up handling it and creates a png
	/^IFF document storage$/,
	/^IFC-ZIP$/,
	/^iGO Digital Elevation Map$/,
	/^IGOR Pro Text document$/,
	/^Imageworks 1D LUT format$/,
	/^Imagine for DOS Effect$/,
	/^iMON Setting file$/,
	/^Incredimail Letter creator project$/,
	/^Inno Setup Script \(with alt rem\)$/,
	/^Instalit Library$/,
	/^Instant Replay Data File$/,
	/^Intel HEX data, record type: data$/,
	/^JB BAHN layout$/,
	/^JEDMICS C4 \(var 2\)$/,
	/^Jeppesen\/Mentor FliteLog Log$/,
	/^jetAudio skin$/,
	/^JETPilot bitmap$/,
	/^JPC snapsot$/,
	/^JSON Entity Model$/,
	/^Kaitai Struct language \(with rem\)$/,
	/^Karl Morton (Music|Sound) format$/,
	/^Kelly Slater's Pro Surfer textures$/,
	/^Kingsoft WPS Office document \(alt\.\)$/,
	/^Korg Trinity\/Triton instruments bank \(generic\)$/,
	/^Land Of Legends game data archive$/,
	/^LEADTOOLS ABC bitmap$/,
	/^Lego Digital Designer data$/,
	/^LEGO Mindstorms EV3 brick executable code$/,
	/^LEN Exchange Format$/,
	/^Lexicon Interchange FormaT$/,
	/^LibGDX 3d model$/,
	/^Lightscape Radiosity$/,
	/^LightWave Envelope data$/,	// Found files that ARE this format, but with no extension and the magic is pretty weak otherwise
	/^LightWave Motion data$/,
	/^Litestep theme$/,
	/^Mac font$/,
	/^Mac ICOL colors LUT$/,
	/^Mac OS X Universal Binary \(generic\)$/,
	/^Macromedia Director Java Resource - Video$/,
	/^Magic and Mayhem sprites$/,
	/^MAGIX music studio (Drum kit|Window layout)$/,	// So these have weak magics, and their extensions are very close to the magic, so it could have mis-identifications so just skip it since there isn't much we can do with them anyways
	/^Maker Interchange Format Book$/,
	/^MAME plugin config$/,
	/^MAME TACO tape image$/,
	/^MapInfo Sea Chart$/,
	/^Mariner Write Document$/,
	/^MasterSound sequence$/,
	/^Mathematical Markup Language$/,
	/^Mathematical Programming System format$/,
	/^Mech Commander game data archive$/,
	/^Mechwarrior FIT data$/,
	/^MegaCAD Project$/,
	/^MegaZeux game$/,
	/^MetaQuote \/ MetaTrader indicator$/,
	/^MetaQuotes Language 5 compiled program$/,
	/^MG!2 compressed$/,
	/^Microbee tape image$/,
	/^Microsoft Help compiler Project \(with rem\)$/,
	/^Microsoft resource data \(old\)$/,
	/^Microsoft Resource Library \(x86\)$/,
	/^Microsoft Visio Template$/,
	/^Midtown Madness game data archive$/,
	/^Midtown Madness 2 game data archive$/,
	/^MIME Base64 encoded MP4 video$/,
	/^Mind Games - (Checkers|Renju) saved game$/,
	/^MIT CADR Lisp Machine disk image$/,
	/^MLT XML$/,
	/^Moebius Graphics Library$/,
	/^Motorhead game data rchive$/,
	/^Mozilla Archive Format \(gen\)$/,
	/^Mozilla Firefox browser extension$/,
	/^Multiplan spreadsheet \(v1\.0x\)$/,
	/^Music Macro Language$/,
	/^MS-DOS Backup Control data \(v3\.30-5\.xx\)$/,
	/^Navitel/,
	/^Neko bytecode$/,
	/^NEOchrome Master bitmap$/,	// Many IFF ILBM files share the same keywords
	/^NeoDraw Palette$/,
	/^NetStumbler NS1 log$/,
	/^NeXtMidas Macro \(with rem\)$/,
	/^NINJA 2\.0 Patch$/,
	/^Nintendo Binary Revolution SEQuence$/,
	/^Nintendo Yaz0 compressed data$/,
	/^Nitro game data archive$/,
	/^NTFS Master File Table$/,
	/^Norton Textra Writer Document \(v2\.x\)$/,
	/^Novastorm Media audio$/,
	/^NPS Image Editor Script$/,
	/^OctaMED MCNT multi-module$/,
	/^Open Packaging Conventions container$/,
	/^OpenSceneGraph (legacy|native) binary format$/,
	/^OpenTTD savegame$/,
	/^OpenVPN profile/,
	/^Orda: Severnyi Veter game data$/,
	/^Org-mode$/,
	/^Organize! Form$/,
	/^Origin Project$/,
	/^OS\/2 Installable File System$/,
	/^OS\/2 Network Information File$/,
	/^OziExplorer Map$/,
	/^PageTech Metafile$/,
	/^P-touch Editor Label$/,
	/^Packaged Indigo Renderer Material$/,
	/^Parrot Digital sample \(raw\)$/,
	/^Pac-in-Time game data$/,
	/^Pacific Warrior 2: Dogfight game data archive$/,
	/^PackDir compressed archive$/,
	/^Palm HanDBase DB$/,
	/^Palm Markup Language$/,
	/^PALASM \(var\.2\)$/,
	/^Panorama database$/,
	/^Parquet storage format$/,
	/^Particles format \((big|little)-endian\)$/,
	/^PC Secure encrypted \(V\d\)$/,	// so I actually found files that ARE this, but it's a pretty weak magic and we can't do anything with em, so we just mark it weak
	/^PC-Calc spreadsheet \(gen\)$/,
	/^PCjr Speech Adapter CVSD audio$/,
	/^Peak audio info$/,
	/^Pepakura Designer work$/,
	/^Perfect Keyboard macro set$/,
	/^PerFROM Pro Form$/,
	/^PERQemu Hard Disk image$/,
	/^Personal Paint encrypted bitmap$/,	// Found these in the wild, distrubuted with demo version of program, but it's weak magic and can't decrypt them easily anyways
	/^PFS File database$/,
	/^PFS:Write document\/outline \(v2\.x\)$/,
	/^Photogenics matrix data$/,
	/^Pileup format$/,
	/^Playmation Surface$/,
	/^PlayStation RSD (animation|Coordinates|Material) \(gen\)$/,
	/^PlayStation Sound Source Data$/,
	/^PNG Animation$/,
	/^PNG Stereo bitmap$/,
	/^Port Royale 4 game data$/,
	/^Portable Image File bitmap$/,
	/^Portfolio BASIC compiled 16 bit MS-DOS binary$/,
	/^Poser (Hair data|pose)$/,
	/^Prisoner Of Ice game data archive$/,
	/^PRO-NTO Application$/,
	/^ProductView Packaged Structure and Drawing$/,
	/^Programmer's Notepad text Clips$/,
	/^Project Dogwaffle mixing palette \(type 2\)$/,
	/^Psion Organiser Block data$/,
	/^Psion OVAL Control$/,
	/^PPrint Color map$/,
	/^PPrint Image$/,
	/^Qt Resource Collection$/,
	/^Quartus Symbols data$/,
	/^Quick Database$/,
	/^QuickBooks Import\/Export Interchange File$/,
	/^R3D data stream$/,
	/^RealTime subtitles$/,
	/^Red Baron 3D game data archive$/,
	/^Red Sector Demo-Maker vector/,
	/^Relocatable object file format$/,
	/^ReplaceEm fileset$/,
	/^ReqAttack Image$/,
	/^ROOT format$/,
	/^Rumble Roses game data archive$/,
	/^Rush Font$/,
	/^Safari Cookies$/,
	/^SAPI Sound Driver$/,
	/^SBStudio II song$/,
	/^Scalable Vector Graphics \(var\.3\)$/,
	/^Scene Generator scene settings$/,
	/^Scribe Markup$/,
	/^Sentry Spelling-Checker user dictionary$/,
	/^Session Description Protocol \(with rem\)$/,
	/^Silver Scene$/,
	/^SimAnt saved game \(Amiga\)$/,
	/^Sinclair TR-DOS disk image$/,
	/^Skyland's Star game data$/,
	/^SLAC lossless compressed audio$/,
	/^Slayer engine Texture$/,
	/^SMAC compressed data$/,
	/^smARTWORK Printed Circuit Board project$/,
	/^SMS Coastline data$/,
	/^SMS Super File$/,
	/^SMS XYZ data$/,
	/^Snowdrop game data archive$/,
	/^Sony SELF - SPRX format$/,
	/^SoundSlimmer compressed audio$/,
	/^SoundTool audio$/,
	/^SPLASH - Lenex compressed data$/,
	/^Starlink Data Format$/,
	/^StarMath Forumla \(v2\.0\)$/,
	/^Stata Data format \(v114, BE\)$/,
	/^Streaming Progressive Image Format bitmap$/,
	/^STT disk image$/,
	/^Studio Folio Corsage compressed palette archive$/,
	/^Stunt Island Film$/,
	/^STW disk image$/,
	/^Sublime Text Menu$/,
	/^Sublime Text Project$/,
	/^Sudden Strike 2 game data archive$/,
	/^Summation Document Image Information Load File$/,
	/^Super-Card Ami II copier$/,
	/^Super Data Format$/,
	/^Surfer Grid$/,
	/^Sweet Home 3D design \(generic\)$/,
	/^Synchronized Multimedia Integration Language$/,
	/^Syntrillium Cool Edit Transform Effect$/,
	/^Syntrillium CoolEdit Filter$/,
	/^SynWrite Snippet$/,
	/^Taxman's Retro Engine v5 3D Model$/,
	/^Team Developer \/ SQLWindows application \(binary\)$/,
	/^TecPlot ascii file format$/,
	/^Telegram Desktop Encrypted File$/,
	/^TeslaCrypt\/Cryptowall encrypted$/,
	/^Text602 document \(v1\.x\)$/,
	/^The Riddle of Master Lu game data archive$/,
	/^The Terminator: Dawn of Fate game data archive$/,
	/^The Ur-Quan Masters game data archive$/,
	/^The Witcher 2 game data archive$/,
	/^Tim Newport-Peace's Special Use Airspace Format$/,
	/^Timed Text Markup Language$/,
	/^Tools Media Corp\. Texture$/,
	/^Tomato ARM config format$/,
	/^TOPO topographic Data$/,
	/^Tornado mission Data$/,
	/^Total Commander Lister extension \(plugin\)$/,
	/^Total War campaign settings \(var 1\)$/,
	/^Transform compressed$/,
	/^TriSound Voice Set$/,
	/^TurboCALC SpreadSheet$/,
	/^Trilobyte SVGA FLICK\/Groovie Player Script$/,
	/^TV-SHOW Script$/,
	/^Twist Update script$/,
	/^Ultimo Primo SnapShot$/,
	/^UltraEdit Wordfile$/,
	/^UNIMod created by APlayer$/,
	/^Universal Data Format$/,
	/^Universe Sandbox simulation$/,
	/^Universal Data Format \(lower case\)$/,
	/^Universal Scene Description Zipped AR format \(generic\)$/,
	/^Vaulty obscured$/,
	/^VBIN container$/,
	/^VCOM Web Easy album$/,
	/^Verilog source code \(with rem 2\)$/,
	/^VersaCAD 2D Library \(MS-DOS\)$/,
	/^VHSIC Hardware Description Language \(with rem\)$/,
	/^Vice HotKeys$/,
	/^Vice Keyboard Mapping$/,
	/^Visual CertExam Simulator Exam$/,	// this is some sort of weird match that seems to match files that are not anywhere close to this format, not sure why
	/^Virtual Home Space Builder 3D Space/,
	/^Virtual TI skin/,
	/^Vivaldi Music Dump format$/,	// found these in item #1392 but no converter and magic is weak and no ext
	/^VP-Planner Plus spreadsheet$/,
	/^VP-Planner Worksheet \(v1\.0\)$/,
	/^Vue D'Esprit 4 Atmosphere Preset$/,
	/^VYM Mind Map$/,
	/^WeatherLink Binary Weather data$/,
	/^WebAssembly module \(binary\)$/,
	/^Westwood game data Archive$/,
	/^Wii Effect controls$/,
	/^Wii Effects Textures$/,
	/^Wildfire convolution$/,
	/^Win16\/32 Executable Delphi generic$/,
	/^Win32 EXE PECompact compressed \(generic\)$/,
	/^Winamp EQ Settings File$/,
	/^WinArcadia Recording\/macro$/,
	/^Windows 95 passwords$/,
	/^Windows ActiveX control$/,
	/^Windows Control Panel Item \(generic\)$/,
	/^Windows Installer Merge Module$/,
	/^Windows Installer Patch$/,
	/^Windows Media Download package$/,
	/^Windows Media Player skin$/,
	/^Windows NTBackup archive$/,
	/^Windows Script File$/,
	/^Windows Shadow spooler/,
	/^Windows SDK Setup Transform script$/,
	/^WindowBlinds skin-theme$/,
	/^WinGenea Data File$/,
	/^WinImage archive data$/,
	/^WinImage disk image$/,
	/^Wii Model Animation$/,
	/^WordPerfect Executive Spreadsheet$/,
	/^WorldWide Telescope collection$/,
	/^wxWindows - wxPython Resource$/,
	/^X-CAD Screen Menu$/,
	/^X-CAD SoftFont$/,
	/^XBaze data base$/,
	/^Xbox 360 (CON|LIVE) container data file$/,
	/^Xbox Game Profile Data$/,
	/^Xbox Packed Resource$/,
	/^Xerox EDMICS-RLC bitmap/,
	/^XFBIN CPK game data container$/,
	/^Xilam DERF video$/,
	/^Xilinx User Constraints File$/,
	/^XML-Data Reduced$/,
	/^XMOD format module$/,
	/^XTrkCAD parameters$/,
	/^XYPad Drawing$/,
	/^YSFlight Surface$/,
	/^Z-Axis game data archive$/,
	/^Zing! directory tree$/,
	/^Zip Chunker fragment$/,
	/^Zoot information processor database$/,
	/^ZZT Game Creation System/
];
