/* eslint-disable prefer-named-capture-group */

// These magics are VERY untrustworthy and any detections against them should be noted as such
export const WEAK_VALUES =
[
	// siegfried: WEAK checks
	/^fmt\/(111|134|208|347|473|1260|1555|1556|1562)( |$)/,
	/^x-fmt\/(111|157|195|342)( |$)/,

	// dexmagic: WEAK checks
	/^IFF CAT file$/,
	
	// FILE: Very weak checks:
	/^, /,
	/^0421 Alliant compact executable/,
	/^370 sysV/,
	/^370 XA sysV/,
	/^386 compact demand paged pure executable/,
	/^0420 Alliant virtual executable/,
	/^5View capture file/,
	/^64-bit XCOFF executable or object module/,
	/^68k Blit/,
	/80386 COFF executable/,
	/^BALANCE NS32000/,
	/ BCS executable/,
	/^BIOS \(ia32\) ROM Ext/,
	/^ABComp archive data/,
	/^AIX core file/,
	/^ALAN game data/,
	/^Alpha compressed COFF$/,
	/^Alpha u-code object$/,
	/^amd 29k /,
	/^AmigaOS bitmap font/,
	/^Android binary XML/,
	/^Apache Avro/,
	/^Apache Hadoop Sequence/,
	/^Apache Hive RC file/,
	/^Apache ORC/,
	/^Apache Parquet/,
	/^Apollo m68k COFF executable/,
	/^apollo a88k COFF executable/,
	/^Apple DiskCopy 4.2 image/,
	/^Arhangel archive data/,
	/^ARM COFF/,
	/^ARMv7 Thumb/,
	/^Award BIOS Logo, \d+ x \d+/,
	/^assembler source/,
	/^b\.out/,
	/^basic-16 executable/,
	/^Bio-Rad \.PIC Image File/,
	/^Biosig\/Heka Patchmaster$/,
	/^BS image/,
	/^CBM BASIC, SYS/,
	/^Clarion Developer/,
	/^CLIPPER COFF executable/,
	/^COFF format/,
	/^Common Data Format \(Version 2\.5 or earlier\) data$/,
	/^compacted data$/,
	/^Compiled PSI/,
	/^Convex old-style/,
	/^Cytovision FISH Probe file/,
	/^ctab data/,
	/^ddis\/ddif/,
	/^diff output/,
	/^dBase I[IV]I? DBT/,
	/^DIF \(/,
	/^disk quotas file/,
	/DIY-Thermocam raw data/,
	/^DOS .*backed up sequence/,
	/^DOS 2\.0 backup id file/,
	/^Dyalog APL/,
	/^EBCDIC text/,
	/ECOFF executable/,
	/^Encore demand-paged executable/,
	/^Encore executable/,
	/^Encore pure executable/,
	/^Encore not stripped/,
	/^Encore unsupported executable/,
	/^ERROR: \(null\)/,
	/^executable \(RISC System\/6000/,
	/^firmware .*revision/,
	/^FIT image data/,
	/^fsav macro virus signatures/,
	/^GDSII Stream file/,
	/^gfxboot compiled html help/,
	/^Generic INItialization configuration/,
	/^GEM NOSIG/,
	/^GeoSwath RDF$/,
	/^GLF_BINARY_LSB_FIRST/,
	/^GPG encrypted data/,
	/^GTA archive/,
	/^GTA audio index data/,
	/^GTA in-game/,
	/^GTA script/,
	/^GTA1 /,
	/^GTA2 /,
	/^Hitachi SH/,
	/^HTML document/,
	/^HP 48 binary/,
	/^hp\d00/,
	/^iAPX 286 executable/,
	/^ICE authority data$/,
	/^IFF data$/,
	/^Intel ia64 COFF/,
	/^Intel.* Common Object File Format/,
	/^IRIS Showcase file/,
	/^IRIS Showcase template/,
	/jffs2 filesystem data/,
	/^Java.*KeyStore$/,
	/^JSON data$/,
	/^JVT NAL sequence/,
	/^little|big endian ispell/,
	/^locale data table/,
	/^Logitech Compress archive data$/,
	/^lif file/,
	/^LZMA compressed data/,
	/^MacBinary.* INVALID date/,
	/^MacBinary II,/,
	/^Maple help database$/,
	/^Matlab v4/,
	/^mc68k COFF /,
	/^mc68k executable/,
	/^Microsoft a\.out/,
	/^MIPSE[BL][ -]/,
	/^MIT scheme/,
	/^MMDF mailbox$/,
	/^Motorola S-Record; binary data in text format$/,
	/^MPEG-4 LOAS/,
	/^MS Windows COFF /,
	/^MSXiE archive data/,
	/^mumps avl|blt global/,
	/^MySQL table definition file Version 0/,
	/^MySQL table definition file.* type UNKNOWN, MySQL version 0/,
	/^Novell LANalyzer capture file$/,
	/^Oak Technologies printer stream/,
	/^old Microsoft 8086 x.out/,
	/^old packed data$/,
	/^old timezone data$/,
	/^OpenPGP Public Key/,
	/^OpenPGP Secret Key/,
	/^Par archive data$/,
	/^Perkin-Elmer executable/,
	/^PEX Binary Archive$/,
	/^Picasso 64 Image$/,
	/^PGP encrypted data/,
	/^PGP key security ring/,
	/^PGP Secret Sub-key/,
	/^PGP symmetric key encrypted data/,
	/^PDP-11/,
	/^QL OS dump data/,
	/^QuArk archive data/,
	/^RAD Game Tools Smacker Multimedia/,
	/^RAGE Package Format/,
	/^raw G3/,
	/^RDI Acoustic Doppler Current Profiler/,
	/^RenderWare.* data/,
	/^RIFF \((big|little)-endian\) data$/,
	/^RISC OS outline font data/,
	/^Sega FILM\/CPK Multimedia/,
	/^shared library TTComp archive data/,
	/^SPARC demand paged/,
	/^SoftQuad DESC or font file binary/,
	/^SoftQuad troff Context intermediate$/,
	/^Sony PlayStation Audio/,
	/^Sony PlayStation PSX image/,
	/^Spectrum \.TAP data/,
	/spot sensor temperature/,
	/^SysEx File/,
	/^StarOffice Gallery theme/,
	/^structured file$/,
	/^SVR2 executable/,
	/^SVR2 pure executable/,
	/^SVr\d curses screen image/,
	/^system ID:/,
	/^TeX font metric data/,
	/^troff or preprocessor input/,
	/^Targa image data/,
	/^Tower\/XP rel/,
	/^Tower32/,
	/^unicos \(cray\) executable/,
	/^unknown demand paged pure executable/,
	/^unknown readable demand paged pure executable/,
	/^VAX-order/,
	/^very short file/,
	/^VISX image file/,
	/^WE32000 COFF/,
	/^Windows boot log/,
	/^Windows Precompiled iNF/,
	/^Windows SYSTEM.INI/,
	/^Windows WIN.INI/,
	/^X1 archive data/,
	/^X11 SNF font data/,
	/^XENIX 8086 relocatable/,
	/^x86 OpenFirmware FORTH Dictionary/,
	/^xBase index/,
	/^YAC archive data/,
	/^Zebra Metafile graphic/,

	// TRID: Checks just 1-3 bytes:
	/^1ST Word Plus Document$/,
	/^22DISK format Definition \(tokenized\)$/,
	/^3D-Calc spreadsheet$/,
	/^5View capture/,
	/^Adobe PRC 3D model$/,
	/^Advanced DB Master data/,
	/^Affix file$/,
	/^Agfa\/Matrix SCODL bitmap$/,
	/^Alpha Four data \(generic\)$/,
	/^Amiga bitmap Font/,
	/^AngelCode Bitmap Font \(binary\)$/,
	/^Any Password data$/,
	/^APE ProSystem Atari 8-bit disk image/,
	/^ArcMac compressed archive$/,
	/^ARHANGEL compressed archive$/,
	/^Atari XE Executable$/,
	/^AutoDesk Revit Indexed Point Cloud$/,
	/^Award BIOS logo bitmap \(\d+x\d+\)/,
	/^AYFX Editor Bank$/,
	/^BALZ compressed data$/,
	/^Bcrypt Encrypted data$/,
	/^Beasts and Bumpkins game data archive$/,
	/^Bennet Yee's face format bitmap$/,
	/Berkeley vfont/,
	/^Big Crunch compressed file$/,
	/^Bio-Rad Image\(s\) bitmap$/,
	/^Binary NX Vibration data/,
	/^BitKeeper history data$/,
	/^BSArc compressed archive$/,
	/^BSC ZX Spectrum tape data$/,
	/^C64 Hires bitmap$/,
	/^Calcomp raster bitmap$/,
	/^Cardwar Cards deck$/,
	/^CauseWay Compressor compressed data$/,
	/^Chasm CEL bitmap$/,
	/^Commodore .*BASIC .*program/,
	/^Compact compressed data/,
	/^Continuous Wave Accelerometry data$/,
	/^Corel Color Palette$/,
	/^Cosmigo Pro Motion SPRites sequence/,
	/^CP\/M 3 COM binary \(no RSX\)$/,
	/^CyberAIDS infected Apple 2 executable$/,
	/^Cybiko Picture bitmap$/,
	/^dBASE IV Multiple index$/,
	/^DEGAS low-res compressed bitmap$/,
	/^DEGAS med-res bitmap$/,
	/^DEGAS med-res compressed bitmap$/,
	/^DEGAS hi-res bitmap$/,
	/^DEGAS hi-res compressed bitmap$/,
	/^DeltaCad drawing$/,
	/^Dialogic VOX \(telephony\) encoded audio$/,
	/^DICOM medical imaging bitmap/,
	/^Digital Micrograph Script$/,
	/^Digital Video$/,
	/^DiskDupe 5\.12 disk image$/,
	/^Doodle bitmap$/,
	/^Drazpaint \(C64\) bitmap$/,
	/^DRM Content Format - Separate delivery file \(generic\)$/,
	/^eFax Document \(generic\)$/,
	/^Error Code Modeler$/,
	/^eXtended Triton Format$/,
	/^F64 disk image$/,
	/^FineCrypt encrypted \(v2\.0\)$/,
	/^FinePrint saved output$/,
	/^Flexible Line Interpretation bitmap$/,
	/^F\.R\.A\.C\. project$/,
	/^Freeze! compressed archive$/,
	/^GEM bitmap/,
	/^Generic INI configuration$/,
	/^Genecyst save state$/,
	/^GIF bitmap \(generic\)$/,
	/^Glest 3D model$/,
	/^GNU Privacy Guard public keyring \(generic\)$/,
	/^GraphiCode Programmable Device Format$/,
	/^Hrust 1 packed/,
	/^interLaced eXtensible Trace/,
	/^Interpaint bitmap$/,
	/^IPLAY Enterprise Video$/,
	/^ISIS sketch$/,
	/^Janome NH10000 Sewing Machine Stitch$/,	// eslint-disable-line unicorn/better-regex
	/^JCALG1 compressed data$/,
	/^JMP data table \(v5\)$/,
	/^Jovian Logic VI bitmap$/,
	/^Jupiter Ace snapshot$/,
	/^Koala Paint/,
	/^Legend text$/,
	/^Leonard Guides compiled data$/,
	/^Lepton bitmap/,
	/^Lepton UJG bitmap$/,
	/^Lotus Manuscript bitmap$/,
	/^LTAC compressed audio/,
	/^LTP Nuclear ZX tape image$/,
	/^Luxor ABC80 tokenized BASIC source$/,
	/^LZMA compressed archive$/,
	/^Mallard BASIC/,
	/^Maple Common Binary file \(generic\)$/,
	/^Max Payne data file$/,
	/^MegaZeux world data/,
	/^Melco embroidery design$/,
	/^Microsoft Help \(old\)$/,
	/^MosASCII Project Workspace$/,
	/^Mozart functor$/,
	/^MP3 audio/,
	/^MSX BASIC tokenized source$/,
	/^MSX ROM Image$/,
	/^MSX2 ROM Image$/,
	/^NEC JIS encoded file$/,
	/^null bytes$/,
	/^Oberon V4 Symbol data$/,
	/^OCAD map$/,
	/^OMF - Relocatable Object Module Format$/,
	/^OS\/2 Bitmap Graphics Array \(generic\)$/,
	/^Pack compressed data \(old\)$/,
	/^packPNM compressed /,
	/^PaintShow Font$/,
	/^Panasonic JR Cassette image$/,
	/^PC9801 rip$/,
	/^PEA compressed archive/,
	/^PGN \(Portable Gaming Notation\) Compressed format$/,
	/^Philips Respironics M-Series data format$/,
	/^Pixel image$/,
	/^PKCS #7 Signature/,
	/^Pretty Good Privacy \(PGP\) Private\/Secret Keyring/,
	/^PrintFox\/Pagefox bitmap/,
	/^ProHance Mouse Keys Definition table/,
	/^Python Pickle serialized data/,
	/^Qmage encoded data$/,
	/^Quarterdeck Mosaic History$/,
	/^raw Group 3 FAX bitmap$/,
	/^RPG Maker data$/,
	/^RR compressed data archive$/,
	/^Scamper WARTS storage$/,
	/^Scitex Continuous Tone bitmap$/,
	/^SCODL image$/,
	/^ScreenBuilder image$/,
	/^Siemens archived SMS messages$/,
	/^SMS Material$/,
	/^Source Code Control System history data$/,
	/^Sound Club 2 sound bank$/,
	/^Spectrum 512 Anispec animation$/,
	/^Spectrum emulator snapshot$/,
	/^SpeedScript document \(C64\)$/,
	/^SQ2 compressed data$/,
	/^Stunt Island Resource$/,
	/^SuperCard Pro flux image$/,
	/^Text - UTF-16/,
	/^TextEngine document \(generic\)$/,
	/^That's Write document$/,
	/^The Bee Archiver compressed archive$/,
	/^THOR compressed data$/,
	/^Trilo Tracker chiptune$/,
	/^TTComp archive/,
	/^Turbo Pascal Symbol Table$/,
	/^VGAPaint 386 module$/,
	/^Videoscape GEO mesh/,
	/^VisiCalc spreadsheet$/,
	/^WhatsApp encrypted database$/,
	/^WillDraw Drawing$/,
	/^WinArcadia Saved State$/,
	/^WinPlot data/,
	/^WLF WolfMAME recording info$/,
	/^WordPerfect document \(Amiga\)$/,
	/^X1 compressed archive$/,
	/^XBase DataBase \(generic\)$/,
	/^Xexor disk image$/,
	/^Z-Code V\d adventure for Infocom Z-Machine$/,
	/^Zoo filter compressed format$/,
	/^ZX Microdrive cartridge image$/,
	
	// TRID: Checks for almost all zeroes or mostly just single repeating values:
	/^A-Robots Fighting Robot Object$/,
	/^Acorn RISC OS font/,
	/^Adobe PhotoShop Brush$/,
	/^Aquarius Cassette tape image$/,
	/^Atari NeoChrome bitmap$/,
	/^AudioZip encoded audio$/,
	/^BackupExpress Pro$/,
	/^bCAD Drawing$/,
	/^BS-DOS MB-0\d disk image$/,
	/^Cadwork 2D Catalog$/,
	/^CAJ database$/,
	/^ChemDraw model$/,
	/^Chompsters level data$/,
	/^Coordinate 3D \(subset of ADTech File Format\) file \(more generic\)$/,
	/^Dr\. Halo Font$/,
	/^Dyalog APL transfer$/,
	/^EPOC data store/,
	/^FastCopy DIM disk image$/,
	/^File List Creator list$/,
	/^Generic RIFF container$/,
	/^HandStory eBook$/,
	/^HP Logical Interchange Format disk image$/,
	/^Id Software Quake II Cinematic video$/,
	/^Immaginaria TNG 3D scene$/,
	/^Install Maker( Pro)? project$/,
	/^Intel CPU Microcode$/,
	/^Inset PIX bitmap$/,
	/^Lotus 123\/Symphony worksheet\/format\/configuration \(V1-V2\)$/,
	/^M99 compressed data$/,
	/^MacBinary [12]$/,
	/^Matlab Level 4 MAT-File \(big-endian\)$/,
	/^Microsoft Works for Mac document \(v1\.0\)$/,
	/^Memo File Apollo Database Engine$/,
	/^MICROCAD Drawing$/,
	/^Music Craft Score$/,
	/^NIfTI-2 data format/,
	/^Open Minecraft Note Block Studio Song/,
	/^OS\/2 Dynamic Link Library \(no DOS stub\)$/,
	/^Palantir WinTime Plan$/,
	/^Pegasus SPS encoded audio$/,
	/^Photoshop Action$/,
	/^PlayStation Hierarchical 3D Model Data$/,
	/^PlayStation high-speed 3D modeling data$/,
	/^PM XV bitmap/,
	/^PSX TMD 3d Model$/,
	/^Quarterdeck Installation Package$/,
	/^Sierra AGI music format$/,
	/^Speccy snapshot$/,
	/^Sybase iAnywhere database files$/,
	/^Take Command: 2nd Manassas game data archive$/,
	/^TERSE compressed archive$/,
	/^Torque Dynamix Three Space model/,
	/^UbiArt Framework Cooked Asset$/,
	/^V-Ray Material \(binary\)$/,
	/^Virtual MC-10\/Alice tape image$/,
	/^Visi On Overlay$/,
	/^VXD Driver$/,
	/^VZ200\/300 image \(type F1\)$/,
	/^Warajevo Tape image format$/,
	/^Windows Device Dependent Bitmap$/,
	/^Windows Jump List$/,
	/^Windows Icon/,

	// TRID: Weak in some other way, such as commonly used word prefix/global string or ascending/descending bytes
	/^AceMoney data$/,
	/^Adobe FilmStrip$/,
	/^Amiga Disk image File \(generic\)$/,
	/^Audio Disk Jockey bank$/,
	/^BibTeX references$/,
	/^Dan Bricklin's Demo/,
	/^Encrypted Blender 3D data$/,
	/^Fine Artist Chunked format/,
	/^Game Boy Advance ROM$/,
	/^Generic IFF container$/,
	/^Grand Theft Auto: San Andreas game data archive$/,
	/^Haines NFF scene/,
	/^Macromedia Director Java Resource - Video$/,
	/^MegaZeux game$/,
	/^Music Macro Language$/,
	/^Novastorm Media audio$/,
	/^OpenSceneGraph native binary format$/,
	/^OpenVPN profile/,
	/^Pacific Warrior 2: Dogfight game data archive$/,
	/^PackDir compressed archive$/,
	/^Poser pose$/,
	/^Scalable Vector Graphics \(var\.3\)$/,
	/^Session Description Protocol \(with rem\)$/,
	/^SMS Super File$/,
	/^Stunt Island Film$/,
	/^Summation Document Image Information Load File$/,
	/^TeslaCrypt\/Cryptowall encrypted$/,
	/^Xilinx User Constraints File$/
];
